module Orb
  module Models
    module Prices
      type external_price_id_fetch_params =
        { external_price_id: String } & Orb::Internal::Type::request_parameters

      class ExternalPriceIDFetchParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor external_price_id: String

        def initialize: (
          external_price_id: String,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> {
          external_price_id: String,
          request_options: Orb::RequestOptions
        }
      end
    end
  end
end
