module Orb
  module Resources
    class Plans
      class ExternalPlanID
        class Versions
          def create: (
            String external_plan_id,
            version: Integer,
            ?add_adjustments: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::AddAdjustment]?,
            ?add_prices: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::AddPrice]?,
            ?remove_adjustments: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::RemoveAdjustment]?,
            ?remove_prices: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::RemovePrice]?,
            ?replace_adjustments: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::ReplaceAdjustment]?,
            ?replace_prices: ::Array[Orb::Plans::ExternalPlanID::VersionCreateParams::ReplacePrice]?,
            ?set_as_default: bool?,
            ?request_options: Orb::request_opts
          ) -> Orb::Models::Plans::ExternalPlanID::VersionCreateResponse

          def retrieve: (
            String version,
            external_plan_id: String,
            ?request_options: Orb::request_opts
          ) -> Orb::Models::Plans::ExternalPlanID::VersionRetrieveResponse

          def initialize: (client: Orb::Client) -> void
        end
      end
    end
  end
end
