module Orb
  module Models
    module Plans
      type external_plan_id_fetch_params =
        {  } & Orb::Internal::Type::request_parameters

      class ExternalPlanIDFetchParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        def initialize: (?request_options: Orb::request_opts) -> void
      end
    end
  end
end
