module Orb
  module Models
    module Plans
      type external_plan_id_fetch_params = {  } & Orb::request_parameters

      class ExternalPlanIDFetchParams < Orb::BaseModel
        extend Orb::RequestParameters::Converter
        include Orb::RequestParameters

        def initialize:
          (request_options: Orb::request_opts) -> void
          | (
            ?Orb::Models::Plans::external_plan_id_fetch_params
            | Orb::BaseModel data
          ) -> void

        def to_h: -> Orb::Models::Plans::external_plan_id_fetch_params
      end
    end
  end
end
