module Orb
  module Resources
    class Customers
      class Costs
        def list: (
          String customer_id,
          ?currency: String?,
          ?timeframe_end: Time?,
          ?timeframe_start: Time?,
          ?view_mode: Orb::Models::Customers::CostListParams::view_mode?,
          ?request_options: Orb::request_opts
        ) -> Orb::Models::Customers::CostListResponse

        def list_by_external_id: (
          String external_customer_id,
          ?currency: String?,
          ?timeframe_end: Time?,
          ?timeframe_start: Time?,
          ?view_mode: Orb::Models::Customers::CostListByExternalIDParams::view_mode?,
          ?request_options: Orb::request_opts
        ) -> Orb::Models::Customers::CostListByExternalIDResponse

        def initialize: (client: Orb::Client) -> void
      end
    end
  end
end
