module Orb
  module Resources
    class Plans
      class Versions
        def create: (
          String plan_id,
          version: Integer,
          ?add_adjustments: ::Array[Orb::Plans::VersionCreateParams::AddAdjustment]?,
          ?add_prices: ::Array[Orb::Plans::VersionCreateParams::AddPrice]?,
          ?remove_adjustments: ::Array[Orb::Plans::VersionCreateParams::RemoveAdjustment]?,
          ?remove_prices: ::Array[Orb::Plans::VersionCreateParams::RemovePrice]?,
          ?replace_adjustments: ::Array[Orb::Plans::VersionCreateParams::ReplaceAdjustment]?,
          ?replace_prices: ::Array[Orb::Plans::VersionCreateParams::ReplacePrice]?,
          ?set_as_default: bool?,
          ?request_options: Orb::request_opts
        ) -> Orb::Models::Plans::VersionCreateResponse

        def retrieve: (
          String version,
          plan_id: String,
          ?request_options: Orb::request_opts
        ) -> Orb::Models::Plans::VersionRetrieveResponse

        def initialize: (client: Orb::Client) -> void
      end
    end
  end
end
