module Orb
  module Type
    module Union
      include Orb::Type::Converter

      private def self.known_variants: -> ::Array[[Symbol?, (^-> Orb::Type::Converter::input)]]

      def self.derefed_variants: -> ::Array[[Symbol?, top]]

      def self.variants: -> ::Array[top]

      private def self.discriminator: (Symbol property) -> void

      private def self.variant: (
        Symbol
        | ::Hash[Symbol, top]
        | ^-> Orb::Type::Converter::input
        | Orb::Type::Converter::input key,
        ?::Hash[Symbol, top]
        | ^-> Orb::Type::Converter::input
        | Orb::Type::Converter::input spec
      ) -> void

      private def self.resolve_variant: (
        top value
      ) -> Orb::Type::Converter::input?

      def ===: (top other) -> bool

      def ==: (top other) -> bool

      def coerce: (top value, state: Orb::Type::Converter::state) -> top

      def dump: (top value) -> top
    end
  end
end
