module Orb
  module Type
    class Unknown
      extend Orb::Type::Converter

      def self.===: (top other) -> bool

      def self.==: (top other) -> bool

      def self.coerce: (top value, state: Orb::Type::Converter::state) -> top

      def self.dump: (top value) -> top
    end
  end
end
