module Orb
  module Models
    type alert_retrieve_params = {  } & Orb::request_parameters

    class AlertRetrieveParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::alert_retrieve_params
    end
  end
end
