module Orb
  module Models
    type alert_create_for_subscription_params =
      {
        thresholds: Array[Orb::Models::AlertCreateForSubscriptionParams::Threshold],
        type: Orb::Models::AlertCreateForSubscriptionParams::type_,
        metric_id: String?
      }
      & Orb::request_parameters

    class AlertCreateForSubscriptionParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor thresholds: Array[Orb::Models::AlertCreateForSubscriptionParams::Threshold]

      attr_accessor type: Orb::Models::AlertCreateForSubscriptionParams::type_

      attr_accessor metric_id: String?

      def initialize:
        (
          thresholds: Array[Orb::Models::AlertCreateForSubscriptionParams::Threshold],
          type: Orb::Models::AlertCreateForSubscriptionParams::type_,
          metric_id: String?,
          request_options: Orb::request_opts
        ) -> void
        | (
          ?Orb::Models::alert_create_for_subscription_params
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::alert_create_for_subscription_params

      type threshold = { value: Float }

      class Threshold < Orb::BaseModel
        attr_accessor value: Float

        def initialize:
          (value: Float) -> void
          | (
            ?Orb::Models::AlertCreateForSubscriptionParams::threshold
            | Orb::BaseModel data
          ) -> void

        def to_hash: -> Orb::Models::AlertCreateForSubscriptionParams::threshold
      end

      type type_ =
        :usage_exceeded
        | :cost_exceeded
        | :credit_balance_depleted
        | :credit_balance_dropped
        | :credit_balance_recovered

      class Type < Orb::Enum
        USAGE_EXCEEDED: :usage_exceeded
        COST_EXCEEDED: :cost_exceeded
        CREDIT_BALANCE_DEPLETED: :credit_balance_depleted
        CREDIT_BALANCE_DROPPED: :credit_balance_dropped
        CREDIT_BALANCE_RECOVERED: :credit_balance_recovered

        def self.values: -> Array[Orb::Models::AlertCreateForSubscriptionParams::type_]
      end
    end
  end
end
