module Orb
  module Models
    type alert_disable_params =
      { subscription_id: String? } & Orb::Internal::Type::request_parameters

    class AlertDisableParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor subscription_id: String?

      def initialize: (
        ?subscription_id: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        subscription_id: String?,
        request_options: Orb::RequestOptions
      }
    end
  end
end
