module Orb
  module Models
    type alert_retrieve_params =
      { alert_id: String } & Orb::Internal::Type::request_parameters

    class AlertRetrieveParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor alert_id: String

      def initialize: (
        alert_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> { alert_id: String, request_options: Orb::RequestOptions }
    end
  end
end
