module Orb
  module Models
    type alert_create_for_subscription_params =
      {
        subscription_id: String,
        thresholds: ::Array[Orb::Threshold],
        type: Orb::Models::AlertCreateForSubscriptionParams::type_,
        grouping_keys: ::Array[String]?,
        metric_id: String?,
        price_filters: ::Array[Orb::AlertCreateForSubscriptionParams::PriceFilter]?,
        pricing_unit_id: String?,
        threshold_overrides: ::Array[Orb::AlertCreateForSubscriptionParams::ThresholdOverride]?
      }
      & Orb::Internal::Type::request_parameters

    class AlertCreateForSubscriptionParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor subscription_id: String

      attr_accessor thresholds: ::Array[Orb::Threshold]

      attr_accessor type: Orb::Models::AlertCreateForSubscriptionParams::type_

      attr_accessor grouping_keys: ::Array[String]?

      attr_accessor metric_id: String?

      attr_accessor price_filters: ::Array[Orb::AlertCreateForSubscriptionParams::PriceFilter]?

      attr_accessor pricing_unit_id: String?

      attr_accessor threshold_overrides: ::Array[Orb::AlertCreateForSubscriptionParams::ThresholdOverride]?

      def initialize: (
        subscription_id: String,
        thresholds: ::Array[Orb::Threshold],
        type: Orb::Models::AlertCreateForSubscriptionParams::type_,
        ?grouping_keys: ::Array[String]?,
        ?metric_id: String?,
        ?price_filters: ::Array[Orb::AlertCreateForSubscriptionParams::PriceFilter]?,
        ?pricing_unit_id: String?,
        ?threshold_overrides: ::Array[Orb::AlertCreateForSubscriptionParams::ThresholdOverride]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        subscription_id: String,
        thresholds: ::Array[Orb::Threshold],
        type: Orb::Models::AlertCreateForSubscriptionParams::type_,
        grouping_keys: ::Array[String]?,
        metric_id: String?,
        price_filters: ::Array[Orb::AlertCreateForSubscriptionParams::PriceFilter]?,
        pricing_unit_id: String?,
        threshold_overrides: ::Array[Orb::AlertCreateForSubscriptionParams::ThresholdOverride]?,
        request_options: Orb::RequestOptions
      }

      type type_ = :usage_exceeded | :cost_exceeded

      module Type
        extend Orb::Internal::Type::Enum

        USAGE_EXCEEDED: :usage_exceeded
        COST_EXCEEDED: :cost_exceeded

        def self?.values: -> ::Array[Orb::Models::AlertCreateForSubscriptionParams::type_]
      end

      type price_filter =
        {
          field: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::field,
          operator: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::operator,
          values: ::Array[String]
        }

      class PriceFilter < Orb::Internal::Type::BaseModel
        attr_accessor field: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::field

        attr_accessor operator: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::operator

        attr_accessor values: ::Array[String]

        def initialize: (
          field: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::field,
          operator: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::operator,
          values: ::Array[String]
        ) -> void

        def to_hash: -> {
          field: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::field,
          operator: Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::operator,
          values: ::Array[String]
        }

        type field =
          :price_id | :item_id | :price_type | :currency | :pricing_unit_id

        module Field
          extend Orb::Internal::Type::Enum

          PRICE_ID: :price_id
          ITEM_ID: :item_id
          PRICE_TYPE: :price_type
          CURRENCY: :currency
          PRICING_UNIT_ID: :pricing_unit_id

          def self?.values: -> ::Array[Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::field]
        end

        type operator = :includes | :excludes

        module Operator
          extend Orb::Internal::Type::Enum

          INCLUDES: :includes
          EXCLUDES: :excludes

          def self?.values: -> ::Array[Orb::Models::AlertCreateForSubscriptionParams::PriceFilter::operator]
        end
      end

      type threshold_override =
        { group_values: ::Array[String], thresholds: ::Array[Orb::Threshold] }

      class ThresholdOverride < Orb::Internal::Type::BaseModel
        attr_accessor group_values: ::Array[String]

        attr_accessor thresholds: ::Array[Orb::Threshold]

        def initialize: (
          group_values: ::Array[String],
          thresholds: ::Array[Orb::Threshold]
        ) -> void

        def to_hash: -> {
          group_values: ::Array[String],
          thresholds: ::Array[Orb::Threshold]
        }
      end
    end
  end
end
