module Orb
  module Models
    type alert_create_for_external_customer_params =
      {
        currency: String,
        type: Orb::Models::AlertCreateForExternalCustomerParams::type_,
        thresholds: ::Array[Orb::Threshold]?
      }
      & Orb::Internal::Type::request_parameters

    class AlertCreateForExternalCustomerParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor currency: String

      attr_accessor type: Orb::Models::AlertCreateForExternalCustomerParams::type_

      attr_accessor thresholds: ::Array[Orb::Threshold]?

      def initialize: (
        currency: String,
        type: Orb::Models::AlertCreateForExternalCustomerParams::type_,
        ?thresholds: ::Array[Orb::Threshold]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        currency: String,
        type: Orb::Models::AlertCreateForExternalCustomerParams::type_,
        thresholds: ::Array[Orb::Threshold]?,
        request_options: Orb::RequestOptions
      }

      type type_ =
        :credit_balance_depleted
        | :credit_balance_dropped
        | :credit_balance_recovered

      module Type
        extend Orb::Internal::Type::Enum

        CREDIT_BALANCE_DEPLETED: :credit_balance_depleted
        CREDIT_BALANCE_DROPPED: :credit_balance_dropped
        CREDIT_BALANCE_RECOVERED: :credit_balance_recovered

        def self?.values: -> ::Array[Orb::Models::AlertCreateForExternalCustomerParams::type_]
      end
    end
  end
end
