module Orb
  module Models
    type alert_list_params =
      {
        created_at_gt: Time?,
        created_at_gte: Time?,
        created_at_lt: Time?,
        created_at_lte: Time?,
        cursor: String?,
        customer_id: String?,
        external_customer_id: String?,
        limit: Integer,
        subscription_id: String?
      }
      & Orb::request_parameters

    class AlertListParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor created_at_gt: Time?

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lt: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor cursor: String?

      attr_accessor customer_id: String?

      attr_accessor external_customer_id: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor subscription_id: String?

      def initialize: (
        ?created_at_gt: Time?,
        ?created_at_gte: Time?,
        ?created_at_lt: Time?,
        ?created_at_lte: Time?,
        ?cursor: String?,
        ?customer_id: String?,
        ?external_customer_id: String?,
        ?limit: Integer,
        ?subscription_id: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::alert_list_params
    end
  end
end
