module Orb
  module Models
    type alert_update_params =
      { thresholds: ::Array[Orb::AlertUpdateParams::Threshold] }
      & Orb::Internal::Type::request_parameters

    class AlertUpdateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor thresholds: ::Array[Orb::AlertUpdateParams::Threshold]

      def initialize: (
        thresholds: ::Array[Orb::AlertUpdateParams::Threshold],
        ?request_options: Orb::request_opts
      ) -> void

      type threshold = { value: Float }

      class Threshold < Orb::Internal::Type::BaseModel
        attr_accessor value: Float

        def initialize: (value: Float) -> void
      end
    end
  end
end
