module Orb
  module Models
    type alert_enable_params =
      { subscription_id: String? } & Orb::request_parameters

    class AlertEnableParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor subscription_id: String?

      def initialize: (
        ?subscription_id: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::alert_enable_params
    end
  end
end
