module Orb
  module Models
    type allocation =
      {
        allows_rollover: bool,
        currency: String,
        custom_expiration: Orb::CustomExpiration?,
        filters: ::Array[Orb::Allocation::Filter],
        license_type_id: String?
      }

    class Allocation < Orb::Internal::Type::BaseModel
      attr_accessor allows_rollover: bool

      attr_accessor currency: String

      attr_accessor custom_expiration: Orb::CustomExpiration?

      attr_reader filters: ::Array[Orb::Allocation::Filter]?

      def filters=: (
        ::Array[Orb::Allocation::Filter]
      ) -> ::Array[Orb::Allocation::Filter]

      attr_accessor license_type_id: String?

      def initialize: (
        allows_rollover: bool,
        currency: String,
        custom_expiration: Orb::CustomExpiration?,
        ?filters: ::Array[Orb::Allocation::Filter],
        ?license_type_id: String?
      ) -> void

      def to_hash: -> {
        allows_rollover: bool,
        currency: String,
        custom_expiration: Orb::CustomExpiration?,
        filters: ::Array[Orb::Allocation::Filter],
        license_type_id: String?
      }

      type filter =
        {
          field: Orb::Models::Allocation::Filter::field,
          operator: Orb::Models::Allocation::Filter::operator,
          values: ::Array[String]
        }

      class Filter < Orb::Internal::Type::BaseModel
        attr_accessor field: Orb::Models::Allocation::Filter::field

        attr_accessor operator: Orb::Models::Allocation::Filter::operator

        attr_accessor values: ::Array[String]

        def initialize: (
          field: Orb::Models::Allocation::Filter::field,
          operator: Orb::Models::Allocation::Filter::operator,
          values: ::Array[String]
        ) -> void

        def to_hash: -> {
          field: Orb::Models::Allocation::Filter::field,
          operator: Orb::Models::Allocation::Filter::operator,
          values: ::Array[String]
        }

        type field =
          :price_id | :item_id | :price_type | :currency | :pricing_unit_id

        module Field
          extend Orb::Internal::Type::Enum

          PRICE_ID: :price_id
          ITEM_ID: :item_id
          PRICE_TYPE: :price_type
          CURRENCY: :currency
          PRICING_UNIT_ID: :pricing_unit_id

          def self?.values: -> ::Array[Orb::Models::Allocation::Filter::field]
        end

        type operator = :includes | :excludes

        module Operator
          extend Orb::Internal::Type::Enum

          INCLUDES: :includes
          EXCLUDES: :excludes

          def self?.values: -> ::Array[Orb::Models::Allocation::Filter::operator]
        end
      end
    end
  end
end
