module Orb
  module Models
    type amount_discount_interval =
      {
        amount_discount: String,
        applies_to_price_interval_ids: ::Array[String],
        discount_type: Orb::Models::AmountDiscountInterval::discount_type,
        end_date: Time?,
        filters: ::Array[Orb::AmountDiscountInterval::Filter],
        start_date: Time
      }

    class AmountDiscountInterval < Orb::Internal::Type::BaseModel
      attr_accessor amount_discount: String

      attr_accessor applies_to_price_interval_ids: ::Array[String]

      attr_accessor discount_type: Orb::Models::AmountDiscountInterval::discount_type

      attr_accessor end_date: Time?

      attr_accessor filters: ::Array[Orb::AmountDiscountInterval::Filter]

      attr_accessor start_date: Time

      def initialize: (
        amount_discount: String,
        applies_to_price_interval_ids: ::Array[String],
        discount_type: Orb::Models::AmountDiscountInterval::discount_type,
        end_date: Time?,
        filters: ::Array[Orb::AmountDiscountInterval::Filter],
        start_date: Time
      ) -> void

      def to_hash: -> {
        amount_discount: String,
        applies_to_price_interval_ids: ::Array[String],
        discount_type: Orb::Models::AmountDiscountInterval::discount_type,
        end_date: Time?,
        filters: ::Array[Orb::AmountDiscountInterval::Filter],
        start_date: Time
      }

      type discount_type = :amount

      module DiscountType
        extend Orb::Internal::Type::Enum

        AMOUNT: :amount

        def self?.values: -> ::Array[Orb::Models::AmountDiscountInterval::discount_type]
      end

      type filter =
        {
          field: Orb::Models::AmountDiscountInterval::Filter::field,
          operator: Orb::Models::AmountDiscountInterval::Filter::operator,
          values: ::Array[String]
        }

      class Filter < Orb::Internal::Type::BaseModel
        attr_accessor field: Orb::Models::AmountDiscountInterval::Filter::field

        attr_accessor operator: Orb::Models::AmountDiscountInterval::Filter::operator

        attr_accessor values: ::Array[String]

        def initialize: (
          field: Orb::Models::AmountDiscountInterval::Filter::field,
          operator: Orb::Models::AmountDiscountInterval::Filter::operator,
          values: ::Array[String]
        ) -> void

        def to_hash: -> {
          field: Orb::Models::AmountDiscountInterval::Filter::field,
          operator: Orb::Models::AmountDiscountInterval::Filter::operator,
          values: ::Array[String]
        }

        type field =
          :price_id | :item_id | :price_type | :currency | :pricing_unit_id

        module Field
          extend Orb::Internal::Type::Enum

          PRICE_ID: :price_id
          ITEM_ID: :item_id
          PRICE_TYPE: :price_type
          CURRENCY: :currency
          PRICING_UNIT_ID: :pricing_unit_id

          def self?.values: -> ::Array[Orb::Models::AmountDiscountInterval::Filter::field]
        end

        type operator = :includes | :excludes

        module Operator
          extend Orb::Internal::Type::Enum

          INCLUDES: :includes
          EXCLUDES: :excludes

          def self?.values: -> ::Array[Orb::Models::AmountDiscountInterval::Filter::operator]
        end
      end
    end
  end
end
