module Orb
  module Models
    type amount_discount =
      {
        amount_discount: String,
        discount_type: Orb::Models::AmountDiscount::discount_type,
        applies_to_price_ids: ::Array[String]?,
        filters: ::Array[Orb::AmountDiscount::Filter]?,
        reason: String?
      }

    class AmountDiscount < Orb::Internal::Type::BaseModel
      attr_accessor amount_discount: String

      attr_accessor discount_type: Orb::Models::AmountDiscount::discount_type

      attr_accessor applies_to_price_ids: ::Array[String]?

      attr_accessor filters: ::Array[Orb::AmountDiscount::Filter]?

      attr_accessor reason: String?

      def initialize: (
        amount_discount: String,
        discount_type: Orb::Models::AmountDiscount::discount_type,
        ?applies_to_price_ids: ::Array[String]?,
        ?filters: ::Array[Orb::AmountDiscount::Filter]?,
        ?reason: String?
      ) -> void

      def to_hash: -> {
        amount_discount: String,
        discount_type: Orb::Models::AmountDiscount::discount_type,
        applies_to_price_ids: ::Array[String]?,
        filters: ::Array[Orb::AmountDiscount::Filter]?,
        reason: String?
      }

      type discount_type = :amount

      module DiscountType
        extend Orb::Internal::Type::Enum

        AMOUNT: :amount

        def self?.values: -> ::Array[Orb::Models::AmountDiscount::discount_type]
      end

      type filter =
        {
          field: Orb::Models::AmountDiscount::Filter::field,
          operator: Orb::Models::AmountDiscount::Filter::operator,
          values: ::Array[String]
        }

      class Filter < Orb::Internal::Type::BaseModel
        attr_accessor field: Orb::Models::AmountDiscount::Filter::field

        attr_accessor operator: Orb::Models::AmountDiscount::Filter::operator

        attr_accessor values: ::Array[String]

        def initialize: (
          field: Orb::Models::AmountDiscount::Filter::field,
          operator: Orb::Models::AmountDiscount::Filter::operator,
          values: ::Array[String]
        ) -> void

        def to_hash: -> {
          field: Orb::Models::AmountDiscount::Filter::field,
          operator: Orb::Models::AmountDiscount::Filter::operator,
          values: ::Array[String]
        }

        type field =
          :price_id | :item_id | :price_type | :currency | :pricing_unit_id

        module Field
          extend Orb::Internal::Type::Enum

          PRICE_ID: :price_id
          ITEM_ID: :item_id
          PRICE_TYPE: :price_type
          CURRENCY: :currency
          PRICING_UNIT_ID: :pricing_unit_id

          def self?.values: -> ::Array[Orb::Models::AmountDiscount::Filter::field]
        end

        type operator = :includes | :excludes

        module Operator
          extend Orb::Internal::Type::Enum

          INCLUDES: :includes
          EXCLUDES: :excludes

          def self?.values: -> ::Array[Orb::Models::AmountDiscount::Filter::operator]
        end
      end
    end
  end
end
