module Orb
  module Models
    type auto_collection_model =
      {
        enabled: bool?,
        next_attempt_at: Time?,
        num_attempts: Integer?,
        previously_attempted_at: Time?
      }

    class AutoCollectionModel < Orb::BaseModel
      attr_accessor enabled: bool?

      attr_accessor next_attempt_at: Time?

      attr_accessor num_attempts: Integer?

      attr_accessor previously_attempted_at: Time?

      def initialize:
        (
          enabled: bool?,
          next_attempt_at: Time?,
          num_attempts: Integer?,
          previously_attempted_at: Time?
        ) -> void
        | (?Orb::Models::auto_collection_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::auto_collection_model
    end
  end
end
