module Orb
  module Models
    type billing_cycle_anchor_configuration_model =
      { day: Integer, month: Integer?, year: Integer? }

    class BillingCycleAnchorConfigurationModel < Orb::BaseModel
      attr_accessor day: Integer

      attr_accessor month: Integer?

      attr_accessor year: Integer?

      def initialize:
        (day: Integer, month: Integer?, year: Integer?) -> void
        | (
          ?Orb::Models::billing_cycle_anchor_configuration_model
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::billing_cycle_anchor_configuration_model
    end
  end
end
