module Orb
  module Models
    type billing_cycle_relative_date = :start_of_term | :end_of_term

    class BillingCycleRelativeDate < Orb::Enum
      START_OF_TERM: :start_of_term
      END_OF_TERM: :end_of_term

      def self.values: -> ::Array[Orb::Models::billing_cycle_relative_date]
    end
  end
end
