module Orb
  module Models
    type billable_metric =
      {
        id: String,
        description: String?,
        item: Orb::Item,
        metadata: ::Hash[Symbol, String],
        name: String,
        sql: String,
        status: Orb::Models::BillableMetric::status,
        parameter_definitions: ::Array[::Hash[Symbol, top]]?
      }

    class BillableMetric < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor description: String?

      attr_accessor item: Orb::Item

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor name: String

      attr_accessor sql: String

      attr_accessor status: Orb::Models::BillableMetric::status

      attr_accessor parameter_definitions: ::Array[::Hash[Symbol, top]]?

      def initialize: (
        id: String,
        description: String?,
        item: Orb::Item,
        metadata: ::Hash[Symbol, String],
        name: String,
        sql: String,
        status: Orb::Models::BillableMetric::status,
        ?parameter_definitions: ::Array[::Hash[Symbol, top]]?
      ) -> void

      def to_hash: -> {
        id: String,
        description: String?,
        item: Orb::Item,
        metadata: ::Hash[Symbol, String],
        name: String,
        sql: String,
        status: Orb::Models::BillableMetric::status,
        parameter_definitions: ::Array[::Hash[Symbol, top]]?
      }

      type status = :active | :draft | :archived

      module Status
        extend Orb::Internal::Type::Enum

        ACTIVE: :active
        DRAFT: :draft
        ARCHIVED: :archived

        def self?.values: -> ::Array[Orb::Models::BillableMetric::status]
      end
    end
  end
end
