module Orb
  module Models
    type conversion_rate_config =
      Orb::UnitConversionRateConfig | Orb::TieredConversionRateConfig

    module ConversionRateConfig
      extend Orb::Internal::Type::Union

      def self?.variants: -> ::Array[Orb::Models::conversion_rate_config]
    end
  end
end
