module Orb
  module Models
    type coupon_list_params =
      {
        cursor: String?,
        limit: Integer,
        redemption_code: String?,
        show_archived: bool?
      }
      & Orb::Internal::Type::request_parameters

    class CouponListParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor cursor: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor redemption_code: String?

      attr_accessor show_archived: bool?

      def initialize: (
        ?cursor: String?,
        ?limit: Integer,
        ?redemption_code: String?,
        ?show_archived: bool?,
        ?request_options: Orb::request_opts
      ) -> void
    end
  end
end
