module Orb
  module Models
    type coupon_list_params =
      {
        cursor: String?,
        limit: Integer,
        redemption_code: String?,
        show_archived: bool?
      }
      & Orb::request_parameters

    class CouponListParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor cursor: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> void

      attr_accessor redemption_code: String?

      attr_accessor show_archived: bool?

      def initialize:
        (
          cursor: String?,
          limit: Integer,
          redemption_code: String?,
          show_archived: bool?,
          request_options: Orb::request_opts
        ) -> void
        | (?Orb::Models::coupon_list_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::coupon_list_params
    end
  end
end
