module Orb
  module Models
    type coupon_fetch_params = {  } & Orb::Internal::Type::request_parameters

    class CouponFetchParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void
    end
  end
end
