module Orb
  module Models
    type coupon_archive_params = {  } & Orb::request_parameters

    class CouponArchiveParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::coupon_archive_params
    end
  end
end
