module Orb
  module Models
    type coupon_redemption =
      { coupon_id: String, end_date: Time?, start_date: Time }

    class CouponRedemption < Orb::Internal::Type::BaseModel
      attr_accessor coupon_id: String

      attr_accessor end_date: Time?

      attr_accessor start_date: Time

      def initialize: (
        coupon_id: String,
        end_date: Time?,
        start_date: Time
      ) -> void

      def to_hash: -> { coupon_id: String, end_date: Time?, start_date: Time }
    end
  end
end
