module Orb
  module Models
    type credit_note_summary_model =
      {
        id: String,
        credit_note_number: String,
        memo: String?,
        reason: String,
        total: String,
        type: String,
        voided_at: Time?
      }

    class CreditNoteSummaryModel < Orb::BaseModel
      attr_accessor id: String

      attr_accessor credit_note_number: String

      attr_accessor memo: String?

      attr_accessor reason: String

      attr_accessor total: String

      attr_accessor type: String

      attr_accessor voided_at: Time?

      def initialize:
        (
          id: String,
          credit_note_number: String,
          memo: String?,
          reason: String,
          total: String,
          type: String,
          voided_at: Time?
        ) -> void
        | (
          ?Orb::Models::credit_note_summary_model | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::credit_note_summary_model
    end
  end
end
