module Orb
  module Models
    type credit_block_list_invoices_params =
      { block_id: String } & Orb::Internal::Type::request_parameters

    class CreditBlockListInvoicesParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor block_id: String

      def initialize: (
        block_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> { block_id: String, request_options: Orb::RequestOptions }
    end
  end
end
