module Orb
  module Models
    type credit_note_fetch_params = {  } & Orb::request_parameters

    class CreditNoteFetchParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::credit_note_fetch_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::credit_note_fetch_params
    end
  end
end
