module Orb
  module Models
    type credit_note_list_params =
      { cursor: String?, limit: Integer } & Orb::request_parameters

    class CreditNoteListParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor cursor: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> void

      def initialize:
        (
          cursor: String?,
          limit: Integer,
          request_options: Orb::request_opts
        ) -> void
        | (?Orb::Models::credit_note_list_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::credit_note_list_params
    end
  end
end
