module Orb
  module Models
    type credit_ledger_entries_model =
      {
        data: ::Array[Orb::Models::credit_ledger_entry_model],
        pagination_metadata: Orb::Models::PaginationMetadata
      }

    class CreditLedgerEntriesModel < Orb::BaseModel
      attr_accessor data: ::Array[Orb::Models::credit_ledger_entry_model]

      attr_accessor pagination_metadata: Orb::Models::PaginationMetadata

      def initialize:
        (
          data: ::Array[Orb::Models::credit_ledger_entry_model],
          pagination_metadata: Orb::Models::PaginationMetadata
        ) -> void
        | (
          ?Orb::Models::credit_ledger_entries_model | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::credit_ledger_entries_model
    end
  end
end
