module Orb
  module Models
    type credit_note_list_params =
      {
        created_at_gt: Time?,
        created_at_gte: Time?,
        created_at_lt: Time?,
        created_at_lte: Time?,
        cursor: String?,
        limit: Integer
      }
      & Orb::Internal::Type::request_parameters

    class CreditNoteListParams < Orb::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor created_at_gt: Time?

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lt: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor cursor: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?created_at_gt: Time?,
        ?created_at_gte: Time?,
        ?created_at_lt: Time?,
        ?created_at_lte: Time?,
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::credit_note_list_params
    end
  end
end
