module Orb
  module Models
    type credit_block_list_invoices_response =
      {
        block: Orb::Models::CreditBlockListInvoicesResponse::Block,
        invoices: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Invoice]
      }

    class CreditBlockListInvoicesResponse < Orb::Internal::Type::BaseModel
      attr_accessor block: Orb::Models::CreditBlockListInvoicesResponse::Block

      attr_accessor invoices: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Invoice]

      def initialize: (
        block: Orb::Models::CreditBlockListInvoicesResponse::Block,
        invoices: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Invoice]
      ) -> void

      def to_hash: -> {
        block: Orb::Models::CreditBlockListInvoicesResponse::Block,
        invoices: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Invoice]
      }

      type block =
        {
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::CreditBlockListInvoicesResponse::Block::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::CreditBlockListInvoicesResponse::Block::status,
          credit_allocation: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation?
        }

      class Block < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor balance: Float

        attr_accessor credit_block_source: Orb::Models::CreditBlockListInvoicesResponse::Block::credit_block_source

        attr_accessor effective_date: Time?

        attr_accessor expiry_date: Time?

        attr_accessor filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter]

        attr_accessor maximum_initial_balance: Float?

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_accessor per_unit_cost_basis: String?

        attr_accessor status: Orb::Models::CreditBlockListInvoicesResponse::Block::status

        attr_accessor credit_allocation: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation?

        def initialize: (
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::CreditBlockListInvoicesResponse::Block::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::CreditBlockListInvoicesResponse::Block::status,
          ?credit_allocation: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation?
        ) -> void

        def to_hash: -> {
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::CreditBlockListInvoicesResponse::Block::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::CreditBlockListInvoicesResponse::Block::status,
          credit_allocation: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation?
        }

        type credit_block_source = :allocation | :top_up | :manual

        module CreditBlockSource
          extend Orb::Internal::Type::Enum

          ALLOCATION: :allocation
          TOP_UP: :top_up
          MANUAL: :manual

          def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::credit_block_source]
        end

        type filter =
          {
            field: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::field,
            operator: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::operator,
            values: ::Array[String]
          }

        class Filter < Orb::Internal::Type::BaseModel
          attr_accessor field: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::field

          attr_accessor operator: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::operator

          attr_accessor values: ::Array[String]

          def initialize: (
            field: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::field,
            operator: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::operator,
            values: ::Array[String]
          ) -> void

          def to_hash: -> {
            field: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::field,
            operator: Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::operator,
            values: ::Array[String]
          }

          type field =
            :price_id | :item_id | :price_type | :currency | :pricing_unit_id

          module Field
            extend Orb::Internal::Type::Enum

            PRICE_ID: :price_id
            ITEM_ID: :item_id
            PRICE_TYPE: :price_type
            CURRENCY: :currency
            PRICING_UNIT_ID: :pricing_unit_id

            def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::field]
          end

          type operator = :includes | :excludes

          module Operator
            extend Orb::Internal::Type::Enum

            INCLUDES: :includes
            EXCLUDES: :excludes

            def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::Filter::operator]
          end
        end

        type status = :active | :pending_payment

        module Status
          extend Orb::Internal::Type::Enum

          ACTIVE: :active
          PENDING_PAYMENT: :pending_payment

          def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::status]
        end

        type credit_allocation =
          {
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter],
            license_type_id: String?
          }

        class CreditAllocation < Orb::Internal::Type::BaseModel
          attr_accessor allows_rollover: bool

          attr_accessor currency: String

          attr_accessor custom_expiration: Orb::CustomExpiration?

          attr_accessor item_id: String

          attr_reader filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter]?

          def filters=: (
            ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter]
          ) -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter]

          attr_accessor license_type_id: String?

          def initialize: (
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            ?filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter],
            ?license_type_id: String?
          ) -> void

          def to_hash: -> {
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            filters: ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter],
            license_type_id: String?
          }

          type filter =
            {
              field: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::field,
              operator: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::operator,
              values: ::Array[String]
            }

          class Filter < Orb::Internal::Type::BaseModel
            attr_accessor field: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::field

            attr_accessor operator: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::operator

            attr_accessor values: ::Array[String]

            def initialize: (
              field: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::field,
              operator: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::operator,
              values: ::Array[String]
            ) -> void

            def to_hash: -> {
              field: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::field,
              operator: Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::operator,
              values: ::Array[String]
            }

            type field =
              :price_id | :item_id | :price_type | :currency | :pricing_unit_id

            module Field
              extend Orb::Internal::Type::Enum

              PRICE_ID: :price_id
              ITEM_ID: :item_id
              PRICE_TYPE: :price_type
              CURRENCY: :currency
              PRICING_UNIT_ID: :pricing_unit_id

              def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::field]
            end

            type operator = :includes | :excludes

            module Operator
              extend Orb::Internal::Type::Enum

              INCLUDES: :includes
              EXCLUDES: :excludes

              def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Block::CreditAllocation::Filter::operator]
            end
          end
        end
      end

      type invoice =
        {
          id: String,
          customer: Orb::CustomerMinified,
          invoice_number: String,
          status: Orb::Models::CreditBlockListInvoicesResponse::Invoice::status,
          subscription: Orb::SubscriptionMinified?
        }

      class Invoice < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor customer: Orb::CustomerMinified

        attr_accessor invoice_number: String

        attr_accessor status: Orb::Models::CreditBlockListInvoicesResponse::Invoice::status

        attr_accessor subscription: Orb::SubscriptionMinified?

        def initialize: (
          id: String,
          customer: Orb::CustomerMinified,
          invoice_number: String,
          status: Orb::Models::CreditBlockListInvoicesResponse::Invoice::status,
          subscription: Orb::SubscriptionMinified?
        ) -> void

        def to_hash: -> {
          id: String,
          customer: Orb::CustomerMinified,
          invoice_number: String,
          status: Orb::Models::CreditBlockListInvoicesResponse::Invoice::status,
          subscription: Orb::SubscriptionMinified?
        }

        type status = :issued | :paid | :synced | :void | :draft

        module Status
          extend Orb::Internal::Type::Enum

          ISSUED: :issued
          PAID: :paid
          SYNCED: :synced
          VOID: :void
          DRAFT: :draft

          def self?.values: -> ::Array[Orb::Models::CreditBlockListInvoicesResponse::Invoice::status]
        end
      end
    end
  end
end
