module Orb
  module Models
    type credit_note_fetch_params = {  } & Orb::request_parameters

    class CreditNoteFetchParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::credit_note_fetch_params
    end
  end
end
