module Orb
  module Models
    type custom_expiration =
      {
        duration: Integer,
        duration_unit: Orb::Models::CustomExpiration::duration_unit
      }

    class CustomExpiration < Orb::Internal::Type::BaseModel
      attr_accessor duration: Integer

      attr_accessor duration_unit: Orb::Models::CustomExpiration::duration_unit

      def initialize: (
        duration: Integer,
        duration_unit: Orb::Models::CustomExpiration::duration_unit
      ) -> void

      def to_hash: -> {
        duration: Integer,
        duration_unit: Orb::Models::CustomExpiration::duration_unit
      }

      type duration_unit = :day | :month

      module DurationUnit
        extend Orb::Internal::Type::Enum

        DAY: :day
        MONTH: :month

        def self?.values: -> ::Array[Orb::Models::CustomExpiration::duration_unit]
      end
    end
  end
end
