module Orb
  module Models
    type customer_update_by_external_id_params = {  } & Orb::request_parameters

    class CustomerUpdateByExternalIDParams < Orb::Models::EditCustomerModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (
          ?Orb::Models::customer_update_by_external_id_params
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::customer_update_by_external_id_params
    end
  end
end
