module Orb
  module Models
    type customer_costs_model =
      { data: ::Array[Orb::Models::AggregatedCostModel] }

    class CustomerCostsModel < Orb::BaseModel
      attr_accessor data: ::Array[Orb::Models::AggregatedCostModel]

      def initialize:
        (data: ::Array[Orb::Models::AggregatedCostModel]) -> void
        | (?Orb::Models::customer_costs_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::customer_costs_model
    end
  end
end
