module Orb
  module Models
    type customer_delete_params = {  } & Orb::request_parameters

    class CustomerDeleteParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::customer_delete_params
    end
  end
end
