module Orb
  module Models
    type customer_update_params =
      {
        customer_id: String,
        accounting_sync_configuration: Orb::NewAccountingSyncConfiguration?,
        additional_emails: ::Array[String]?,
        auto_collection: bool?,
        auto_issuance: bool?,
        billing_address: Orb::AddressInput?,
        currency: String?,
        email: String?,
        email_delivery: bool?,
        external_customer_id: String?,
        hierarchy: Orb::CustomerHierarchyConfig?,
        metadata: ::Hash[Symbol, String?]?,
        name: String?,
        payment_configuration: Orb::CustomerUpdateParams::PaymentConfiguration?,
        payment_provider: Orb::Models::CustomerUpdateParams::payment_provider?,
        payment_provider_id: String?,
        reporting_configuration: Orb::NewReportingConfiguration?,
        shipping_address: Orb::AddressInput?,
        tax_configuration: Orb::Models::CustomerUpdateParams::tax_configuration?,
        tax_id: Orb::CustomerTaxID?
      }
      & Orb::Internal::Type::request_parameters

    class CustomerUpdateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor customer_id: String

      attr_accessor accounting_sync_configuration: Orb::NewAccountingSyncConfiguration?

      attr_accessor additional_emails: ::Array[String]?

      attr_accessor auto_collection: bool?

      attr_accessor auto_issuance: bool?

      attr_accessor billing_address: Orb::AddressInput?

      attr_accessor currency: String?

      attr_accessor email: String?

      attr_accessor email_delivery: bool?

      attr_accessor external_customer_id: String?

      attr_accessor hierarchy: Orb::CustomerHierarchyConfig?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      attr_accessor name: String?

      attr_accessor payment_configuration: Orb::CustomerUpdateParams::PaymentConfiguration?

      attr_accessor payment_provider: Orb::Models::CustomerUpdateParams::payment_provider?

      attr_accessor payment_provider_id: String?

      attr_accessor reporting_configuration: Orb::NewReportingConfiguration?

      attr_accessor shipping_address: Orb::AddressInput?

      attr_accessor tax_configuration: Orb::Models::CustomerUpdateParams::tax_configuration?

      attr_accessor tax_id: Orb::CustomerTaxID?

      def initialize: (
        customer_id: String,
        ?accounting_sync_configuration: Orb::NewAccountingSyncConfiguration?,
        ?additional_emails: ::Array[String]?,
        ?auto_collection: bool?,
        ?auto_issuance: bool?,
        ?billing_address: Orb::AddressInput?,
        ?currency: String?,
        ?email: String?,
        ?email_delivery: bool?,
        ?external_customer_id: String?,
        ?hierarchy: Orb::CustomerHierarchyConfig?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?name: String?,
        ?payment_configuration: Orb::CustomerUpdateParams::PaymentConfiguration?,
        ?payment_provider: Orb::Models::CustomerUpdateParams::payment_provider?,
        ?payment_provider_id: String?,
        ?reporting_configuration: Orb::NewReportingConfiguration?,
        ?shipping_address: Orb::AddressInput?,
        ?tax_configuration: Orb::Models::CustomerUpdateParams::tax_configuration?,
        ?tax_id: Orb::CustomerTaxID?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        customer_id: String,
        accounting_sync_configuration: Orb::NewAccountingSyncConfiguration?,
        additional_emails: ::Array[String]?,
        auto_collection: bool?,
        auto_issuance: bool?,
        billing_address: Orb::AddressInput?,
        currency: String?,
        email: String?,
        email_delivery: bool?,
        external_customer_id: String?,
        hierarchy: Orb::CustomerHierarchyConfig?,
        metadata: ::Hash[Symbol, String?]?,
        name: String?,
        payment_configuration: Orb::CustomerUpdateParams::PaymentConfiguration?,
        payment_provider: Orb::Models::CustomerUpdateParams::payment_provider?,
        payment_provider_id: String?,
        reporting_configuration: Orb::NewReportingConfiguration?,
        shipping_address: Orb::AddressInput?,
        tax_configuration: Orb::Models::CustomerUpdateParams::tax_configuration?,
        tax_id: Orb::CustomerTaxID?,
        request_options: Orb::RequestOptions
      }

      type payment_configuration =
        {
          payment_providers: ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]
        }

      class PaymentConfiguration < Orb::Internal::Type::BaseModel
        attr_reader payment_providers: ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]?

        def payment_providers=: (
          ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]
        ) -> ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]

        def initialize: (
          ?payment_providers: ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]
        ) -> void

        def to_hash: -> {
          payment_providers: ::Array[Orb::CustomerUpdateParams::PaymentConfiguration::PaymentProvider]
        }

        type payment_provider =
          {
            provider_type: Orb::Models::CustomerUpdateParams::PaymentConfiguration::PaymentProvider::provider_type,
            excluded_payment_method_types: ::Array[String]
          }

        class PaymentProvider < Orb::Internal::Type::BaseModel
          attr_accessor provider_type: Orb::Models::CustomerUpdateParams::PaymentConfiguration::PaymentProvider::provider_type

          attr_reader excluded_payment_method_types: ::Array[String]?

          def excluded_payment_method_types=: (
            ::Array[String]
          ) -> ::Array[String]

          def initialize: (
            provider_type: Orb::Models::CustomerUpdateParams::PaymentConfiguration::PaymentProvider::provider_type,
            ?excluded_payment_method_types: ::Array[String]
          ) -> void

          def to_hash: -> {
            provider_type: Orb::Models::CustomerUpdateParams::PaymentConfiguration::PaymentProvider::provider_type,
            excluded_payment_method_types: ::Array[String]
          }

          type provider_type = :stripe

          module ProviderType
            extend Orb::Internal::Type::Enum

            STRIPE: :stripe

            def self?.values: -> ::Array[Orb::Models::CustomerUpdateParams::PaymentConfiguration::PaymentProvider::provider_type]
          end
        end
      end

      type payment_provider =
        :quickbooks
        | :"bill.com"
        | :stripe_charge
        | :stripe_invoice
        | :netsuite
        | :netsuite_ampersand

      module PaymentProvider
        extend Orb::Internal::Type::Enum

        QUICKBOOKS: :quickbooks
        BILL_COM: :"bill.com"
        STRIPE_CHARGE: :stripe_charge
        STRIPE_INVOICE: :stripe_invoice
        NETSUITE: :netsuite
        NETSUITE_AMPERSAND: :netsuite_ampersand

        def self?.values: -> ::Array[Orb::Models::CustomerUpdateParams::payment_provider]
      end

      type tax_configuration =
        Orb::NewAvalaraTaxConfiguration
        | Orb::NewTaxJarConfiguration
        | Orb::NewSphereConfiguration
        | Orb::CustomerUpdateParams::TaxConfiguration::Numeral
        | Orb::CustomerUpdateParams::TaxConfiguration::Anrok
        | Orb::CustomerUpdateParams::TaxConfiguration::Stripe

      module TaxConfiguration
        extend Orb::Internal::Type::Union

        type numeral =
          {
            tax_exempt: bool,
            tax_provider: :numeral,
            automatic_tax_enabled: bool?
          }

        class Numeral < Orb::Internal::Type::BaseModel
          attr_accessor tax_exempt: bool

          attr_accessor tax_provider: :numeral

          attr_accessor automatic_tax_enabled: bool?

          def initialize: (
            tax_exempt: bool,
            ?automatic_tax_enabled: bool?,
            ?tax_provider: :numeral
          ) -> void

          def to_hash: -> {
            tax_exempt: bool,
            tax_provider: :numeral,
            automatic_tax_enabled: bool?
          }
        end

        type anrok =
          {
            tax_exempt: bool,
            tax_provider: :anrok,
            automatic_tax_enabled: bool?
          }

        class Anrok < Orb::Internal::Type::BaseModel
          attr_accessor tax_exempt: bool

          attr_accessor tax_provider: :anrok

          attr_accessor automatic_tax_enabled: bool?

          def initialize: (
            tax_exempt: bool,
            ?automatic_tax_enabled: bool?,
            ?tax_provider: :anrok
          ) -> void

          def to_hash: -> {
            tax_exempt: bool,
            tax_provider: :anrok,
            automatic_tax_enabled: bool?
          }
        end

        type stripe =
          {
            tax_exempt: bool,
            tax_provider: :stripe,
            automatic_tax_enabled: bool?
          }

        class Stripe < Orb::Internal::Type::BaseModel
          attr_accessor tax_exempt: bool

          attr_accessor tax_provider: :stripe

          attr_accessor automatic_tax_enabled: bool?

          def initialize: (
            tax_exempt: bool,
            ?automatic_tax_enabled: bool?,
            ?tax_provider: :stripe
          ) -> void

          def to_hash: -> {
            tax_exempt: bool,
            tax_provider: :stripe,
            automatic_tax_enabled: bool?
          }
        end

        def self?.variants: -> ::Array[Orb::Models::CustomerUpdateParams::tax_configuration]
      end
    end
  end
end
