module Orb
  module Models
    type customer_hierarchy_config =
      { child_customer_ids: ::Array[String], parent_customer_id: String? }

    class CustomerHierarchyConfig < Orb::Internal::Type::BaseModel
      attr_reader child_customer_ids: ::Array[String]?

      def child_customer_ids=: (::Array[String]) -> ::Array[String]

      attr_accessor parent_customer_id: String?

      def initialize: (
        ?child_customer_ids: ::Array[String],
        ?parent_customer_id: String?
      ) -> void

      def to_hash: -> {
        child_customer_ids: ::Array[String],
        parent_customer_id: String?
      }
    end
  end
end
