module Orb
  module Models
    type customer_accounting_sync_failed_webhook_event =
      {
        id: String,
        accounting_sync_record: Orb::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        customer: Orb::Customer,
        properties: Orb::CustomerAccountingSyncFailedWebhookEvent::Properties,
        type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::type_
      }

    class CustomerAccountingSyncFailedWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor accounting_sync_record: Orb::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord

      attr_accessor created_at: Time

      attr_accessor customer: Orb::Customer

      attr_accessor properties: Orb::CustomerAccountingSyncFailedWebhookEvent::Properties

      attr_accessor type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::type_

      def initialize: (
        id: String,
        accounting_sync_record: Orb::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        customer: Orb::Customer,
        properties: Orb::CustomerAccountingSyncFailedWebhookEvent::Properties,
        type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        accounting_sync_record: Orb::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        customer: Orb::Customer,
        properties: Orb::CustomerAccountingSyncFailedWebhookEvent::Properties,
        type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::type_
      }

      type accounting_sync_record =
        {
          id: String,
          customer_id: String,
          record_type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord::record_type,
          error_details: ::Hash[Symbol, top]?,
          provider_customer_id: String?,
          status: String?,
          sync_action: String?
        }

      class AccountingSyncRecord < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor customer_id: String

        attr_accessor record_type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord::record_type

        attr_accessor error_details: ::Hash[Symbol, top]?

        attr_accessor provider_customer_id: String?

        attr_accessor status: String?

        attr_accessor sync_action: String?

        def initialize: (
          id: String,
          customer_id: String,
          record_type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord::record_type,
          ?error_details: ::Hash[Symbol, top]?,
          ?provider_customer_id: String?,
          ?status: String?,
          ?sync_action: String?
        ) -> void

        def to_hash: -> {
          id: String,
          customer_id: String,
          record_type: Orb::Models::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord::record_type,
          error_details: ::Hash[Symbol, top]?,
          provider_customer_id: String?,
          status: String?,
          sync_action: String?
        }

        type record_type =
          :customer
          | :invoice
          | :transaction
          | :customer_balance_transaction
          | :credit_note
          | :subscription
          | :sales_order
          | :block

        module RecordType
          extend Orb::Internal::Type::Enum

          CUSTOMER: :customer
          INVOICE: :invoice
          TRANSACTION: :transaction
          CUSTOMER_BALANCE_TRANSACTION: :customer_balance_transaction
          CREDIT_NOTE: :credit_note
          SUBSCRIPTION: :subscription
          SALES_ORDER: :sales_order
          BLOCK: :block

          def self?.values: -> ::Array[Orb::Models::CustomerAccountingSyncFailedWebhookEvent::AccountingSyncRecord::record_type]
        end
      end

      type properties = { connection_type: String, failure_reason: String }

      class Properties < Orb::Internal::Type::BaseModel
        attr_accessor connection_type: String

        attr_accessor failure_reason: String

        def initialize: (
          connection_type: String,
          failure_reason: String
        ) -> void

        def to_hash: -> { connection_type: String, failure_reason: String }
      end

      type type_ = :"customer.accounting_sync_failed"

      module Type
        extend Orb::Internal::Type::Enum

        CUSTOMER_ACCOUNTING_SYNC_FAILED: :"customer.accounting_sync_failed"

        def self?.values: -> ::Array[Orb::Models::CustomerAccountingSyncFailedWebhookEvent::type_]
      end
    end
  end
end
