module Orb
  module Models
    type customer_update_params = {  } & Orb::request_parameters

    class CustomerUpdateParams < Orb::Models::EditCustomerModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::customer_update_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::customer_update_params
    end
  end
end
