module Orb
  module Models
    type customer_delete_params = {  } & Orb::Internal::Type::request_parameters

    class CustomerDeleteParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::customer_delete_params
    end
  end
end
