module Orb
  module Models
    type customer_sync_payment_methods_from_gateway_params =
      {  } & Orb::Internal::Type::request_parameters

    class CustomerSyncPaymentMethodsFromGatewayParams < Orb::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::customer_sync_payment_methods_from_gateway_params
    end
  end
end
