module Orb
  module Models
    type customer_sync_payment_methods_from_gateway_params =
      {  } & Orb::request_parameters

    class CustomerSyncPaymentMethodsFromGatewayParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (
          ?Orb::Models::customer_sync_payment_methods_from_gateway_params
          | Orb::BaseModel data
        ) -> void

      def to_h: -> Orb::Models::customer_sync_payment_methods_from_gateway_params
    end
  end
end
