module Orb
  module Models
    type customer_minified_model = { id: String, external_customer_id: String? }

    class CustomerMinifiedModel < Orb::BaseModel
      attr_accessor id: String

      attr_accessor external_customer_id: String?

      def initialize:
        (id: String, external_customer_id: String?) -> void
        | (?Orb::Models::customer_minified_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::customer_minified_model
    end
  end
end
