module Orb
  module Models
    type dimensional_price_groups_api =
      {
        data: ::Array[Orb::Models::DimensionalPriceGroup],
        pagination_metadata: Orb::Models::PaginationMetadata
      }

    class DimensionalPriceGroupsAPI < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::Models::DimensionalPriceGroup]

      attr_accessor pagination_metadata: Orb::Models::PaginationMetadata

      def initialize: (
        data: ::Array[Orb::Models::DimensionalPriceGroup],
        pagination_metadata: Orb::Models::PaginationMetadata
      ) -> void

      def to_hash: -> Orb::Models::dimensional_price_groups_api
    end
  end
end
