module Orb
  module Models
    type dimensional_price_groups_api =
      {
        data: ::Array[Orb::DimensionalPriceGroup],
        pagination_metadata: Orb::PaginationMetadata
      }

    class DimensionalPriceGroupsAPI < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::DimensionalPriceGroup]

      attr_accessor pagination_metadata: Orb::PaginationMetadata

      def initialize: (
        data: ::Array[Orb::DimensionalPriceGroup],
        pagination_metadata: Orb::PaginationMetadata
      ) -> void

      def to_hash: -> {
        data: ::Array[Orb::DimensionalPriceGroup],
        pagination_metadata: Orb::PaginationMetadata
      }
    end
  end
end
