module Orb
  module Models
    type dimensional_price_configuration_model =
      { dimension_values: ::Array[String], dimensional_price_group_id: String }

    class DimensionalPriceConfigurationModel < Orb::BaseModel
      attr_accessor dimension_values: ::Array[String]

      attr_accessor dimensional_price_group_id: String

      def initialize:
        (
          dimension_values: ::Array[String],
          dimensional_price_group_id: String
        ) -> void
        | (
          ?Orb::Models::dimensional_price_configuration_model
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::dimensional_price_configuration_model
    end
  end
end
