module Orb
  module Models
    type dimensional_price_group_retrieve_params =
      {  } & Orb::request_parameters

    class DimensionalPriceGroupRetrieveParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::dimensional_price_group_retrieve_params
    end
  end
end
