module Orb
  module Models
    type dimensional_price_group_create_params =
      {
        billable_metric_id: String,
        dimensions: ::Array[String],
        name: String,
        external_dimensional_price_group_id: String?,
        metadata: ::Hash[Symbol, String?]?
      }
      & Orb::request_parameters

    class DimensionalPriceGroupCreateParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor billable_metric_id: String

      attr_accessor dimensions: ::Array[String]

      attr_accessor name: String

      attr_accessor external_dimensional_price_group_id: String?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        billable_metric_id: String,
        dimensions: ::Array[String],
        name: String,
        ?external_dimensional_price_group_id: String?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::dimensional_price_group_create_params
    end
  end
end
