module Orb
  module Models
    type discount =
      Orb::Models::PercentageDiscount
      | Orb::Models::TrialDiscount
      | Orb::Models::UsageDiscount
      | Orb::Models::AmountDiscount

    class Discount < Orb::Union
      def self.variants: -> [Orb::Models::PercentageDiscount, Orb::Models::TrialDiscount, Orb::Models::UsageDiscount, Orb::Models::AmountDiscount]
    end
  end
end
