module Orb
  module Models
    type edit_plan_model =
      { external_plan_id: String?, metadata: ::Hash[Symbol, String?]? }

    class EditPlanModel < Orb::BaseModel
      attr_accessor external_plan_id: String?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize:
        (external_plan_id: String?, metadata: ::Hash[Symbol, String?]?) -> void
        | (?Orb::Models::edit_plan_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::edit_plan_model
    end
  end
end
