module Orb
  module Models
    type event_deprecate_response = { deprecated: String }

    class EventDeprecateResponse < Orb::Internal::Type::BaseModel
      attr_accessor deprecated: String

      def initialize: (deprecated: String) -> void

      def to_hash: -> { deprecated: String }
    end
  end
end
