module Orb
  module Models
    type event_ingest_response =
      {
        validation_failed: ::Array[Orb::Models::EventIngestResponse::ValidationFailed]
      }

    class EventIngestResponse < Orb::Internal::Type::BaseModel
      attr_accessor validation_failed: ::Array[Orb::Models::EventIngestResponse::ValidationFailed]

      def initialize: (
        validation_failed: ::Array[Orb::Models::EventIngestResponse::ValidationFailed]
      ) -> void

      def to_hash: -> {
        validation_failed: ::Array[Orb::Models::EventIngestResponse::ValidationFailed]
      }

      type validation_failed =
        { idempotency_key: String, validation_errors: ::Array[String] }

      class ValidationFailed < Orb::Internal::Type::BaseModel
        attr_accessor idempotency_key: String

        attr_accessor validation_errors: ::Array[String]

        def initialize: (
          idempotency_key: String,
          validation_errors: ::Array[String]
        ) -> void

        def to_hash: -> {
          idempotency_key: String,
          validation_errors: ::Array[String]
        }
      end
    end
  end
end
