module Orb
  module Models
    type event_update_params =
      {
        event_name: String,
        properties: top,
        timestamp: Time,
        customer_id: String?,
        external_customer_id: String?
      }
      & Orb::Internal::Type::request_parameters

    class EventUpdateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor event_name: String

      attr_accessor properties: top

      attr_accessor timestamp: Time

      attr_accessor customer_id: String?

      attr_accessor external_customer_id: String?

      def initialize: (
        event_name: String,
        properties: top,
        timestamp: Time,
        ?customer_id: String?,
        ?external_customer_id: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        event_name: String,
        properties: top,
        timestamp: Time,
        customer_id: String?,
        external_customer_id: String?,
        request_options: Orb::RequestOptions
      }
    end
  end
end
