module Orb
  module Models
    type event_update_response = { amended: String }

    class EventUpdateResponse < Orb::Internal::Type::BaseModel
      attr_accessor amended: String

      def initialize: (amended: String) -> void
    end
  end
end
