module Orb
  module Models
    type event_search_params =
      {
        event_ids: ::Array[String],
        timeframe_end: Time?,
        timeframe_start: Time?
      }
      & Orb::Internal::Type::request_parameters

    class EventSearchParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor event_ids: ::Array[String]

      attr_accessor timeframe_end: Time?

      attr_accessor timeframe_start: Time?

      def initialize: (
        event_ids: ::Array[String],
        ?timeframe_end: Time?,
        ?timeframe_start: Time?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::event_search_params
    end
  end
end
