module Orb
  module Models
    type event_deprecate_params = {  } & Orb::Internal::Type::request_parameters

    class EventDeprecateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::event_deprecate_params
    end
  end
end
