module Orb
  module Models
    type invoice_void_params = {  } & Orb::request_parameters

    class InvoiceVoidParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::invoice_void_params
    end
  end
end
