module Orb
  module Models
    type invoice_issue_summary_params =
      { invoice_id: String, synchronous: bool }
      & Orb::Internal::Type::request_parameters

    class InvoiceIssueSummaryParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor invoice_id: String

      attr_reader synchronous: bool?

      def synchronous=: (bool) -> bool

      def initialize: (
        invoice_id: String,
        ?synchronous: bool,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        invoice_id: String,
        synchronous: bool,
        request_options: Orb::RequestOptions
      }
    end
  end
end
