module Orb
  module Models
    type invoice_issue_params = { synchronous: bool } & Orb::request_parameters

    class InvoiceIssueParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_reader synchronous: bool?

      def synchronous=: (bool) -> bool

      def initialize: (
        ?synchronous: bool,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::invoice_issue_params
    end
  end
end
