module Orb
  module Models
    type invoice_dunning_schedule_reset_webhook_event =
      {
        id: String,
        created_at: Time,
        invoice: Orb::Invoice,
        properties: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties,
        type: Orb::Models::InvoiceDunningScheduleResetWebhookEvent::type_
      }

    class InvoiceDunningScheduleResetWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor invoice: Orb::Invoice

      attr_accessor properties: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties

      attr_accessor type: Orb::Models::InvoiceDunningScheduleResetWebhookEvent::type_

      def initialize: (
        id: String,
        created_at: Time,
        invoice: Orb::Invoice,
        properties: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties,
        type: Orb::Models::InvoiceDunningScheduleResetWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        invoice: Orb::Invoice,
        properties: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties,
        type: Orb::Models::InvoiceDunningScheduleResetWebhookEvent::type_
      }

      type properties =
        {
          dunning_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::DunningSchedule,
          previous_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::PreviousSchedule
        }

      class Properties < Orb::Internal::Type::BaseModel
        attr_accessor dunning_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::DunningSchedule

        attr_accessor previous_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::PreviousSchedule

        def initialize: (
          dunning_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::DunningSchedule,
          previous_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::PreviousSchedule
        ) -> void

        def to_hash: -> {
          dunning_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::DunningSchedule,
          previous_schedule: Orb::InvoiceDunningScheduleResetWebhookEvent::Properties::PreviousSchedule
        }

        type dunning_schedule =
          {
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          }

        class DunningSchedule < Orb::Internal::Type::BaseModel
          attr_accessor completion_time: Time?

          attr_accessor created_at: Time?

          attr_accessor invoice_id: String

          attr_accessor modified_at: Time?

          attr_accessor start_time: Time?

          attr_accessor status: String?

          def initialize: (
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          ) -> void

          def to_hash: -> {
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          }
        end

        type previous_schedule =
          {
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          }

        class PreviousSchedule < Orb::Internal::Type::BaseModel
          attr_accessor completion_time: Time?

          attr_accessor created_at: Time?

          attr_accessor invoice_id: String

          attr_accessor modified_at: Time?

          attr_accessor start_time: Time?

          attr_accessor status: String?

          def initialize: (
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          ) -> void

          def to_hash: -> {
            completion_time: Time?,
            created_at: Time?,
            invoice_id: String,
            modified_at: Time?,
            start_time: Time?,
            status: String?
          }
        end
      end

      type type_ = :"invoice.dunning_schedule_reset"

      module Type
        extend Orb::Internal::Type::Enum

        INVOICE_DUNNING_SCHEDULE_RESET: :"invoice.dunning_schedule_reset"

        def self?.values: -> ::Array[Orb::Models::InvoiceDunningScheduleResetWebhookEvent::type_]
      end
    end
  end
end
