module Orb
  module Models
    type invoice_issue_params =
      { synchronous: bool } & Orb::Internal::Type::request_parameters

    class InvoiceIssueParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_reader synchronous: bool?

      def synchronous=: (bool) -> bool

      def initialize: (
        ?synchronous: bool,
        ?request_options: Orb::request_opts
      ) -> void
    end
  end
end
