module Orb
  module Models
    type invoice_level_discount_model =
      Orb::Models::PercentageDiscount
      | Orb::Models::AmountDiscount
      | Orb::Models::TrialDiscount

    class InvoiceLevelDiscountModel < Orb::Union
      private def self.variants: -> [[:percentage, Orb::Models::PercentageDiscount], [:amount, Orb::Models::AmountDiscount], [:trial, Orb::Models::TrialDiscount]]
    end
  end
end
