module Orb
  module Models
    type invoice_level_discount =
      Orb::Models::PercentageDiscount
      | Orb::Models::AmountDiscount
      | Orb::Models::TrialDiscount

    module InvoiceLevelDiscount
      extend Orb::Internal::Type::Union

      def self?.variants: -> [Orb::Models::PercentageDiscount, Orb::Models::AmountDiscount, Orb::Models::TrialDiscount]
    end
  end
end
