module Orb
  module Models
    type invoice_due_date_recalculation_completed_webhook_event =
      {
        id: String,
        created_at: Time,
        properties: Orb::InvoiceDueDateRecalculationCompletedWebhookEvent::Properties,
        type: Orb::Models::InvoiceDueDateRecalculationCompletedWebhookEvent::type_
      }

    class InvoiceDueDateRecalculationCompletedWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor properties: Orb::InvoiceDueDateRecalculationCompletedWebhookEvent::Properties

      attr_accessor type: Orb::Models::InvoiceDueDateRecalculationCompletedWebhookEvent::type_

      def initialize: (
        id: String,
        created_at: Time,
        properties: Orb::InvoiceDueDateRecalculationCompletedWebhookEvent::Properties,
        type: Orb::Models::InvoiceDueDateRecalculationCompletedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        properties: Orb::InvoiceDueDateRecalculationCompletedWebhookEvent::Properties,
        type: Orb::Models::InvoiceDueDateRecalculationCompletedWebhookEvent::type_
      }

      type properties = { completed_at: Time, started_at: Time }

      class Properties < Orb::Internal::Type::BaseModel
        attr_accessor completed_at: Time

        attr_accessor started_at: Time

        def initialize: (completed_at: Time, started_at: Time) -> void

        def to_hash: -> { completed_at: Time, started_at: Time }
      end

      type type_ = :"invoice_due_date_recalculation.completed"

      module Type
        extend Orb::Internal::Type::Enum

        INVOICE_DUE_DATE_RECALCULATION_COMPLETED: :"invoice_due_date_recalculation.completed"

        def self?.values: -> ::Array[Orb::Models::InvoiceDueDateRecalculationCompletedWebhookEvent::type_]
      end
    end
  end
end
