module Orb
  module Models
    type invoice_delete_line_item_params =
      { invoice_id: String, line_item_id: String }
      & Orb::Internal::Type::request_parameters

    class InvoiceDeleteLineItemParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor invoice_id: String

      attr_accessor line_item_id: String

      def initialize: (
        invoice_id: String,
        line_item_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        invoice_id: String,
        line_item_id: String,
        request_options: Orb::RequestOptions
      }
    end
  end
end
