module Orb
  module Models
    type invoice_level_discount =
      Orb::PercentageDiscount
      | Orb::AmountDiscount
      | Orb::TrialDiscount
      | Orb::InvoiceLevelDiscount::TieredPercentage

    module InvoiceLevelDiscount
      extend Orb::Internal::Type::Union

      type tiered_percentage =
        {
          discount_type: :tiered_percentage,
          tiers: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Tier],
          applies_to_price_ids: ::Array[String]?,
          filters: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Filter]?,
          reason: String?
        }

      class TieredPercentage < Orb::Internal::Type::BaseModel
        attr_accessor discount_type: :tiered_percentage

        attr_accessor tiers: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Tier]

        attr_accessor applies_to_price_ids: ::Array[String]?

        attr_accessor filters: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Filter]?

        attr_accessor reason: String?

        def initialize: (
          tiers: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Tier],
          ?applies_to_price_ids: ::Array[String]?,
          ?filters: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Filter]?,
          ?reason: String?,
          ?discount_type: :tiered_percentage
        ) -> void

        def to_hash: -> {
          discount_type: :tiered_percentage,
          tiers: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Tier],
          applies_to_price_ids: ::Array[String]?,
          filters: ::Array[Orb::InvoiceLevelDiscount::TieredPercentage::Filter]?,
          reason: String?
        }

        type tier =
          { lower_bound: Float, percentage: Float, upper_bound: Float? }

        class Tier < Orb::Internal::Type::BaseModel
          attr_accessor lower_bound: Float

          attr_accessor percentage: Float

          attr_accessor upper_bound: Float?

          def initialize: (
            lower_bound: Float,
            percentage: Float,
            ?upper_bound: Float?
          ) -> void

          def to_hash: -> {
            lower_bound: Float,
            percentage: Float,
            upper_bound: Float?
          }
        end

        type filter =
          {
            field: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::field,
            operator: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::operator,
            values: ::Array[String]
          }

        class Filter < Orb::Internal::Type::BaseModel
          attr_accessor field: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::field

          attr_accessor operator: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::operator

          attr_accessor values: ::Array[String]

          def initialize: (
            field: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::field,
            operator: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::operator,
            values: ::Array[String]
          ) -> void

          def to_hash: -> {
            field: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::field,
            operator: Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::operator,
            values: ::Array[String]
          }

          type field =
            :price_id | :item_id | :price_type | :currency | :pricing_unit_id

          module Field
            extend Orb::Internal::Type::Enum

            PRICE_ID: :price_id
            ITEM_ID: :item_id
            PRICE_TYPE: :price_type
            CURRENCY: :currency
            PRICING_UNIT_ID: :pricing_unit_id

            def self?.values: -> ::Array[Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::field]
          end

          type operator = :includes | :excludes

          module Operator
            extend Orb::Internal::Type::Enum

            INCLUDES: :includes
            EXCLUDES: :excludes

            def self?.values: -> ::Array[Orb::Models::InvoiceLevelDiscount::TieredPercentage::Filter::operator]
          end
        end
      end

      def self?.variants: -> ::Array[Orb::Models::invoice_level_discount]
    end
  end
end
