module Orb
  module Models
    type invoice_pay_params = {  } & Orb::Internal::Type::request_parameters

    class InvoicePayParams < Orb::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::invoice_pay_params
    end
  end
end
