module Orb
  module Models
    type invoice_pay_params = {  } & Orb::request_parameters

    class InvoicePayParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::invoice_pay_params | Orb::BaseModel data) -> void

      def to_h: -> Orb::Models::invoice_pay_params
    end
  end
end
