module Orb
  module Models
    type invoice_mark_paid_params =
      { payment_received_date: Date, external_id: String?, notes: String? }
      & Orb::Internal::Type::request_parameters

    class InvoiceMarkPaidParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor payment_received_date: Date

      attr_accessor external_id: String?

      attr_accessor notes: String?

      def initialize: (
        payment_received_date: Date,
        ?external_id: String?,
        ?notes: String?,
        ?request_options: Orb::request_opts
      ) -> void
    end
  end
end
