module Orb
  module Models
    type invoice_mark_paid_params =
      { payment_received_date: Date, external_id: String?, notes: String? }
      & Orb::request_parameters

    class InvoiceMarkPaidParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor payment_received_date: Date

      attr_accessor external_id: String?

      attr_accessor notes: String?

      def initialize:
        (
          payment_received_date: Date,
          external_id: String?,
          notes: String?,
          request_options: Orb::request_opts
        ) -> void
        | (?Orb::Models::invoice_mark_paid_params | Orb::BaseModel data) -> void

      def to_h: -> Orb::Models::invoice_mark_paid_params
    end
  end
end
