module Orb
  module Models
    type item_fetch_params =
      { item_id: String } & Orb::Internal::Type::request_parameters

    class ItemFetchParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor item_id: String

      def initialize: (
        item_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> { item_id: String, request_options: Orb::RequestOptions }
    end
  end
end
