module Orb
  module Models
    type item_slim_model = { id: String, name: String }

    class ItemSlimModel < Orb::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      def initialize:
        (id: String, name: String) -> void
        | (?Orb::Models::item_slim_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::item_slim_model
    end
  end
end
