module Orb
  module Models
    type item_update_params =
      {
        external_connections: ::Array[Orb::Models::ItemExternalConnectionModel]?,
        name: String?
      }
      & Orb::request_parameters

    class ItemUpdateParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor external_connections: ::Array[Orb::Models::ItemExternalConnectionModel]?

      attr_accessor name: String?

      def initialize:
        (
          external_connections: ::Array[Orb::Models::ItemExternalConnectionModel]?,
          name: String?,
          request_options: Orb::request_opts
        ) -> void
        | (?Orb::Models::item_update_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::item_update_params
    end
  end
end
