module Orb
  module Models
    type item_update_params =
      {
        external_connections: ::Array[Orb::ItemUpdateParams::ExternalConnection]?,
        name: String?
      }
      & Orb::Internal::Type::request_parameters

    class ItemUpdateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor external_connections: ::Array[Orb::ItemUpdateParams::ExternalConnection]?

      attr_accessor name: String?

      def initialize: (
        ?external_connections: ::Array[Orb::ItemUpdateParams::ExternalConnection]?,
        ?name: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        external_connections: ::Array[Orb::ItemUpdateParams::ExternalConnection]?,
        name: String?,
        request_options: Orb::RequestOptions
      }

      type external_connection =
        {
          external_connection_name: Orb::Models::ItemUpdateParams::ExternalConnection::external_connection_name,
          external_entity_id: String
        }

      class ExternalConnection < Orb::Internal::Type::BaseModel
        attr_accessor external_connection_name: Orb::Models::ItemUpdateParams::ExternalConnection::external_connection_name

        attr_accessor external_entity_id: String

        def initialize: (
          external_connection_name: Orb::Models::ItemUpdateParams::ExternalConnection::external_connection_name,
          external_entity_id: String
        ) -> void

        def to_hash: -> {
          external_connection_name: Orb::Models::ItemUpdateParams::ExternalConnection::external_connection_name,
          external_entity_id: String
        }

        type external_connection_name =
          :stripe
          | :quickbooks
          | :"bill.com"
          | :netsuite
          | :taxjar
          | :avalara
          | :anrok

        module ExternalConnectionName
          extend Orb::Internal::Type::Enum

          STRIPE: :stripe
          QUICKBOOKS: :quickbooks
          BILL_COM: :"bill.com"
          NETSUITE: :netsuite
          TAXJAR: :taxjar
          AVALARA: :avalara
          ANROK: :anrok

          def self?.values: -> ::Array[Orb::Models::ItemUpdateParams::ExternalConnection::external_connection_name]
        end
      end
    end
  end
end
