module Orb
  module Models
    type item_external_connection_model =
      {
        external_connection_name: Orb::Models::ItemExternalConnectionModel::external_connection_name,
        external_entity_id: String
      }

    class ItemExternalConnectionModel < Orb::BaseModel
      attr_accessor external_connection_name: Orb::Models::ItemExternalConnectionModel::external_connection_name

      attr_accessor external_entity_id: String

      def initialize:
        (
          external_connection_name: Orb::Models::ItemExternalConnectionModel::external_connection_name,
          external_entity_id: String
        ) -> void
        | (
          ?Orb::Models::item_external_connection_model | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::item_external_connection_model

      type external_connection_name =
        :stripe
        | :quickbooks
        | :"bill.com"
        | :netsuite
        | :taxjar
        | :avalara
        | :anrok

      class ExternalConnectionName < Orb::Enum
        STRIPE: :stripe
        QUICKBOOKS: :quickbooks
        BILL_COM: :"bill.com"
        NETSUITE: :netsuite
        TAXJAR: :taxjar
        AVALARA: :avalara
        ANROK: :anrok

        def self.values: -> ::Array[Orb::Models::ItemExternalConnectionModel::external_connection_name]
      end
    end
  end
end
