module Orb
  module Models
    type item_fetch_params = {  } & Orb::request_parameters

    class ItemFetchParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::item_fetch_params
    end
  end
end
