module Orb
  module Models
    type license_retrieve_by_external_id_params =
      {
        external_license_id: String,
        license_type_id: String,
        subscription_id: String
      }
      & Orb::Internal::Type::request_parameters

    class LicenseRetrieveByExternalIDParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor external_license_id: String

      attr_accessor license_type_id: String

      attr_accessor subscription_id: String

      def initialize: (
        external_license_id: String,
        license_type_id: String,
        subscription_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        external_license_id: String,
        license_type_id: String,
        subscription_id: String,
        request_options: Orb::RequestOptions
      }
    end
  end
end
