module Orb
  module Models
    type matrix_with_allocation_config_model =
      {
        allocation: Float,
        default_unit_amount: String,
        dimensions: ::Array[String?],
        matrix_values: ::Array[Orb::Models::MatrixValueModel]
      }

    class MatrixWithAllocationConfigModel < Orb::BaseModel
      attr_accessor allocation: Float

      attr_accessor default_unit_amount: String

      attr_accessor dimensions: ::Array[String?]

      attr_accessor matrix_values: ::Array[Orb::Models::MatrixValueModel]

      def initialize:
        (
          allocation: Float,
          default_unit_amount: String,
          dimensions: ::Array[String?],
          matrix_values: ::Array[Orb::Models::MatrixValueModel]
        ) -> void
        | (
          ?Orb::Models::matrix_with_allocation_config_model
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::matrix_with_allocation_config_model
    end
  end
end
