module Orb
  module Models
    type metric_fetch_params =
      { metric_id: String } & Orb::Internal::Type::request_parameters

    class MetricFetchParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor metric_id: String

      def initialize: (
        metric_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        metric_id: String,
        request_options: Orb::RequestOptions
      }
    end
  end
end
