module Orb
  module Models
    type metric_update_params =
      { metadata: ::Hash[Symbol, String?]? }
      & Orb::Internal::Type::request_parameters

    class MetricUpdateParams < Orb::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::metric_update_params
    end
  end
end
