module Orb
  module Models
    type metric_create_params =
      {
        description: String?,
        item_id: String,
        name: String,
        sql: String,
        metadata: ::Hash[Symbol, String?]?
      }
      & Orb::Internal::Type::request_parameters

    class MetricCreateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor description: String?

      attr_accessor item_id: String

      attr_accessor name: String

      attr_accessor sql: String

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        description: String?,
        item_id: String,
        name: String,
        sql: String,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::metric_create_params
    end
  end
end
