module Orb
  module Models
    type monetary_usage_discount_adjustment =
      {
        id: String,
        adjustment_type: Orb::Models::MonetaryUsageDiscountAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        reason: String?,
        replaces_adjustment_id: String?,
        usage_discount: Float
      }

    class MonetaryUsageDiscountAdjustment < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor adjustment_type: Orb::Models::MonetaryUsageDiscountAdjustment::adjustment_type

      attr_accessor amount: String

      attr_accessor applies_to_price_ids: ::Array[String]

      attr_accessor filters: ::Array[Orb::TransformPriceFilter]

      attr_accessor is_invoice_level: bool

      attr_accessor reason: String?

      attr_accessor replaces_adjustment_id: String?

      attr_accessor usage_discount: Float

      def initialize: (
        id: String,
        adjustment_type: Orb::Models::MonetaryUsageDiscountAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        reason: String?,
        replaces_adjustment_id: String?,
        usage_discount: Float
      ) -> void

      def to_hash: -> {
        id: String,
        adjustment_type: Orb::Models::MonetaryUsageDiscountAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        reason: String?,
        replaces_adjustment_id: String?,
        usage_discount: Float
      }

      type adjustment_type = :usage_discount

      module AdjustmentType
        extend Orb::Internal::Type::Enum

        USAGE_DISCOUNT: :usage_discount

        def self?.values: -> ::Array[Orb::Models::MonetaryUsageDiscountAdjustment::adjustment_type]
      end
    end
  end
end
