module Orb
  module Models
    type monetary_maximum_adjustment =
      {
        id: String,
        adjustment_type: Orb::Models::MonetaryMaximumAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        maximum_amount: String,
        reason: String?,
        replaces_adjustment_id: String?
      }

    class MonetaryMaximumAdjustment < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor adjustment_type: Orb::Models::MonetaryMaximumAdjustment::adjustment_type

      attr_accessor amount: String

      attr_accessor applies_to_price_ids: ::Array[String]

      attr_accessor filters: ::Array[Orb::TransformPriceFilter]

      attr_accessor is_invoice_level: bool

      attr_accessor maximum_amount: String

      attr_accessor reason: String?

      attr_accessor replaces_adjustment_id: String?

      def initialize: (
        id: String,
        adjustment_type: Orb::Models::MonetaryMaximumAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        maximum_amount: String,
        reason: String?,
        replaces_adjustment_id: String?
      ) -> void

      def to_hash: -> {
        id: String,
        adjustment_type: Orb::Models::MonetaryMaximumAdjustment::adjustment_type,
        amount: String,
        applies_to_price_ids: ::Array[String],
        filters: ::Array[Orb::TransformPriceFilter],
        is_invoice_level: bool,
        maximum_amount: String,
        reason: String?,
        replaces_adjustment_id: String?
      }

      type adjustment_type = :maximum

      module AdjustmentType
        extend Orb::Internal::Type::Enum

        MAXIMUM: :maximum

        def self?.values: -> ::Array[Orb::Models::MonetaryMaximumAdjustment::adjustment_type]
      end
    end
  end
end
