module Orb
  module Models
    type new_subscription_scalable_matrix_with_tiered_pricing_price =
      {
        cadence: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::model_type,
        name: String,
        scalable_matrix_with_tiered_pricing_config: Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::conversion_rate_config?,
        currency: String?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        license_type_id: String?,
        metadata: ::Hash[Symbol, String?]?,
        reference_id: String?
      }

    class NewSubscriptionScalableMatrixWithTieredPricingPrice < Orb::Internal::Type::BaseModel
      attr_accessor cadence: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::cadence

      attr_accessor item_id: String

      attr_accessor model_type: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::model_type

      attr_accessor name: String

      attr_accessor scalable_matrix_with_tiered_pricing_config: Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig

      attr_accessor billable_metric_id: String?

      attr_accessor billed_in_advance: bool?

      attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor conversion_rate: Float?

      attr_accessor conversion_rate_config: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::conversion_rate_config?

      attr_accessor currency: String?

      attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

      attr_accessor external_price_id: String?

      attr_accessor fixed_price_quantity: Float?

      attr_accessor invoice_grouping_key: String?

      attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor license_type_id: String?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      attr_accessor reference_id: String?

      def initialize: (
        cadence: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::model_type,
        name: String,
        scalable_matrix_with_tiered_pricing_config: Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig,
        ?billable_metric_id: String?,
        ?billed_in_advance: bool?,
        ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?conversion_rate: Float?,
        ?conversion_rate_config: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::conversion_rate_config?,
        ?currency: String?,
        ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        ?external_price_id: String?,
        ?fixed_price_quantity: Float?,
        ?invoice_grouping_key: String?,
        ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?license_type_id: String?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?reference_id: String?
      ) -> void

      def to_hash: -> {
        cadence: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::model_type,
        name: String,
        scalable_matrix_with_tiered_pricing_config: Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::conversion_rate_config?,
        currency: String?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        license_type_id: String?,
        metadata: ::Hash[Symbol, String?]?,
        reference_id: String?
      }

      type cadence =
        :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

      module Cadence
        extend Orb::Internal::Type::Enum

        ANNUAL: :annual
        SEMI_ANNUAL: :semi_annual
        MONTHLY: :monthly
        QUARTERLY: :quarterly
        ONE_TIME: :one_time
        CUSTOM: :custom

        def self?.values: -> ::Array[Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::cadence]
      end

      type model_type = :scalable_matrix_with_tiered_pricing

      module ModelType
        extend Orb::Internal::Type::Enum

        SCALABLE_MATRIX_WITH_TIERED_PRICING: :scalable_matrix_with_tiered_pricing

        def self?.values: -> ::Array[Orb::Models::NewSubscriptionScalableMatrixWithTieredPricingPrice::model_type]
      end

      type scalable_matrix_with_tiered_pricing_config =
        {
          first_dimension: String,
          matrix_scaling_factors: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::MatrixScalingFactor],
          tiers: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::Tier],
          second_dimension: String?
        }

      class ScalableMatrixWithTieredPricingConfig < Orb::Internal::Type::BaseModel
        attr_accessor first_dimension: String

        attr_accessor matrix_scaling_factors: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::MatrixScalingFactor]

        attr_accessor tiers: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::Tier]

        attr_accessor second_dimension: String?

        def initialize: (
          first_dimension: String,
          matrix_scaling_factors: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::MatrixScalingFactor],
          tiers: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::Tier],
          ?second_dimension: String?
        ) -> void

        def to_hash: -> {
          first_dimension: String,
          matrix_scaling_factors: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::MatrixScalingFactor],
          tiers: ::Array[Orb::NewSubscriptionScalableMatrixWithTieredPricingPrice::ScalableMatrixWithTieredPricingConfig::Tier],
          second_dimension: String?
        }

        type matrix_scaling_factor =
          {
            first_dimension_value: String,
            scaling_factor: String,
            second_dimension_value: String?
          }

        class MatrixScalingFactor < Orb::Internal::Type::BaseModel
          attr_accessor first_dimension_value: String

          attr_accessor scaling_factor: String

          attr_accessor second_dimension_value: String?

          def initialize: (
            first_dimension_value: String,
            scaling_factor: String,
            ?second_dimension_value: String?
          ) -> void

          def to_hash: -> {
            first_dimension_value: String,
            scaling_factor: String,
            second_dimension_value: String?
          }
        end

        type tier = { tier_lower_bound: String, unit_amount: String }

        class Tier < Orb::Internal::Type::BaseModel
          attr_accessor tier_lower_bound: String

          attr_accessor unit_amount: String

          def initialize: (
            tier_lower_bound: String,
            unit_amount: String
          ) -> void

          def to_hash: -> { tier_lower_bound: String, unit_amount: String }
        end
      end
    end
  end
end
