module Orb
  module Models
    type new_floating_max_group_tiered_package_price =
      {
        cadence: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::cadence,
        currency: String,
        item_id: String,
        max_group_tiered_package_config: ::Hash[Symbol, top],
        model_type: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::model_type,
        name: String,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?
      }

    class NewFloatingMaxGroupTieredPackagePrice < Orb::Internal::Type::BaseModel
      attr_accessor cadence: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::cadence

      attr_accessor currency: String

      attr_accessor item_id: String

      attr_accessor max_group_tiered_package_config: ::Hash[Symbol, top]

      attr_accessor model_type: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::model_type

      attr_accessor name: String

      attr_accessor billable_metric_id: String?

      attr_accessor billed_in_advance: bool?

      attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor conversion_rate: Float?

      attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

      attr_accessor external_price_id: String?

      attr_accessor fixed_price_quantity: Float?

      attr_accessor invoice_grouping_key: String?

      attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        cadence: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::cadence,
        currency: String,
        item_id: String,
        max_group_tiered_package_config: ::Hash[Symbol, top],
        model_type: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::model_type,
        name: String,
        ?billable_metric_id: String?,
        ?billed_in_advance: bool?,
        ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?conversion_rate: Float?,
        ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        ?external_price_id: String?,
        ?fixed_price_quantity: Float?,
        ?invoice_grouping_key: String?,
        ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?metadata: ::Hash[Symbol, String?]?
      ) -> void

      def to_hash: -> {
        cadence: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::cadence,
        currency: String,
        item_id: String,
        max_group_tiered_package_config: ::Hash[Symbol, top],
        model_type: Orb::Models::NewFloatingMaxGroupTieredPackagePrice::model_type,
        name: String,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?
      }

      type cadence =
        :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

      module Cadence
        extend Orb::Internal::Type::Enum

        ANNUAL: :annual
        SEMI_ANNUAL: :semi_annual
        MONTHLY: :monthly
        QUARTERLY: :quarterly
        ONE_TIME: :one_time
        CUSTOM: :custom

        def self?.values: -> ::Array[Orb::Models::NewFloatingMaxGroupTieredPackagePrice::cadence]
      end

      type model_type = :max_group_tiered_package

      module ModelType
        extend Orb::Internal::Type::Enum

        MAX_GROUP_TIERED_PACKAGE: :max_group_tiered_package

        def self?.values: -> ::Array[Orb::Models::NewFloatingMaxGroupTieredPackagePrice::model_type]
      end
    end
  end
end
