module Orb
  module Models
    type new_plan_package_with_allocation_price =
      {
        cadence: Orb::Models::NewPlanPackageWithAllocationPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewPlanPackageWithAllocationPrice::model_type,
        name: String,
        package_with_allocation_config: ::Hash[Symbol, top],
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::NewPlanPackageWithAllocationPrice::conversion_rate_config?,
        currency: String?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?,
        reference_id: String?
      }

    class NewPlanPackageWithAllocationPrice < Orb::Internal::Type::BaseModel
      attr_accessor cadence: Orb::Models::NewPlanPackageWithAllocationPrice::cadence

      attr_accessor item_id: String

      attr_accessor model_type: Orb::Models::NewPlanPackageWithAllocationPrice::model_type

      attr_accessor name: String

      attr_accessor package_with_allocation_config: ::Hash[Symbol, top]

      attr_accessor billable_metric_id: String?

      attr_accessor billed_in_advance: bool?

      attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor conversion_rate: Float?

      attr_accessor conversion_rate_config: Orb::Models::NewPlanPackageWithAllocationPrice::conversion_rate_config?

      attr_accessor currency: String?

      attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

      attr_accessor external_price_id: String?

      attr_accessor fixed_price_quantity: Float?

      attr_accessor invoice_grouping_key: String?

      attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      attr_accessor reference_id: String?

      def initialize: (
        cadence: Orb::Models::NewPlanPackageWithAllocationPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewPlanPackageWithAllocationPrice::model_type,
        name: String,
        package_with_allocation_config: ::Hash[Symbol, top],
        ?billable_metric_id: String?,
        ?billed_in_advance: bool?,
        ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?conversion_rate: Float?,
        ?conversion_rate_config: Orb::Models::NewPlanPackageWithAllocationPrice::conversion_rate_config?,
        ?currency: String?,
        ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        ?external_price_id: String?,
        ?fixed_price_quantity: Float?,
        ?invoice_grouping_key: String?,
        ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?reference_id: String?
      ) -> void

      def to_hash: -> {
        cadence: Orb::Models::NewPlanPackageWithAllocationPrice::cadence,
        item_id: String,
        model_type: Orb::Models::NewPlanPackageWithAllocationPrice::model_type,
        name: String,
        package_with_allocation_config: ::Hash[Symbol, top],
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::NewPlanPackageWithAllocationPrice::conversion_rate_config?,
        currency: String?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?,
        reference_id: String?
      }

      type cadence =
        :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

      module Cadence
        extend Orb::Internal::Type::Enum

        ANNUAL: :annual
        SEMI_ANNUAL: :semi_annual
        MONTHLY: :monthly
        QUARTERLY: :quarterly
        ONE_TIME: :one_time
        CUSTOM: :custom

        def self?.values: -> ::Array[Orb::Models::NewPlanPackageWithAllocationPrice::cadence]
      end

      type model_type = :package_with_allocation

      module ModelType
        extend Orb::Internal::Type::Enum

        PACKAGE_WITH_ALLOCATION: :package_with_allocation

        def self?.values: -> ::Array[Orb::Models::NewPlanPackageWithAllocationPrice::model_type]
      end

      type conversion_rate_config =
        Orb::UnitConversionRateConfig | Orb::TieredConversionRateConfig

      module ConversionRateConfig
        extend Orb::Internal::Type::Union

        def self?.variants: -> ::Array[Orb::Models::NewPlanPackageWithAllocationPrice::conversion_rate_config]
      end
    end
  end
end
