module Orb
  module Models
    type new_allocation_price =
      {
        amount: String,
        cadence: Orb::Models::NewAllocationPrice::cadence,
        currency: String,
        custom_expiration: Orb::CustomExpiration?,
        expires_at_end_of_cadence: bool?,
        filters: ::Array[Orb::NewAllocationPrice::Filter]?,
        item_id: String?,
        per_unit_cost_basis: String
      }

    class NewAllocationPrice < Orb::Internal::Type::BaseModel
      attr_accessor amount: String

      attr_accessor cadence: Orb::Models::NewAllocationPrice::cadence

      attr_accessor currency: String

      attr_accessor custom_expiration: Orb::CustomExpiration?

      attr_accessor expires_at_end_of_cadence: bool?

      attr_accessor filters: ::Array[Orb::NewAllocationPrice::Filter]?

      attr_accessor item_id: String?

      attr_reader per_unit_cost_basis: String?

      def per_unit_cost_basis=: (String) -> String

      def initialize: (
        amount: String,
        cadence: Orb::Models::NewAllocationPrice::cadence,
        currency: String,
        ?custom_expiration: Orb::CustomExpiration?,
        ?expires_at_end_of_cadence: bool?,
        ?filters: ::Array[Orb::NewAllocationPrice::Filter]?,
        ?item_id: String?,
        ?per_unit_cost_basis: String
      ) -> void

      def to_hash: -> {
        amount: String,
        cadence: Orb::Models::NewAllocationPrice::cadence,
        currency: String,
        custom_expiration: Orb::CustomExpiration?,
        expires_at_end_of_cadence: bool?,
        filters: ::Array[Orb::NewAllocationPrice::Filter]?,
        item_id: String?,
        per_unit_cost_basis: String
      }

      type cadence = :one_time | :monthly | :quarterly | :semi_annual | :annual

      module Cadence
        extend Orb::Internal::Type::Enum

        ONE_TIME: :one_time
        MONTHLY: :monthly
        QUARTERLY: :quarterly
        SEMI_ANNUAL: :semi_annual
        ANNUAL: :annual

        def self?.values: -> ::Array[Orb::Models::NewAllocationPrice::cadence]
      end

      type filter =
        {
          field: Orb::Models::NewAllocationPrice::Filter::field,
          operator: Orb::Models::NewAllocationPrice::Filter::operator,
          values: ::Array[String]
        }

      class Filter < Orb::Internal::Type::BaseModel
        attr_accessor field: Orb::Models::NewAllocationPrice::Filter::field

        attr_accessor operator: Orb::Models::NewAllocationPrice::Filter::operator

        attr_accessor values: ::Array[String]

        def initialize: (
          field: Orb::Models::NewAllocationPrice::Filter::field,
          operator: Orb::Models::NewAllocationPrice::Filter::operator,
          values: ::Array[String]
        ) -> void

        def to_hash: -> {
          field: Orb::Models::NewAllocationPrice::Filter::field,
          operator: Orb::Models::NewAllocationPrice::Filter::operator,
          values: ::Array[String]
        }

        type field = :item_id

        module Field
          extend Orb::Internal::Type::Enum

          ITEM_ID: :item_id

          def self?.values: -> ::Array[Orb::Models::NewAllocationPrice::Filter::field]
        end

        type operator = :includes | :excludes

        module Operator
          extend Orb::Internal::Type::Enum

          INCLUDES: :includes
          EXCLUDES: :excludes

          def self?.values: -> ::Array[Orb::Models::NewAllocationPrice::Filter::operator]
        end
      end
    end
  end
end
