module Orb
  module Models
    type package_config_model =
      { package_amount: String, package_size: Integer }

    class PackageConfigModel < Orb::BaseModel
      attr_accessor package_amount: String

      attr_accessor package_size: Integer

      def initialize:
        (package_amount: String, package_size: Integer) -> void
        | (?Orb::Models::package_config_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::package_config_model
    end
  end
end
