module Orb
  module Models
    type pagination_metadata = { has_more: bool, next_cursor: String? }

    class PaginationMetadata < Orb::Internal::Type::BaseModel
      attr_accessor has_more: bool

      attr_accessor next_cursor: String?

      def initialize: (has_more: bool, next_cursor: String?) -> void

      def to_hash: -> Orb::Models::pagination_metadata
    end
  end
end
