module Orb
  module Models
    type percentage_discount =
      {
        applies_to_price_ids: ::Array[String],
        discount_type: Orb::Models::PercentageDiscount::discount_type,
        percentage_discount: Float,
        reason: String?
      }

    class PercentageDiscount < Orb::BaseModel
      attr_accessor applies_to_price_ids: ::Array[String]

      attr_accessor discount_type: Orb::Models::PercentageDiscount::discount_type

      attr_accessor percentage_discount: Float

      attr_accessor reason: String?

      def initialize:
        (
          applies_to_price_ids: ::Array[String],
          discount_type: Orb::Models::PercentageDiscount::discount_type,
          percentage_discount: Float,
          reason: String?
        ) -> void
        | (?Orb::Models::percentage_discount | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::percentage_discount

      type discount_type = :percentage

      class DiscountType < Orb::Enum
        PERCENTAGE: :percentage

        def self.values: -> ::Array[Orb::Models::PercentageDiscount::discount_type]
      end
    end
  end
end
