module Orb
  module Models
    type plan_minified_model =
      { id: String?, external_plan_id: String?, name: String? }

    class PlanMinifiedModel < Orb::BaseModel
      attr_accessor id: String?

      attr_accessor external_plan_id: String?

      attr_accessor name: String?

      def initialize:
        (id: String?, external_plan_id: String?, name: String?) -> void
        | (?Orb::Models::plan_minified_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::plan_minified_model
    end
  end
end
