module Orb
  module Models
    type plan_update_params = {  } & Orb::request_parameters

    class PlanUpdateParams < Orb::Models::EditPlanModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::plan_update_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::plan_update_params
    end
  end
end
