module Orb
  module Models
    type price_evaluate_response =
      { data: ::Array[Orb::Models::EvaluatePriceGroup] }

    class PriceEvaluateResponse < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::Models::EvaluatePriceGroup]

      def initialize: (data: ::Array[Orb::Models::EvaluatePriceGroup]) -> void

      def to_hash: -> Orb::Models::price_evaluate_response
    end
  end
end
