module Orb
  module Models
    type price_create_params =
      { body: Orb::Models::PriceCreateParams::body }
      & Orb::Internal::Type::request_parameters

    class PriceCreateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor body: Orb::Models::PriceCreateParams::body

      def initialize: (
        body: Orb::Models::PriceCreateParams::body,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        body: Orb::Models::PriceCreateParams::body,
        request_options: Orb::RequestOptions
      }

      type body =
        Orb::NewFloatingUnitPrice
        | Orb::NewFloatingTieredPrice
        | Orb::NewFloatingBulkPrice
        | Orb::PriceCreateParams::Body::BulkWithFilters
        | Orb::NewFloatingPackagePrice
        | Orb::NewFloatingMatrixPrice
        | Orb::NewFloatingThresholdTotalAmountPrice
        | Orb::NewFloatingTieredPackagePrice
        | Orb::NewFloatingTieredWithMinimumPrice
        | Orb::NewFloatingGroupedTieredPrice
        | Orb::NewFloatingTieredPackageWithMinimumPrice
        | Orb::NewFloatingPackageWithAllocationPrice
        | Orb::NewFloatingUnitWithPercentPrice
        | Orb::NewFloatingMatrixWithAllocationPrice
        | Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts
        | Orb::NewFloatingTieredWithProrationPrice
        | Orb::NewFloatingUnitWithProrationPrice
        | Orb::NewFloatingGroupedAllocationPrice
        | Orb::NewFloatingBulkWithProrationPrice
        | Orb::NewFloatingGroupedWithProratedMinimumPrice
        | Orb::NewFloatingGroupedWithMeteredMinimumPrice
        | Orb::PriceCreateParams::Body::GroupedWithMinMaxThresholds
        | Orb::NewFloatingMatrixWithDisplayNamePrice
        | Orb::NewFloatingGroupedTieredPackagePrice
        | Orb::NewFloatingMaxGroupTieredPackagePrice
        | Orb::NewFloatingScalableMatrixWithUnitPricingPrice
        | Orb::NewFloatingScalableMatrixWithTieredPricingPrice
        | Orb::NewFloatingCumulativeGroupedBulkPrice
        | Orb::PriceCreateParams::Body::CumulativeGroupedAllocation
        | Orb::PriceCreateParams::Body::DailyCreditAllowance
        | Orb::PriceCreateParams::Body::MeteredAllowance
        | Orb::NewFloatingMinimumCompositePrice
        | Orb::PriceCreateParams::Body::Percent
        | Orb::PriceCreateParams::Body::EventOutput

      module Body
        extend Orb::Internal::Type::Union

        type bulk_with_filters =
          {
            bulk_with_filters_config: Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig,
            cadence: Orb::Models::PriceCreateParams::Body::BulkWithFilters::cadence,
            currency: String,
            item_id: String,
            model_type: :bulk_with_filters,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class BulkWithFilters < Orb::Internal::Type::BaseModel
          attr_accessor bulk_with_filters_config: Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig

          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::BulkWithFilters::cadence

          attr_accessor currency: String

          attr_accessor item_id: String

          attr_accessor model_type: :bulk_with_filters

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            bulk_with_filters_config: Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig,
            cadence: Orb::Models::PriceCreateParams::Body::BulkWithFilters::cadence,
            currency: String,
            item_id: String,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :bulk_with_filters
          ) -> void

          def to_hash: -> {
            bulk_with_filters_config: Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig,
            cadence: Orb::Models::PriceCreateParams::Body::BulkWithFilters::cadence,
            currency: String,
            item_id: String,
            model_type: :bulk_with_filters,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type bulk_with_filters_config =
            {
              filters: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Filter],
              tiers: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Tier]
            }

          class BulkWithFiltersConfig < Orb::Internal::Type::BaseModel
            attr_accessor filters: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Filter]

            attr_accessor tiers: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Tier]

            def initialize: (
              filters: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Filter],
              tiers: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Tier]
            ) -> void

            def to_hash: -> {
              filters: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Filter],
              tiers: ::Array[Orb::PriceCreateParams::Body::BulkWithFilters::BulkWithFiltersConfig::Tier]
            }

            type filter = { property_key: String, property_value: String }

            class Filter < Orb::Internal::Type::BaseModel
              attr_accessor property_key: String

              attr_accessor property_value: String

              def initialize: (
                property_key: String,
                property_value: String
              ) -> void

              def to_hash: -> { property_key: String, property_value: String }
            end

            type tier = { unit_amount: String, tier_lower_bound: String? }

            class Tier < Orb::Internal::Type::BaseModel
              attr_accessor unit_amount: String

              attr_accessor tier_lower_bound: String?

              def initialize: (
                unit_amount: String,
                ?tier_lower_bound: String?
              ) -> void

              def to_hash: -> { unit_amount: String, tier_lower_bound: String? }
            end
          end

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::BulkWithFilters::cadence]
          end
        end

        type matrix_with_threshold_discounts =
          {
            cadence: Orb::Models::PriceCreateParams::Body::MatrixWithThresholdDiscounts::cadence,
            currency: String,
            item_id: String,
            matrix_with_threshold_discounts_config: Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig,
            model_type: :matrix_with_threshold_discounts,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class MatrixWithThresholdDiscounts < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::MatrixWithThresholdDiscounts::cadence

          attr_accessor currency: String

          attr_accessor item_id: String

          attr_accessor matrix_with_threshold_discounts_config: Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig

          attr_accessor model_type: :matrix_with_threshold_discounts

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::MatrixWithThresholdDiscounts::cadence,
            currency: String,
            item_id: String,
            matrix_with_threshold_discounts_config: Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :matrix_with_threshold_discounts
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::MatrixWithThresholdDiscounts::cadence,
            currency: String,
            item_id: String,
            matrix_with_threshold_discounts_config: Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig,
            model_type: :matrix_with_threshold_discounts,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::MatrixWithThresholdDiscounts::cadence]
          end

          type matrix_with_threshold_discounts_config =
            {
              default_unit_amount: String,
              first_dimension: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::MatrixValue],
              second_dimension: String?,
              threshold_discount_groups: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]
            }

          class MatrixWithThresholdDiscountsConfig < Orb::Internal::Type::BaseModel
            attr_accessor default_unit_amount: String

            attr_accessor first_dimension: String

            attr_accessor matrix_values: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::MatrixValue]

            attr_accessor second_dimension: String?

            attr_reader threshold_discount_groups: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]?

            def threshold_discount_groups=: (
              ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]
            ) -> ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]

            def initialize: (
              default_unit_amount: String,
              first_dimension: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::MatrixValue],
              ?second_dimension: String?,
              ?threshold_discount_groups: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]
            ) -> void

            def to_hash: -> {
              default_unit_amount: String,
              first_dimension: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::MatrixValue],
              second_dimension: String?,
              threshold_discount_groups: ::Array[Orb::PriceCreateParams::Body::MatrixWithThresholdDiscounts::MatrixWithThresholdDiscountsConfig::ThresholdDiscountGroup]
            }

            type matrix_value =
              {
                first_dimension_value: String,
                unit_amount: String,
                second_dimension_value: String?
              }

            class MatrixValue < Orb::Internal::Type::BaseModel
              attr_accessor first_dimension_value: String

              attr_accessor unit_amount: String

              attr_accessor second_dimension_value: String?

              def initialize: (
                first_dimension_value: String,
                unit_amount: String,
                ?second_dimension_value: String?
              ) -> void

              def to_hash: -> {
                first_dimension_value: String,
                unit_amount: String,
                second_dimension_value: String?
              }
            end

            type threshold_discount_group =
              {
                above_threshold_discount_percentage: String,
                below_threshold_discount_percentage: String,
                cell_coordinates: String,
                threshold_amount: String,
                description: String?
              }

            class ThresholdDiscountGroup < Orb::Internal::Type::BaseModel
              attr_accessor above_threshold_discount_percentage: String

              attr_accessor below_threshold_discount_percentage: String

              attr_accessor cell_coordinates: String

              attr_accessor threshold_amount: String

              attr_accessor description: String?

              def initialize: (
                above_threshold_discount_percentage: String,
                below_threshold_discount_percentage: String,
                cell_coordinates: String,
                threshold_amount: String,
                ?description: String?
              ) -> void

              def to_hash: -> {
                above_threshold_discount_percentage: String,
                below_threshold_discount_percentage: String,
                cell_coordinates: String,
                threshold_amount: String,
                description: String?
              }
            end
          end
        end

        type grouped_with_min_max_thresholds =
          {
            cadence: Orb::Models::PriceCreateParams::Body::GroupedWithMinMaxThresholds::cadence,
            currency: String,
            grouped_with_min_max_thresholds_config: Orb::PriceCreateParams::Body::GroupedWithMinMaxThresholds::GroupedWithMinMaxThresholdsConfig,
            item_id: String,
            model_type: :grouped_with_min_max_thresholds,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class GroupedWithMinMaxThresholds < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::GroupedWithMinMaxThresholds::cadence

          attr_accessor currency: String

          attr_accessor grouped_with_min_max_thresholds_config: Orb::PriceCreateParams::Body::GroupedWithMinMaxThresholds::GroupedWithMinMaxThresholdsConfig

          attr_accessor item_id: String

          attr_accessor model_type: :grouped_with_min_max_thresholds

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::GroupedWithMinMaxThresholds::cadence,
            currency: String,
            grouped_with_min_max_thresholds_config: Orb::PriceCreateParams::Body::GroupedWithMinMaxThresholds::GroupedWithMinMaxThresholdsConfig,
            item_id: String,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :grouped_with_min_max_thresholds
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::GroupedWithMinMaxThresholds::cadence,
            currency: String,
            grouped_with_min_max_thresholds_config: Orb::PriceCreateParams::Body::GroupedWithMinMaxThresholds::GroupedWithMinMaxThresholdsConfig,
            item_id: String,
            model_type: :grouped_with_min_max_thresholds,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::GroupedWithMinMaxThresholds::cadence]
          end

          type grouped_with_min_max_thresholds_config =
            {
              grouping_key: String,
              maximum_charge: String,
              minimum_charge: String,
              per_unit_rate: String
            }

          class GroupedWithMinMaxThresholdsConfig < Orb::Internal::Type::BaseModel
            attr_accessor grouping_key: String

            attr_accessor maximum_charge: String

            attr_accessor minimum_charge: String

            attr_accessor per_unit_rate: String

            def initialize: (
              grouping_key: String,
              maximum_charge: String,
              minimum_charge: String,
              per_unit_rate: String
            ) -> void

            def to_hash: -> {
              grouping_key: String,
              maximum_charge: String,
              minimum_charge: String,
              per_unit_rate: String
            }
          end
        end

        type cumulative_grouped_allocation =
          {
            cadence: Orb::Models::PriceCreateParams::Body::CumulativeGroupedAllocation::cadence,
            cumulative_grouped_allocation_config: Orb::PriceCreateParams::Body::CumulativeGroupedAllocation::CumulativeGroupedAllocationConfig,
            currency: String,
            item_id: String,
            model_type: :cumulative_grouped_allocation,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class CumulativeGroupedAllocation < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::CumulativeGroupedAllocation::cadence

          attr_accessor cumulative_grouped_allocation_config: Orb::PriceCreateParams::Body::CumulativeGroupedAllocation::CumulativeGroupedAllocationConfig

          attr_accessor currency: String

          attr_accessor item_id: String

          attr_accessor model_type: :cumulative_grouped_allocation

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::CumulativeGroupedAllocation::cadence,
            cumulative_grouped_allocation_config: Orb::PriceCreateParams::Body::CumulativeGroupedAllocation::CumulativeGroupedAllocationConfig,
            currency: String,
            item_id: String,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :cumulative_grouped_allocation
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::CumulativeGroupedAllocation::cadence,
            cumulative_grouped_allocation_config: Orb::PriceCreateParams::Body::CumulativeGroupedAllocation::CumulativeGroupedAllocationConfig,
            currency: String,
            item_id: String,
            model_type: :cumulative_grouped_allocation,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::CumulativeGroupedAllocation::cadence]
          end

          type cumulative_grouped_allocation_config =
            {
              cumulative_allocation: String,
              group_allocation: String,
              grouping_key: String,
              unit_amount: String
            }

          class CumulativeGroupedAllocationConfig < Orb::Internal::Type::BaseModel
            attr_accessor cumulative_allocation: String

            attr_accessor group_allocation: String

            attr_accessor grouping_key: String

            attr_accessor unit_amount: String

            def initialize: (
              cumulative_allocation: String,
              group_allocation: String,
              grouping_key: String,
              unit_amount: String
            ) -> void

            def to_hash: -> {
              cumulative_allocation: String,
              group_allocation: String,
              grouping_key: String,
              unit_amount: String
            }
          end
        end

        type daily_credit_allowance =
          {
            cadence: Orb::Models::PriceCreateParams::Body::DailyCreditAllowance::cadence,
            currency: String,
            daily_credit_allowance_config: Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig,
            item_id: String,
            model_type: :daily_credit_allowance,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class DailyCreditAllowance < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::DailyCreditAllowance::cadence

          attr_accessor currency: String

          attr_accessor daily_credit_allowance_config: Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig

          attr_accessor item_id: String

          attr_accessor model_type: :daily_credit_allowance

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::DailyCreditAllowance::cadence,
            currency: String,
            daily_credit_allowance_config: Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig,
            item_id: String,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :daily_credit_allowance
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::DailyCreditAllowance::cadence,
            currency: String,
            daily_credit_allowance_config: Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig,
            item_id: String,
            model_type: :daily_credit_allowance,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::DailyCreditAllowance::cadence]
          end

          type daily_credit_allowance_config =
            {
              daily_allowance: String,
              default_unit_amount: String,
              dimensions: ::Array[String?],
              event_day_property: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig::MatrixValue]
            }

          class DailyCreditAllowanceConfig < Orb::Internal::Type::BaseModel
            attr_accessor daily_allowance: String

            attr_accessor default_unit_amount: String

            attr_accessor dimensions: ::Array[String?]

            attr_accessor event_day_property: String

            attr_accessor matrix_values: ::Array[Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig::MatrixValue]

            def initialize: (
              daily_allowance: String,
              default_unit_amount: String,
              dimensions: ::Array[String?],
              event_day_property: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig::MatrixValue]
            ) -> void

            def to_hash: -> {
              daily_allowance: String,
              default_unit_amount: String,
              dimensions: ::Array[String?],
              event_day_property: String,
              matrix_values: ::Array[Orb::PriceCreateParams::Body::DailyCreditAllowance::DailyCreditAllowanceConfig::MatrixValue]
            }

            type matrix_value =
              { dimension_values: ::Array[String?], unit_amount: String }

            class MatrixValue < Orb::Internal::Type::BaseModel
              attr_accessor dimension_values: ::Array[String?]

              attr_accessor unit_amount: String

              def initialize: (
                dimension_values: ::Array[String?],
                unit_amount: String
              ) -> void

              def to_hash: -> {
                dimension_values: ::Array[String?],
                unit_amount: String
              }
            end
          end
        end

        type metered_allowance =
          {
            cadence: Orb::Models::PriceCreateParams::Body::MeteredAllowance::cadence,
            currency: String,
            item_id: String,
            metered_allowance_config: Orb::PriceCreateParams::Body::MeteredAllowance::MeteredAllowanceConfig,
            model_type: :metered_allowance,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class MeteredAllowance < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::MeteredAllowance::cadence

          attr_accessor currency: String

          attr_accessor item_id: String

          attr_accessor metered_allowance_config: Orb::PriceCreateParams::Body::MeteredAllowance::MeteredAllowanceConfig

          attr_accessor model_type: :metered_allowance

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::MeteredAllowance::cadence,
            currency: String,
            item_id: String,
            metered_allowance_config: Orb::PriceCreateParams::Body::MeteredAllowance::MeteredAllowanceConfig,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :metered_allowance
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::MeteredAllowance::cadence,
            currency: String,
            item_id: String,
            metered_allowance_config: Orb::PriceCreateParams::Body::MeteredAllowance::MeteredAllowanceConfig,
            model_type: :metered_allowance,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::MeteredAllowance::cadence]
          end

          type metered_allowance_config =
            {
              allowance_grouping_value: String,
              consumption_grouping_value: String,
              grouping_key: String,
              unit_amount: String,
              allowance_display_name: String,
              consumption_display_name: String
            }

          class MeteredAllowanceConfig < Orb::Internal::Type::BaseModel
            attr_accessor allowance_grouping_value: String

            attr_accessor consumption_grouping_value: String

            attr_accessor grouping_key: String

            attr_accessor unit_amount: String

            attr_reader allowance_display_name: String?

            def allowance_display_name=: (String) -> String

            attr_reader consumption_display_name: String?

            def consumption_display_name=: (String) -> String

            def initialize: (
              allowance_grouping_value: String,
              consumption_grouping_value: String,
              grouping_key: String,
              unit_amount: String,
              ?allowance_display_name: String,
              ?consumption_display_name: String
            ) -> void

            def to_hash: -> {
              allowance_grouping_value: String,
              consumption_grouping_value: String,
              grouping_key: String,
              unit_amount: String,
              allowance_display_name: String,
              consumption_display_name: String
            }
          end
        end

        type percent =
          {
            cadence: Orb::Models::PriceCreateParams::Body::Percent::cadence,
            currency: String,
            item_id: String,
            model_type: :percent,
            name: String,
            percent_config: Orb::PriceCreateParams::Body::Percent::PercentConfig,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class Percent < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::Percent::cadence

          attr_accessor currency: String

          attr_accessor item_id: String

          attr_accessor model_type: :percent

          attr_accessor name: String

          attr_accessor percent_config: Orb::PriceCreateParams::Body::Percent::PercentConfig

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::Percent::cadence,
            currency: String,
            item_id: String,
            name: String,
            percent_config: Orb::PriceCreateParams::Body::Percent::PercentConfig,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :percent
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::Percent::cadence,
            currency: String,
            item_id: String,
            model_type: :percent,
            name: String,
            percent_config: Orb::PriceCreateParams::Body::Percent::PercentConfig,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::Percent::cadence]
          end

          type percent_config =
            {
              percent: Float,
              maximum_amount: String?,
              minimum_amount: String?,
              prorated: bool
            }

          class PercentConfig < Orb::Internal::Type::BaseModel
            attr_accessor percent: Float

            attr_accessor maximum_amount: String?

            attr_accessor minimum_amount: String?

            attr_reader prorated: bool?

            def prorated=: (bool) -> bool

            def initialize: (
              percent: Float,
              ?maximum_amount: String?,
              ?minimum_amount: String?,
              ?prorated: bool
            ) -> void

            def to_hash: -> {
              percent: Float,
              maximum_amount: String?,
              minimum_amount: String?,
              prorated: bool
            }
          end
        end

        type event_output =
          {
            cadence: Orb::Models::PriceCreateParams::Body::EventOutput::cadence,
            currency: String,
            event_output_config: Orb::PriceCreateParams::Body::EventOutput::EventOutputConfig,
            item_id: String,
            model_type: :event_output,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

        class EventOutput < Orb::Internal::Type::BaseModel
          attr_accessor cadence: Orb::Models::PriceCreateParams::Body::EventOutput::cadence

          attr_accessor currency: String

          attr_accessor event_output_config: Orb::PriceCreateParams::Body::EventOutput::EventOutputConfig

          attr_accessor item_id: String

          attr_accessor model_type: :event_output

          attr_accessor name: String

          attr_accessor billable_metric_id: String?

          attr_accessor billed_in_advance: bool?

          attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor conversion_rate: Float?

          attr_accessor conversion_rate_config: Orb::Models::conversion_rate_config?

          attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

          attr_accessor external_price_id: String?

          attr_accessor fixed_price_quantity: Float?

          attr_accessor invoice_grouping_key: String?

          attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

          attr_accessor license_type_id: String?

          attr_accessor metadata: ::Hash[Symbol, String?]?

          def initialize: (
            cadence: Orb::Models::PriceCreateParams::Body::EventOutput::cadence,
            currency: String,
            event_output_config: Orb::PriceCreateParams::Body::EventOutput::EventOutputConfig,
            item_id: String,
            name: String,
            ?billable_metric_id: String?,
            ?billed_in_advance: bool?,
            ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?conversion_rate: Float?,
            ?conversion_rate_config: Orb::Models::conversion_rate_config?,
            ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            ?external_price_id: String?,
            ?fixed_price_quantity: Float?,
            ?invoice_grouping_key: String?,
            ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            ?license_type_id: String?,
            ?metadata: ::Hash[Symbol, String?]?,
            ?model_type: :event_output
          ) -> void

          def to_hash: -> {
            cadence: Orb::Models::PriceCreateParams::Body::EventOutput::cadence,
            currency: String,
            event_output_config: Orb::PriceCreateParams::Body::EventOutput::EventOutputConfig,
            item_id: String,
            model_type: :event_output,
            name: String,
            billable_metric_id: String?,
            billed_in_advance: bool?,
            billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            conversion_rate: Float?,
            conversion_rate_config: Orb::Models::conversion_rate_config?,
            dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
            external_price_id: String?,
            fixed_price_quantity: Float?,
            invoice_grouping_key: String?,
            invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
            license_type_id: String?,
            metadata: ::Hash[Symbol, String?]?
          }

          type cadence =
            :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

          module Cadence
            extend Orb::Internal::Type::Enum

            ANNUAL: :annual
            SEMI_ANNUAL: :semi_annual
            MONTHLY: :monthly
            QUARTERLY: :quarterly
            ONE_TIME: :one_time
            CUSTOM: :custom

            def self?.values: -> ::Array[Orb::Models::PriceCreateParams::Body::EventOutput::cadence]
          end

          type event_output_config =
            {
              unit_rating_key: String,
              default_unit_rate: String?,
              grouping_key: String?
            }

          class EventOutputConfig < Orb::Internal::Type::BaseModel
            attr_accessor unit_rating_key: String

            attr_accessor default_unit_rate: String?

            attr_accessor grouping_key: String?

            def initialize: (
              unit_rating_key: String,
              ?default_unit_rate: String?,
              ?grouping_key: String?
            ) -> void

            def to_hash: -> {
              unit_rating_key: String,
              default_unit_rate: String?,
              grouping_key: String?
            }
          end
        end

        def self?.variants: -> ::Array[Orb::Models::PriceCreateParams::body]
      end
    end
  end
end
