module Orb
  module Models
    type price_update_params = {  } & Orb::request_parameters

    class PriceUpdateParams < Orb::Models::UpdatePriceRequestParams
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::price_update_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::price_update_params
    end
  end
end
