module Orb
  module Models
    type price_update_params =
      { price_id: String, metadata: ::Hash[Symbol, String?]? }
      & Orb::Internal::Type::request_parameters

    class PriceUpdateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor price_id: String

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        price_id: String,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        price_id: String,
        metadata: ::Hash[Symbol, String?]?,
        request_options: Orb::RequestOptions
      }
    end
  end
end
