module Orb
  module Models
    type price_create_params =
      { new_floating_price_model: Orb::Models::new_floating_price_model }
      & Orb::request_parameters

    class PriceCreateParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor new_floating_price_model: Orb::Models::new_floating_price_model

      def initialize:
        (
          new_floating_price_model: Orb::Models::new_floating_price_model,
          request_options: Orb::request_opts
        ) -> void
        | (?Orb::Models::price_create_params | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::price_create_params
    end
  end
end
