module Orb
  module Models
    type price_fetch_params = {  } & Orb::request_parameters

    class PriceFetchParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize:
        (request_options: Orb::request_opts) -> void
        | (?Orb::Models::price_fetch_params | Orb::BaseModel data) -> void

      def to_h: -> Orb::Models::price_fetch_params
    end
  end
end
