module Orb
  module Models
    type price_create_params =
      {
        cadence: Orb::Models::PriceCreateParams::cadence,
        currency: String,
        item_id: String,
        model_type: Orb::Models::PriceCreateParams::model_type,
        name: String,
        unit_config: Orb::UnitConfig,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::PriceCreateParams::conversion_rate_config?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?,
        package_config: Orb::PackageConfig,
        matrix_config: Orb::MatrixConfig,
        matrix_with_allocation_config: Orb::MatrixWithAllocationConfig,
        tiered_config: Orb::TieredConfig,
        tiered_bps_config: Orb::TieredBPSConfig,
        bps_config: Orb::BPSConfig,
        bulk_bps_config: Orb::BulkBPSConfig,
        bulk_config: Orb::BulkConfig,
        threshold_total_amount_config: ::Hash[Symbol, top],
        tiered_package_config: ::Hash[Symbol, top],
        grouped_tiered_config: ::Hash[Symbol, top],
        max_group_tiered_package_config: ::Hash[Symbol, top],
        tiered_with_minimum_config: ::Hash[Symbol, top],
        package_with_allocation_config: ::Hash[Symbol, top],
        tiered_package_with_minimum_config: ::Hash[Symbol, top],
        unit_with_percent_config: ::Hash[Symbol, top],
        tiered_with_proration_config: ::Hash[Symbol, top],
        unit_with_proration_config: ::Hash[Symbol, top],
        grouped_allocation_config: ::Hash[Symbol, top],
        grouped_with_prorated_minimum_config: ::Hash[Symbol, top],
        grouped_with_metered_minimum_config: ::Hash[Symbol, top],
        matrix_with_display_name_config: ::Hash[Symbol, top],
        bulk_with_proration_config: ::Hash[Symbol, top],
        grouped_tiered_package_config: ::Hash[Symbol, top],
        scalable_matrix_with_unit_pricing_config: ::Hash[Symbol, top],
        scalable_matrix_with_tiered_pricing_config: ::Hash[Symbol, top],
        cumulative_grouped_bulk_config: ::Hash[Symbol, top]
      }
      & Orb::Internal::Type::request_parameters

    class PriceCreateParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor cadence: Orb::Models::PriceCreateParams::cadence

      attr_accessor currency: String

      attr_accessor item_id: String

      attr_accessor model_type: Orb::Models::PriceCreateParams::model_type

      attr_accessor name: String

      attr_accessor unit_config: Orb::UnitConfig

      attr_accessor billable_metric_id: String?

      attr_accessor billed_in_advance: bool?

      attr_accessor billing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor conversion_rate: Float?

      attr_accessor conversion_rate_config: Orb::Models::PriceCreateParams::conversion_rate_config?

      attr_accessor dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?

      attr_accessor external_price_id: String?

      attr_accessor fixed_price_quantity: Float?

      attr_accessor invoice_grouping_key: String?

      attr_accessor invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?

      attr_accessor metadata: ::Hash[Symbol, String?]?

      attr_accessor package_config: Orb::PackageConfig

      attr_accessor matrix_config: Orb::MatrixConfig

      attr_accessor matrix_with_allocation_config: Orb::MatrixWithAllocationConfig

      attr_accessor tiered_config: Orb::TieredConfig

      attr_accessor tiered_bps_config: Orb::TieredBPSConfig

      attr_accessor bps_config: Orb::BPSConfig

      attr_accessor bulk_bps_config: Orb::BulkBPSConfig

      attr_accessor bulk_config: Orb::BulkConfig

      attr_accessor threshold_total_amount_config: ::Hash[Symbol, top]

      attr_accessor tiered_package_config: ::Hash[Symbol, top]

      attr_accessor grouped_tiered_config: ::Hash[Symbol, top]

      attr_accessor max_group_tiered_package_config: ::Hash[Symbol, top]

      attr_accessor tiered_with_minimum_config: ::Hash[Symbol, top]

      attr_accessor package_with_allocation_config: ::Hash[Symbol, top]

      attr_accessor tiered_package_with_minimum_config: ::Hash[Symbol, top]

      attr_accessor unit_with_percent_config: ::Hash[Symbol, top]

      attr_accessor tiered_with_proration_config: ::Hash[Symbol, top]

      attr_accessor unit_with_proration_config: ::Hash[Symbol, top]

      attr_accessor grouped_allocation_config: ::Hash[Symbol, top]

      attr_accessor grouped_with_prorated_minimum_config: ::Hash[Symbol, top]

      attr_accessor grouped_with_metered_minimum_config: ::Hash[Symbol, top]

      attr_accessor matrix_with_display_name_config: ::Hash[Symbol, top]

      attr_accessor bulk_with_proration_config: ::Hash[Symbol, top]

      attr_accessor grouped_tiered_package_config: ::Hash[Symbol, top]

      attr_accessor scalable_matrix_with_unit_pricing_config: ::Hash[Symbol, top]

      attr_accessor scalable_matrix_with_tiered_pricing_config: ::Hash[Symbol, top]

      attr_accessor cumulative_grouped_bulk_config: ::Hash[Symbol, top]

      def initialize: (
        cadence: Orb::Models::PriceCreateParams::cadence,
        currency: String,
        item_id: String,
        model_type: Orb::Models::PriceCreateParams::model_type,
        name: String,
        unit_config: Orb::UnitConfig,
        package_config: Orb::PackageConfig,
        matrix_config: Orb::MatrixConfig,
        matrix_with_allocation_config: Orb::MatrixWithAllocationConfig,
        tiered_config: Orb::TieredConfig,
        tiered_bps_config: Orb::TieredBPSConfig,
        bps_config: Orb::BPSConfig,
        bulk_bps_config: Orb::BulkBPSConfig,
        bulk_config: Orb::BulkConfig,
        threshold_total_amount_config: ::Hash[Symbol, top],
        tiered_package_config: ::Hash[Symbol, top],
        grouped_tiered_config: ::Hash[Symbol, top],
        max_group_tiered_package_config: ::Hash[Symbol, top],
        tiered_with_minimum_config: ::Hash[Symbol, top],
        package_with_allocation_config: ::Hash[Symbol, top],
        tiered_package_with_minimum_config: ::Hash[Symbol, top],
        unit_with_percent_config: ::Hash[Symbol, top],
        tiered_with_proration_config: ::Hash[Symbol, top],
        unit_with_proration_config: ::Hash[Symbol, top],
        grouped_allocation_config: ::Hash[Symbol, top],
        grouped_with_prorated_minimum_config: ::Hash[Symbol, top],
        grouped_with_metered_minimum_config: ::Hash[Symbol, top],
        matrix_with_display_name_config: ::Hash[Symbol, top],
        bulk_with_proration_config: ::Hash[Symbol, top],
        grouped_tiered_package_config: ::Hash[Symbol, top],
        scalable_matrix_with_unit_pricing_config: ::Hash[Symbol, top],
        scalable_matrix_with_tiered_pricing_config: ::Hash[Symbol, top],
        cumulative_grouped_bulk_config: ::Hash[Symbol, top],
        ?billable_metric_id: String?,
        ?billed_in_advance: bool?,
        ?billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?conversion_rate: Float?,
        ?conversion_rate_config: Orb::Models::PriceCreateParams::conversion_rate_config?,
        ?dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        ?external_price_id: String?,
        ?fixed_price_quantity: Float?,
        ?invoice_grouping_key: String?,
        ?invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        cadence: Orb::Models::PriceCreateParams::cadence,
        currency: String,
        item_id: String,
        model_type: Orb::Models::PriceCreateParams::model_type,
        name: String,
        unit_config: Orb::UnitConfig,
        billable_metric_id: String?,
        billed_in_advance: bool?,
        billing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        conversion_rate: Float?,
        conversion_rate_config: Orb::Models::PriceCreateParams::conversion_rate_config?,
        dimensional_price_configuration: Orb::NewDimensionalPriceConfiguration?,
        external_price_id: String?,
        fixed_price_quantity: Float?,
        invoice_grouping_key: String?,
        invoicing_cycle_configuration: Orb::NewBillingCycleConfiguration?,
        metadata: ::Hash[Symbol, String?]?,
        package_config: Orb::PackageConfig,
        matrix_config: Orb::MatrixConfig,
        matrix_with_allocation_config: Orb::MatrixWithAllocationConfig,
        tiered_config: Orb::TieredConfig,
        tiered_bps_config: Orb::TieredBPSConfig,
        bps_config: Orb::BPSConfig,
        bulk_bps_config: Orb::BulkBPSConfig,
        bulk_config: Orb::BulkConfig,
        threshold_total_amount_config: ::Hash[Symbol, top],
        tiered_package_config: ::Hash[Symbol, top],
        grouped_tiered_config: ::Hash[Symbol, top],
        max_group_tiered_package_config: ::Hash[Symbol, top],
        tiered_with_minimum_config: ::Hash[Symbol, top],
        package_with_allocation_config: ::Hash[Symbol, top],
        tiered_package_with_minimum_config: ::Hash[Symbol, top],
        unit_with_percent_config: ::Hash[Symbol, top],
        tiered_with_proration_config: ::Hash[Symbol, top],
        unit_with_proration_config: ::Hash[Symbol, top],
        grouped_allocation_config: ::Hash[Symbol, top],
        grouped_with_prorated_minimum_config: ::Hash[Symbol, top],
        grouped_with_metered_minimum_config: ::Hash[Symbol, top],
        matrix_with_display_name_config: ::Hash[Symbol, top],
        bulk_with_proration_config: ::Hash[Symbol, top],
        grouped_tiered_package_config: ::Hash[Symbol, top],
        scalable_matrix_with_unit_pricing_config: ::Hash[Symbol, top],
        scalable_matrix_with_tiered_pricing_config: ::Hash[Symbol, top],
        cumulative_grouped_bulk_config: ::Hash[Symbol, top],
        request_options: Orb::RequestOptions
      }

      type cadence =
        :annual | :semi_annual | :monthly | :quarterly | :one_time | :custom

      module Cadence
        extend Orb::Internal::Type::Enum

        ANNUAL: :annual
        SEMI_ANNUAL: :semi_annual
        MONTHLY: :monthly
        QUARTERLY: :quarterly
        ONE_TIME: :one_time
        CUSTOM: :custom

        def self?.values: -> ::Array[Orb::Models::PriceCreateParams::cadence]
      end

      type model_type = :cumulative_grouped_bulk

      module ModelType
        extend Orb::Internal::Type::Enum

        CUMULATIVE_GROUPED_BULK: :cumulative_grouped_bulk

        def self?.values: -> ::Array[Orb::Models::PriceCreateParams::model_type]
      end

      type conversion_rate_config =
        Orb::PriceCreateParams::ConversionRateConfig::Unit
        | Orb::PriceCreateParams::ConversionRateConfig::Tiered

      module ConversionRateConfig
        extend Orb::Internal::Type::Union

        type unit =
          {
            conversion_rate_type: :unit,
            unit_config: Orb::PriceCreateParams::ConversionRateConfig::Unit::UnitConfig
          }

        class Unit < Orb::Internal::Type::BaseModel
          attr_accessor conversion_rate_type: :unit

          attr_accessor unit_config: Orb::PriceCreateParams::ConversionRateConfig::Unit::UnitConfig

          def initialize: (
            unit_config: Orb::PriceCreateParams::ConversionRateConfig::Unit::UnitConfig,
            ?conversion_rate_type: :unit
          ) -> void

          def to_hash: -> {
            conversion_rate_type: :unit,
            unit_config: Orb::PriceCreateParams::ConversionRateConfig::Unit::UnitConfig
          }

          type unit_config = { unit_amount: String }

          class UnitConfig < Orb::Internal::Type::BaseModel
            attr_accessor unit_amount: String

            def initialize: (unit_amount: String) -> void

            def to_hash: -> { unit_amount: String }
          end
        end

        type tiered =
          {
            conversion_rate_type: :tiered,
            tiered_config: Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig
          }

        class Tiered < Orb::Internal::Type::BaseModel
          attr_accessor conversion_rate_type: :tiered

          attr_accessor tiered_config: Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig

          def initialize: (
            tiered_config: Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig,
            ?conversion_rate_type: :tiered
          ) -> void

          def to_hash: -> {
            conversion_rate_type: :tiered,
            tiered_config: Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig
          }

          type tiered_config =
            {
              tiers: ::Array[Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig::Tier]
            }

          class TieredConfig < Orb::Internal::Type::BaseModel
            attr_accessor tiers: ::Array[Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig::Tier]

            def initialize: (
              tiers: ::Array[Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig::Tier]
            ) -> void

            def to_hash: -> {
              tiers: ::Array[Orb::PriceCreateParams::ConversionRateConfig::Tiered::TieredConfig::Tier]
            }

            type tier =
              { first_unit: Float, unit_amount: String, last_unit: Float? }

            class Tier < Orb::Internal::Type::BaseModel
              attr_accessor first_unit: Float

              attr_accessor unit_amount: String

              attr_accessor last_unit: Float?

              def initialize: (
                first_unit: Float,
                unit_amount: String,
                ?last_unit: Float?
              ) -> void

              def to_hash: -> {
                first_unit: Float,
                unit_amount: String,
                last_unit: Float?
              }
            end
          end
        end

        def self?.variants: -> ::Array[Orb::Models::PriceCreateParams::conversion_rate_config]
      end
    end
  end
end
