module Orb
  module Models
    type price_fetch_params = {  } & Orb::Internal::Type::request_parameters

    class PriceFetchParams < Orb::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::price_fetch_params
    end
  end
end
