module Orb
  module Models
    type price_update_params =
      { metadata: ::Hash[Symbol, String?]? } & Orb::request_parameters

    class PriceUpdateParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize: (
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::price_update_params
    end
  end
end
