module Orb
  module Models
    type price_list_params =
      { cursor: String?, limit: Integer }
      & Orb::Internal::Type::request_parameters

    class PriceListParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor cursor: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> void
    end
  end
end
