module Orb
  module Models
    type price_evaluate_response = { data: ::Array[Orb::EvaluatePriceGroup] }

    class PriceEvaluateResponse < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::EvaluatePriceGroup]

      def initialize: (data: ::Array[Orb::EvaluatePriceGroup]) -> void
    end
  end
end
