module Orb
  module Models
    type remove_subscription_adjustment_params = { adjustment_id: String }

    class RemoveSubscriptionAdjustmentParams < Orb::BaseModel
      attr_accessor adjustment_id: String

      def initialize:
        (adjustment_id: String) -> void
        | (
          ?Orb::Models::remove_subscription_adjustment_params
          | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::remove_subscription_adjustment_params
    end
  end
end
