module Orb
  module Models
    type remove_subscription_price_params =
      { external_price_id: String?, price_id: String? }

    class RemoveSubscriptionPriceParams < Orb::BaseModel
      attr_accessor external_price_id: String?

      attr_accessor price_id: String?

      def initialize:
        (external_price_id: String?, price_id: String?) -> void
        | (
          ?Orb::Models::remove_subscription_price_params | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::remove_subscription_price_params
    end
  end
end
