module Orb
  module Models
    type sub_line_item_grouping = { key: String, value: String? }

    class SubLineItemGrouping < Orb::Internal::Type::BaseModel
      attr_accessor key: String

      attr_accessor value: String?

      def initialize: (key: String, value: String?) -> void

      def to_hash: -> { key: String, value: String? }
    end
  end
end
