module Orb
  module Models
    type subscription_unschedule_fixed_fee_quantity_updates_params =
      { price_id: String } & Orb::request_parameters

    class SubscriptionUnscheduleFixedFeeQuantityUpdatesParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor price_id: String

      def initialize: (
        price_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::subscription_unschedule_fixed_fee_quantity_updates_params
    end
  end
end
