module Orb
  module Models
    type subscription_change_cancel_response =
      {
        id: String,
        expiration_time: Time,
        status: Orb::Models::SubscriptionChangeCancelResponse::status,
        subscription: Orb::MutatedSubscription?,
        applied_at: Time?,
        cancelled_at: Time?
      }

    class SubscriptionChangeCancelResponse < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor expiration_time: Time

      attr_accessor status: Orb::Models::SubscriptionChangeCancelResponse::status

      attr_accessor subscription: Orb::MutatedSubscription?

      attr_accessor applied_at: Time?

      attr_accessor cancelled_at: Time?

      def initialize: (
        id: String,
        expiration_time: Time,
        status: Orb::Models::SubscriptionChangeCancelResponse::status,
        subscription: Orb::MutatedSubscription?,
        ?applied_at: Time?,
        ?cancelled_at: Time?
      ) -> void

      def to_hash: -> {
        id: String,
        expiration_time: Time,
        status: Orb::Models::SubscriptionChangeCancelResponse::status,
        subscription: Orb::MutatedSubscription?,
        applied_at: Time?,
        cancelled_at: Time?
      }

      type status = :pending | :applied | :cancelled

      module Status
        extend Orb::Internal::Type::Enum

        PENDING: :pending
        APPLIED: :applied
        CANCELLED: :cancelled

        def self?.values: -> ::Array[Orb::Models::SubscriptionChangeCancelResponse::status]
      end
    end
  end
end
