module Orb
  module Models
    type subscription_created_webhook_event =
      {
        id: String,
        created_at: Time,
        properties: top,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCreatedWebhookEvent::type_
      }

    class SubscriptionCreatedWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor properties: top

      attr_accessor subscription: Orb::Subscription

      attr_accessor type: Orb::Models::SubscriptionCreatedWebhookEvent::type_

      def initialize: (
        id: String,
        created_at: Time,
        properties: top,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCreatedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        properties: top,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCreatedWebhookEvent::type_
      }

      type type_ = :"subscription.created"

      module Type
        extend Orb::Internal::Type::Enum

        SUBSCRIPTION_CREATED: :"subscription.created"

        def self?.values: -> ::Array[Orb::Models::SubscriptionCreatedWebhookEvent::type_]
      end
    end
  end
end
