module Orb
  module Models
    type subscription_change_cancel_params =
      { subscription_change_id: String }
      & Orb::Internal::Type::request_parameters

    class SubscriptionChangeCancelParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor subscription_change_id: String

      def initialize: (
        subscription_change_id: String,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        subscription_change_id: String,
        request_options: Orb::RequestOptions
      }
    end
  end
end
