module Orb
  module Models
    type subscription_trial_info_model = { end_date: Time? }

    class SubscriptionTrialInfoModel < Orb::BaseModel
      attr_accessor end_date: Time?

      def initialize:
        (end_date: Time?) -> void
        | (
          ?Orb::Models::subscription_trial_info_model | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::subscription_trial_info_model
    end
  end
end
