module Orb
  module Models
    type subscription_fetch_costs_response =
      { data: ::Array[Orb::AggregatedCost] }

    class SubscriptionFetchCostsResponse < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::AggregatedCost]

      def initialize: (data: ::Array[Orb::AggregatedCost]) -> void

      def to_hash: -> { data: ::Array[Orb::AggregatedCost] }
    end
  end
end
