module Orb
  module Models
    type subscriptions_api =
      {
        data: ::Array[Orb::Models::Subscription],
        pagination_metadata: Orb::Models::PaginationMetadata
      }

    class SubscriptionsAPI < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::Models::Subscription]

      attr_accessor pagination_metadata: Orb::Models::PaginationMetadata

      def initialize: (
        data: ::Array[Orb::Models::Subscription],
        pagination_metadata: Orb::Models::PaginationMetadata
      ) -> void

      def to_hash: -> Orb::Models::subscriptions_api
    end
  end
end
