module Orb
  module Models
    type subscription_fetch_costs_response =
      { data: ::Array[Orb::Models::AggregatedCostModel] }

    class SubscriptionFetchCostsResponse < Orb::BaseModel
      attr_accessor data: ::Array[Orb::Models::AggregatedCostModel]

      def initialize:
        (data: ::Array[Orb::Models::AggregatedCostModel]) -> void
        | (
          ?Orb::Models::subscription_fetch_costs_response | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::subscription_fetch_costs_response
    end
  end
end
