module Orb
  module Models
    type subscriptions_api =
      {
        data: ::Array[Orb::Subscription],
        pagination_metadata: Orb::PaginationMetadata
      }

    class SubscriptionsAPI < Orb::Internal::Type::BaseModel
      attr_accessor data: ::Array[Orb::Subscription]

      attr_accessor pagination_metadata: Orb::PaginationMetadata

      def initialize: (
        data: ::Array[Orb::Subscription],
        pagination_metadata: Orb::PaginationMetadata
      ) -> void
    end
  end
end
