module Orb
  module Models
    type subscription_unschedule_pending_plan_changes_params =
      {  } & Orb::request_parameters

    class SubscriptionUnschedulePendingPlanChangesParams < Orb::BaseModel
      extend Orb::Type::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::subscription_unschedule_pending_plan_changes_params
    end
  end
end
