module Orb
  module Models
    type subscription_change_minified = { id: String }

    class SubscriptionChangeMinified < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
