module Orb
  module Models
    type subscription_cancellation_scheduled_webhook_event =
      {
        id: String,
        created_at: Time,
        properties: Orb::SubscriptionCancellationScheduledWebhookEvent::Properties,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCancellationScheduledWebhookEvent::type_
      }

    class SubscriptionCancellationScheduledWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor properties: Orb::SubscriptionCancellationScheduledWebhookEvent::Properties

      attr_accessor subscription: Orb::Subscription

      attr_accessor type: Orb::Models::SubscriptionCancellationScheduledWebhookEvent::type_

      def initialize: (
        id: String,
        created_at: Time,
        properties: Orb::SubscriptionCancellationScheduledWebhookEvent::Properties,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCancellationScheduledWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        properties: Orb::SubscriptionCancellationScheduledWebhookEvent::Properties,
        subscription: Orb::Subscription,
        type: Orb::Models::SubscriptionCancellationScheduledWebhookEvent::type_
      }

      type properties = { cancellation_date: String }

      class Properties < Orb::Internal::Type::BaseModel
        attr_accessor cancellation_date: String

        def initialize: (cancellation_date: String) -> void

        def to_hash: -> { cancellation_date: String }
      end

      type type_ = :"subscription.cancellation_scheduled"

      module Type
        extend Orb::Internal::Type::Enum

        SUBSCRIPTION_CANCELLATION_SCHEDULED: :"subscription.cancellation_scheduled"

        def self?.values: -> ::Array[Orb::Models::SubscriptionCancellationScheduledWebhookEvent::type_]
      end
    end
  end
end
