module Orb
  module Models
    type subscription_update_trial_params =
      {
        trial_end_date: Orb::Models::SubscriptionUpdateTrialParams::trial_end_date,
        shift: bool
      }
      & Orb::request_parameters

    class SubscriptionUpdateTrialParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      attr_accessor trial_end_date: Orb::Models::SubscriptionUpdateTrialParams::trial_end_date

      attr_reader shift: bool?

      def shift=: (bool) -> bool

      def initialize: (
        trial_end_date: Orb::Models::SubscriptionUpdateTrialParams::trial_end_date,
        ?shift: bool,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> Orb::Models::subscription_update_trial_params

      type trial_end_date = Time | :immediate

      module TrialEndDate
        extend Orb::Union

        def self?.variants: -> [Time, :immediate]

        IMMEDIATE: :immediate
      end
    end
  end
end
