module Orb
  module Models
    type subscription_change_apply_params =
      {
        description: String?,
        mark_as_paid: bool?,
        previously_collected_amount: String?
      }
      & Orb::Internal::Type::request_parameters

    class SubscriptionChangeApplyParams < Orb::Internal::Type::BaseModel
      extend Orb::Internal::Type::RequestParameters::Converter
      include Orb::Internal::Type::RequestParameters

      attr_accessor description: String?

      attr_accessor mark_as_paid: bool?

      attr_accessor previously_collected_amount: String?

      def initialize: (
        ?description: String?,
        ?mark_as_paid: bool?,
        ?previously_collected_amount: String?,
        ?request_options: Orb::request_opts
      ) -> void

      def to_hash: -> {
        description: String?,
        mark_as_paid: bool?,
        previously_collected_amount: String?,
        request_options: Orb::RequestOptions
      }
    end
  end
end
