module Orb
  module Models
    type tax_amount =
      {
        amount: String,
        tax_rate_description: String,
        tax_rate_percentage: String?
      }

    class TaxAmount < Orb::Internal::Type::BaseModel
      attr_accessor amount: String

      attr_accessor tax_rate_description: String

      attr_accessor tax_rate_percentage: String?

      def initialize: (
        amount: String,
        tax_rate_description: String,
        tax_rate_percentage: String?
      ) -> void

      def to_hash: -> {
        amount: String,
        tax_rate_description: String,
        tax_rate_percentage: String?
      }
    end
  end
end
