module Orb
  module Models
    type top_level_ping_response = { response: String }

    class TopLevelPingResponse < Orb::Internal::Type::BaseModel
      attr_accessor response: String

      def initialize: (response: String) -> void

      def to_hash: -> Orb::Models::top_level_ping_response
    end
  end
end
