module Orb
  module Models
    type top_level_ping_params = {  } & Orb::request_parameters

    class TopLevelPingParams < Orb::BaseModel
      extend Orb::RequestParameters::Converter
      include Orb::RequestParameters

      def initialize: (?request_options: Orb::request_opts) -> void

      def to_hash: -> Orb::Models::top_level_ping_params
    end
  end
end
