module Orb
  module Models
    type transaction_accounting_sync_succeeded_webhook_event =
      {
        id: String,
        accounting_sync_record: Orb::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        properties: Orb::TransactionAccountingSyncSucceededWebhookEvent::Properties,
        transaction: Orb::TransactionAccountingSyncSucceededWebhookEvent::Transaction,
        type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::type_
      }

    class TransactionAccountingSyncSucceededWebhookEvent < Orb::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor accounting_sync_record: Orb::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord

      attr_accessor created_at: Time

      attr_accessor properties: Orb::TransactionAccountingSyncSucceededWebhookEvent::Properties

      attr_accessor transaction: Orb::TransactionAccountingSyncSucceededWebhookEvent::Transaction

      attr_accessor type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::type_

      def initialize: (
        id: String,
        accounting_sync_record: Orb::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        properties: Orb::TransactionAccountingSyncSucceededWebhookEvent::Properties,
        transaction: Orb::TransactionAccountingSyncSucceededWebhookEvent::Transaction,
        type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        accounting_sync_record: Orb::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord,
        created_at: Time,
        properties: Orb::TransactionAccountingSyncSucceededWebhookEvent::Properties,
        transaction: Orb::TransactionAccountingSyncSucceededWebhookEvent::Transaction,
        type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::type_
      }

      type accounting_sync_record =
        {
          id: String,
          customer_id: String,
          record_type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord::record_type,
          error_details: ::Hash[Symbol, top]?,
          provider_customer_id: String?,
          status: String?,
          sync_action: String?,
          transaction_record_id: String?
        }

      class AccountingSyncRecord < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor customer_id: String

        attr_accessor record_type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord::record_type

        attr_accessor error_details: ::Hash[Symbol, top]?

        attr_accessor provider_customer_id: String?

        attr_accessor status: String?

        attr_accessor sync_action: String?

        attr_accessor transaction_record_id: String?

        def initialize: (
          id: String,
          customer_id: String,
          record_type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord::record_type,
          ?error_details: ::Hash[Symbol, top]?,
          ?provider_customer_id: String?,
          ?status: String?,
          ?sync_action: String?,
          ?transaction_record_id: String?
        ) -> void

        def to_hash: -> {
          id: String,
          customer_id: String,
          record_type: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord::record_type,
          error_details: ::Hash[Symbol, top]?,
          provider_customer_id: String?,
          status: String?,
          sync_action: String?,
          transaction_record_id: String?
        }

        type record_type =
          :customer
          | :invoice
          | :transaction
          | :customer_balance_transaction
          | :credit_note
          | :subscription
          | :sales_order
          | :block

        module RecordType
          extend Orb::Internal::Type::Enum

          CUSTOMER: :customer
          INVOICE: :invoice
          TRANSACTION: :transaction
          CUSTOMER_BALANCE_TRANSACTION: :customer_balance_transaction
          CREDIT_NOTE: :credit_note
          SUBSCRIPTION: :subscription
          SALES_ORDER: :sales_order
          BLOCK: :block

          def self?.values: -> ::Array[Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::AccountingSyncRecord::record_type]
        end
      end

      type properties = { connection_type: String }

      class Properties < Orb::Internal::Type::BaseModel
        attr_accessor connection_type: String

        def initialize: (connection_type: String) -> void

        def to_hash: -> { connection_type: String }
      end

      type transaction =
        {
          id: String,
          amount: String,
          created_at: Time,
          payment_provider: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::Transaction::payment_provider?,
          payment_provider_id: String?,
          receipt_pdf: String?,
          succeeded: bool
        }

      class Transaction < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: String

        attr_accessor created_at: Time

        attr_accessor payment_provider: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::Transaction::payment_provider?

        attr_accessor payment_provider_id: String?

        attr_accessor receipt_pdf: String?

        attr_accessor succeeded: bool

        def initialize: (
          id: String,
          amount: String,
          created_at: Time,
          payment_provider: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::Transaction::payment_provider?,
          payment_provider_id: String?,
          receipt_pdf: String?,
          succeeded: bool
        ) -> void

        def to_hash: -> {
          id: String,
          amount: String,
          created_at: Time,
          payment_provider: Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::Transaction::payment_provider?,
          payment_provider_id: String?,
          receipt_pdf: String?,
          succeeded: bool
        }

        type payment_provider = :stripe | :adyen

        module PaymentProvider
          extend Orb::Internal::Type::Enum

          STRIPE: :stripe
          ADYEN: :adyen

          def self?.values: -> ::Array[Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::Transaction::payment_provider]
        end
      end

      type type_ = :"transaction.accounting_sync_succeeded"

      module Type
        extend Orb::Internal::Type::Enum

        TRANSACTION_ACCOUNTING_SYNC_SUCCEEDED: :"transaction.accounting_sync_succeeded"

        def self?.values: -> ::Array[Orb::Models::TransactionAccountingSyncSucceededWebhookEvent::type_]
      end
    end
  end
end
