module Orb
  module Models
    type unit_config = { unit_amount: String, scaling_factor: Float? }

    class UnitConfig < Orb::Internal::Type::BaseModel
      attr_accessor unit_amount: String

      attr_accessor scaling_factor: Float?

      def initialize: (unit_amount: String, ?scaling_factor: Float?) -> void

      def to_hash: -> { unit_amount: String, scaling_factor: Float? }
    end
  end
end
