module Orb
  module Models
    type unit_config_model = { unit_amount: String }

    class UnitConfigModel < Orb::BaseModel
      attr_accessor unit_amount: String

      def initialize:
        (unit_amount: String) -> void
        | (?Orb::Models::unit_config_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::unit_config_model
    end
  end
end
