module Orb
  module Models
    type update_price_request_params = { metadata: ::Hash[Symbol, String?]? }

    class UpdatePriceRequestParams < Orb::BaseModel
      attr_accessor metadata: ::Hash[Symbol, String?]?

      def initialize:
        (metadata: ::Hash[Symbol, String?]?) -> void
        | (
          ?Orb::Models::update_price_request_params | Orb::BaseModel data
        ) -> void

      def to_hash: -> Orb::Models::update_price_request_params
    end
  end
end
