module Orb
  module Models
    type usage_discount =
      {
        applies_to_price_ids: ::Array[String],
        discount_type: Orb::Models::UsageDiscount::discount_type,
        usage_discount: Float,
        reason: String?
      }

    class UsageDiscount < Orb::BaseModel
      attr_accessor applies_to_price_ids: ::Array[String]

      attr_accessor discount_type: Orb::Models::UsageDiscount::discount_type

      attr_accessor usage_discount: Float

      attr_accessor reason: String?

      def initialize:
        (
          applies_to_price_ids: ::Array[String],
          discount_type: Orb::Models::UsageDiscount::discount_type,
          usage_discount: Float,
          reason: String?
        ) -> void
        | (?Orb::Models::usage_discount | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::usage_discount

      type discount_type = :usage

      class DiscountType < Orb::Enum
        USAGE: :usage

        def self.values: -> ::Array[Orb::Models::UsageDiscount::discount_type]
      end
    end
  end
end
