module Orb
  module Models
    type usage_model =
      { quantity: Float, timeframe_end: Time, timeframe_start: Time }

    class UsageModel < Orb::BaseModel
      attr_accessor quantity: Float

      attr_accessor timeframe_end: Time

      attr_accessor timeframe_start: Time

      def initialize:
        (quantity: Float, timeframe_end: Time, timeframe_start: Time) -> void
        | (?Orb::Models::usage_model | Orb::BaseModel data) -> void

      def to_hash: -> Orb::Models::usage_model
    end
  end
end
