module Orb
  module Models
    module Customers
      type balance_transaction_list_response =
        {
          id: String,
          action: Orb::Models::Customers::BalanceTransactionListResponse::action,
          amount: String,
          created_at: Time,
          credit_note: Orb::CreditNoteTiny?,
          description: String?,
          ending_balance: String,
          invoice: Orb::InvoiceTiny?,
          starting_balance: String,
          type: Orb::Models::Customers::BalanceTransactionListResponse::type_
        }

      class BalanceTransactionListResponse < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor action: Orb::Models::Customers::BalanceTransactionListResponse::action

        attr_accessor amount: String

        attr_accessor created_at: Time

        attr_accessor credit_note: Orb::CreditNoteTiny?

        attr_accessor description: String?

        attr_accessor ending_balance: String

        attr_accessor invoice: Orb::InvoiceTiny?

        attr_accessor starting_balance: String

        attr_accessor type: Orb::Models::Customers::BalanceTransactionListResponse::type_

        def initialize: (
          id: String,
          action: Orb::Models::Customers::BalanceTransactionListResponse::action,
          amount: String,
          created_at: Time,
          credit_note: Orb::CreditNoteTiny?,
          description: String?,
          ending_balance: String,
          invoice: Orb::InvoiceTiny?,
          starting_balance: String,
          type: Orb::Models::Customers::BalanceTransactionListResponse::type_
        ) -> void

        def to_hash: -> {
          id: String,
          action: Orb::Models::Customers::BalanceTransactionListResponse::action,
          amount: String,
          created_at: Time,
          credit_note: Orb::CreditNoteTiny?,
          description: String?,
          ending_balance: String,
          invoice: Orb::InvoiceTiny?,
          starting_balance: String,
          type: Orb::Models::Customers::BalanceTransactionListResponse::type_
        }

        type action =
          :applied_to_invoice
          | :manual_adjustment
          | :prorated_refund
          | :revert_prorated_refund
          | :return_from_voiding
          | :credit_note_applied
          | :credit_note_voided
          | :overpayment_refund
          | :external_payment

        module Action
          extend Orb::Internal::Type::Enum

          APPLIED_TO_INVOICE: :applied_to_invoice
          MANUAL_ADJUSTMENT: :manual_adjustment
          PRORATED_REFUND: :prorated_refund
          REVERT_PRORATED_REFUND: :revert_prorated_refund
          RETURN_FROM_VOIDING: :return_from_voiding
          CREDIT_NOTE_APPLIED: :credit_note_applied
          CREDIT_NOTE_VOIDED: :credit_note_voided
          OVERPAYMENT_REFUND: :overpayment_refund
          EXTERNAL_PAYMENT: :external_payment

          def self?.values: -> ::Array[Orb::Models::Customers::BalanceTransactionListResponse::action]
        end

        type type_ = :increment | :decrement

        module Type
          extend Orb::Internal::Type::Enum

          INCREMENT: :increment
          DECREMENT: :decrement

          def self?.values: -> ::Array[Orb::Models::Customers::BalanceTransactionListResponse::type_]
        end
      end
    end
  end
end
