module Orb
  module Models
    module Customers
      type balance_transaction_create_params =
        {
          amount: String,
          type: Orb::Models::Customers::BalanceTransactionCreateParams::type_,
          description: String?
        }
        & Orb::Internal::Type::request_parameters

      class BalanceTransactionCreateParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor amount: String

        attr_accessor type: Orb::Models::Customers::BalanceTransactionCreateParams::type_

        attr_accessor description: String?

        def initialize: (
          amount: String,
          type: Orb::Models::Customers::BalanceTransactionCreateParams::type_,
          ?description: String?,
          ?request_options: Orb::request_opts
        ) -> void

        type type_ = :increment | :decrement

        module Type
          extend Orb::Internal::Type::Enum

          INCREMENT: :increment
          DECREMENT: :decrement

          def self?.values: -> ::Array[Orb::Models::Customers::BalanceTransactionCreateParams::type_]
        end
      end
    end
  end
end
