module Orb
  module Models
    module Customers
      type cost_list_response = { data: ::Array[Orb::AggregatedCost] }

      class CostListResponse < Orb::Internal::Type::BaseModel
        attr_accessor data: ::Array[Orb::AggregatedCost]

        def initialize: (data: ::Array[Orb::AggregatedCost]) -> void

        def to_hash: -> { data: ::Array[Orb::AggregatedCost] }
      end
    end
  end
end
