module Orb
  module Models
    module Customers
      type credit_list_response =
        {
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::Customers::CreditListResponse::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::Customers::CreditListResponse::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::Customers::CreditListResponse::status,
          credit_allocation: Orb::Models::Customers::CreditListResponse::CreditAllocation?,
          credit_commitment: Orb::Models::Customers::CreditListResponse::CreditCommitment?
        }

      class CreditListResponse < Orb::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor balance: Float

        attr_accessor credit_block_source: Orb::Models::Customers::CreditListResponse::credit_block_source

        attr_accessor effective_date: Time?

        attr_accessor expiry_date: Time?

        attr_accessor filters: ::Array[Orb::Models::Customers::CreditListResponse::Filter]

        attr_accessor maximum_initial_balance: Float?

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_accessor per_unit_cost_basis: String?

        attr_accessor status: Orb::Models::Customers::CreditListResponse::status

        attr_accessor credit_allocation: Orb::Models::Customers::CreditListResponse::CreditAllocation?

        attr_accessor credit_commitment: Orb::Models::Customers::CreditListResponse::CreditCommitment?

        def initialize: (
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::Customers::CreditListResponse::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::Customers::CreditListResponse::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::Customers::CreditListResponse::status,
          ?credit_allocation: Orb::Models::Customers::CreditListResponse::CreditAllocation?,
          ?credit_commitment: Orb::Models::Customers::CreditListResponse::CreditCommitment?
        ) -> void

        def to_hash: -> {
          id: String,
          balance: Float,
          credit_block_source: Orb::Models::Customers::CreditListResponse::credit_block_source,
          effective_date: Time?,
          expiry_date: Time?,
          filters: ::Array[Orb::Models::Customers::CreditListResponse::Filter],
          maximum_initial_balance: Float?,
          metadata: ::Hash[Symbol, String],
          per_unit_cost_basis: String?,
          status: Orb::Models::Customers::CreditListResponse::status,
          credit_allocation: Orb::Models::Customers::CreditListResponse::CreditAllocation?,
          credit_commitment: Orb::Models::Customers::CreditListResponse::CreditCommitment?
        }

        type credit_block_source = :allocation | :top_up | :commitment | :manual

        module CreditBlockSource
          extend Orb::Internal::Type::Enum

          ALLOCATION: :allocation
          TOP_UP: :top_up
          COMMITMENT: :commitment
          MANUAL: :manual

          def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::credit_block_source]
        end

        type filter =
          {
            field: Orb::Models::Customers::CreditListResponse::Filter::field,
            operator: Orb::Models::Customers::CreditListResponse::Filter::operator,
            values: ::Array[String]
          }

        class Filter < Orb::Internal::Type::BaseModel
          attr_accessor field: Orb::Models::Customers::CreditListResponse::Filter::field

          attr_accessor operator: Orb::Models::Customers::CreditListResponse::Filter::operator

          attr_accessor values: ::Array[String]

          def initialize: (
            field: Orb::Models::Customers::CreditListResponse::Filter::field,
            operator: Orb::Models::Customers::CreditListResponse::Filter::operator,
            values: ::Array[String]
          ) -> void

          def to_hash: -> {
            field: Orb::Models::Customers::CreditListResponse::Filter::field,
            operator: Orb::Models::Customers::CreditListResponse::Filter::operator,
            values: ::Array[String]
          }

          type field = :item_id

          module Field
            extend Orb::Internal::Type::Enum

            ITEM_ID: :item_id

            def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::Filter::field]
          end

          type operator = :includes | :excludes

          module Operator
            extend Orb::Internal::Type::Enum

            INCLUDES: :includes
            EXCLUDES: :excludes

            def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::Filter::operator]
          end
        end

        type status = :active | :pending_payment

        module Status
          extend Orb::Internal::Type::Enum

          ACTIVE: :active
          PENDING_PAYMENT: :pending_payment

          def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::status]
        end

        type credit_allocation =
          {
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            filters: ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter],
            license_type_id: String?
          }

        class CreditAllocation < Orb::Internal::Type::BaseModel
          attr_accessor allows_rollover: bool

          attr_accessor currency: String

          attr_accessor custom_expiration: Orb::CustomExpiration?

          attr_accessor item_id: String

          attr_reader filters: ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter]?

          def filters=: (
            ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter]
          ) -> ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter]

          attr_accessor license_type_id: String?

          def initialize: (
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            ?filters: ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter],
            ?license_type_id: String?
          ) -> void

          def to_hash: -> {
            allows_rollover: bool,
            currency: String,
            custom_expiration: Orb::CustomExpiration?,
            item_id: String,
            filters: ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter],
            license_type_id: String?
          }

          type filter =
            {
              field: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::field,
              operator: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::operator,
              values: ::Array[String]
            }

          class Filter < Orb::Internal::Type::BaseModel
            attr_accessor field: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::field

            attr_accessor operator: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::operator

            attr_accessor values: ::Array[String]

            def initialize: (
              field: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::field,
              operator: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::operator,
              values: ::Array[String]
            ) -> void

            def to_hash: -> {
              field: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::field,
              operator: Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::operator,
              values: ::Array[String]
            }

            type field =
              :price_id | :item_id | :price_type | :currency | :pricing_unit_id

            module Field
              extend Orb::Internal::Type::Enum

              PRICE_ID: :price_id
              ITEM_ID: :item_id
              PRICE_TYPE: :price_type
              CURRENCY: :currency
              PRICING_UNIT_ID: :pricing_unit_id

              def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::field]
            end

            type operator = :includes | :excludes

            module Operator
              extend Orb::Internal::Type::Enum

              INCLUDES: :includes
              EXCLUDES: :excludes

              def self?.values: -> ::Array[Orb::Models::Customers::CreditListResponse::CreditAllocation::Filter::operator]
            end
          end
        end

        type credit_commitment = { id: String, subscription_id: String? }

        class CreditCommitment < Orb::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor subscription_id: String?

          def initialize: (id: String, ?subscription_id: String?) -> void

          def to_hash: -> { id: String, subscription_id: String? }
        end
      end
    end
  end
end
