module Orb
  module Models
    module Customers
      type credit_list_params =
        {
          customer_id: String,
          currency: String?,
          cursor: String?,
          effective_date_gt: Time?,
          effective_date_gte: Time?,
          effective_date_lt: Time?,
          effective_date_lte: Time?,
          include_all_blocks: bool,
          limit: Integer
        }
        & Orb::Internal::Type::request_parameters

      class CreditListParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_accessor currency: String?

        attr_accessor cursor: String?

        attr_accessor effective_date_gt: Time?

        attr_accessor effective_date_gte: Time?

        attr_accessor effective_date_lt: Time?

        attr_accessor effective_date_lte: Time?

        attr_reader include_all_blocks: bool?

        def include_all_blocks=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          customer_id: String,
          ?currency: String?,
          ?cursor: String?,
          ?effective_date_gt: Time?,
          ?effective_date_gte: Time?,
          ?effective_date_lt: Time?,
          ?effective_date_lte: Time?,
          ?include_all_blocks: bool,
          ?limit: Integer,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          currency: String?,
          cursor: String?,
          effective_date_gt: Time?,
          effective_date_gte: Time?,
          effective_date_lt: Time?,
          effective_date_lte: Time?,
          include_all_blocks: bool,
          limit: Integer,
          request_options: Orb::RequestOptions
        }
      end
    end
  end
end
