module Orb
  module Models
    module Customers
      type credit_list_params =
        {
          currency: String?,
          cursor: String?,
          include_all_blocks: bool,
          limit: Integer
        }
        & Orb::Internal::Type::request_parameters

      class CreditListParams < Orb::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor currency: String?

        attr_accessor cursor: String?

        attr_reader include_all_blocks: bool?

        def include_all_blocks=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          ?currency: String?,
          ?cursor: String?,
          ?include_all_blocks: bool,
          ?limit: Integer,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> Orb::Models::Customers::credit_list_params
      end
    end
  end
end
