module Orb
  module Resources
    class Coupons
      class Subscriptions
        def list:
          (
            String coupon_id,
            ?Orb::Models::Coupons::SubscriptionListParams
            | ::Hash[Symbol, top] params
          ) -> Orb::Page[Orb::Models::SubscriptionModel]
          | (
            String coupon_id,
            cursor: String?,
            limit: Integer,
            request_options: Orb::request_opts
          ) -> Orb::Page[Orb::Models::SubscriptionModel]

        def initialize: (client: Orb::Client) -> void
      end
    end
  end
end
