module Orb
  module Resources
    class Coupons
      class Subscriptions
        def list: (
          String coupon_id,
          ?cursor: String?,
          ?limit: Integer,
          ?request_options: Orb::request_opts
        ) -> Orb::Page[Orb::Models::Subscription]

        def initialize: (client: Orb::Client) -> void
      end
    end
  end
end
