module Orb
  module Resources
    class Customers
      class Credits
        class Ledger
          def list:
            (
              String customer_id,
              ?Orb::Models::Customers::Credits::LedgerListParams
              | ::Hash[Symbol, top] params
            ) -> Orb::Page[Orb::Models::credit_ledger_entry_model]
            | (
              String customer_id,
              created_at_gt: Time?,
              created_at_gte: Time?,
              created_at_lt: Time?,
              created_at_lte: Time?,
              currency: String?,
              cursor: String?,
              entry_status: Orb::Models::Customers::Credits::LedgerListParams::entry_status?,
              entry_type: Orb::Models::Customers::Credits::LedgerListParams::entry_type?,
              limit: Integer,
              minimum_amount: String?,
              request_options: Orb::request_opts
            ) -> Orb::Page[Orb::Models::credit_ledger_entry_model]

          def create_entry:
            (
              String customer_id,
              Orb::Models::Customers::Credits::LedgerCreateEntryParams
              | ::Hash[Symbol, top] params
            ) -> Orb::Models::credit_ledger_entry_model
            | (
              String customer_id,
              add_credit_ledger_entry_request: Orb::Models::AddCreditLedgerEntryRequest,
              request_options: Orb::request_opts
            ) -> Orb::Models::credit_ledger_entry_model

          def create_entry_by_external_id:
            (
              String external_customer_id,
              Orb::Models::Customers::Credits::LedgerCreateEntryByExternalIDParams
              | ::Hash[Symbol, top] params
            ) -> Orb::Models::credit_ledger_entry_model
            | (
              String external_customer_id,
              add_credit_ledger_entry_request: Orb::Models::AddCreditLedgerEntryRequest,
              request_options: Orb::request_opts
            ) -> Orb::Models::credit_ledger_entry_model

          def list_by_external_id:
            (
              String external_customer_id,
              ?Orb::Models::Customers::Credits::LedgerListByExternalIDParams
              | ::Hash[Symbol, top] params
            ) -> Orb::Page[Orb::Models::credit_ledger_entry_model]
            | (
              String external_customer_id,
              created_at_gt: Time?,
              created_at_gte: Time?,
              created_at_lt: Time?,
              created_at_lte: Time?,
              currency: String?,
              cursor: String?,
              entry_status: Orb::Models::Customers::Credits::LedgerListByExternalIDParams::entry_status?,
              entry_type: Orb::Models::Customers::Credits::LedgerListByExternalIDParams::entry_type?,
              limit: Integer,
              minimum_amount: String?,
              request_options: Orb::request_opts
            ) -> Orb::Page[Orb::Models::credit_ledger_entry_model]

          def initialize: (client: Orb::Client) -> void
        end
      end
    end
  end
end
