module Orb
  module Resources
    class Beta
      class ExternalPlanID
        def create_plan_version: (
          String external_plan_id,
          version: Integer,
          ?add_adjustments: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::AddAdjustment]?,
          ?add_prices: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::AddPrice]?,
          ?remove_adjustments: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::RemoveAdjustment]?,
          ?remove_prices: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::RemovePrice]?,
          ?replace_adjustments: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::ReplaceAdjustment]?,
          ?replace_prices: ::Array[Orb::Beta::ExternalPlanIDCreatePlanVersionParams::ReplacePrice]?,
          ?set_as_default: bool?,
          ?request_options: Orb::request_opts
        ) -> Orb::PlanVersion

        def fetch_plan_version: (
          String version,
          external_plan_id: String,
          ?request_options: Orb::request_opts
        ) -> Orb::PlanVersion

        def set_default_plan_version: (
          String external_plan_id,
          version: Integer,
          ?request_options: Orb::request_opts
        ) -> Orb::Plan

        def initialize: (client: Orb::Client) -> void
      end
    end
  end
end
