module Orb
  class Error < StandardError
    attr_reader cause: StandardError?
  end

  class ConversionError < Orb::Error
  end

  class APIError < Orb::Error
    attr_reader url: URI::Generic

    attr_reader status: Integer?

    attr_reader body: top?

    def initialize: (
      url: URI::Generic,
      status: Integer?,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIConnectionError < Orb::APIError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APITimeoutError < Orb::APIConnectionError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIStatusError < Orb::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class BadRequestError < Orb::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Orb::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Orb::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Orb::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Orb::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Orb::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Orb::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Orb::APIStatusError
    HTTP_STATUS: Range[Integer]
  end

  class ConstraintViolation < Orb::BadRequestError
    HTTP_STATUS: 400

    TYPE: "https://docs.withorb.com/reference/error-responses#400-constraint-violation"
  end

  class DuplicateResourceCreation < Orb::BadRequestError
    HTTP_STATUS: 400

    TYPE: "https://docs.withorb.com/reference/error-responses#400-duplicate-resource-creation"
  end

  class FeatureNotAvailable < Orb::BadRequestError
    HTTP_STATUS: 400

    TYPE: "https://docs.withorb.com/reference/error-responses#404-feature-not-available"
  end

  class RequestValidationError < Orb::BadRequestError
    HTTP_STATUS: 400

    TYPE: "https://docs.withorb.com/reference/error-responses#400-request-validation-errors"
  end

  class OrbAuthenticationError < Orb::AuthenticationError
    HTTP_STATUS: 401

    TYPE: "https://docs.withorb.com/reference/error-responses#401-authentication-error"
  end

  class ResourceNotFound < Orb::NotFoundError
    HTTP_STATUS: 404

    TYPE: "https://docs.withorb.com/reference/error-responses#404-resource-not-found"
  end

  class URLNotFound < Orb::NotFoundError
    HTTP_STATUS: 404

    TYPE: "https://docs.withorb.com/reference/error-responses#404-url-not-found"
  end

  class ResourceConflict < Orb::ConflictError
    HTTP_STATUS: 409

    TYPE: "https://docs.withorb.com/reference/error-responses#409-resource-conflict"
  end

  class RequestTooLarge < Orb::APIStatusError
    HTTP_STATUS: 413

    TYPE: "https://docs.withorb.com/reference/error-responses#413-request-too-large"
  end

  class ResourceTooLarge < Orb::APIStatusError
    HTTP_STATUS: 413

    TYPE: "https://docs.withorb.com/reference/error-responses#413-resource-too-large"
  end

  class TooManyRequests < Orb::RateLimitError
    HTTP_STATUS: 429

    TYPE: "https://docs.withorb.com/reference/error-responses#429-too-many-requests"
  end

  class OrbInternalServerError < Orb::InternalServerError
    HTTP_STATUS: Range[Integer]

    TYPE: "https://docs.withorb.com/reference/error-responses#500-internal-server-error"
  end
end
