module Orb
  module Models
    module Events
      type backfill_close_params =
        {  } & Orb::Internal::Type::request_parameters

      class BackfillCloseParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        def initialize: (?request_options: Orb::request_opts) -> void

        def to_hash: -> Orb::Models::Events::backfill_close_params
      end
    end
  end
end
