module Orb
  module Models
    module Events
      type backfill_revert_params = {  } & Orb::request_parameters

      class BackfillRevertParams < Orb::BaseModel
        extend Orb::RequestParameters::Converter
        include Orb::RequestParameters

        def initialize:
          (request_options: Orb::request_opts) -> void
          | (
            ?Orb::Models::Events::backfill_revert_params | Orb::BaseModel data
          ) -> void

        def to_h: -> Orb::Models::Events::backfill_revert_params
      end
    end
  end
end
