module Orb
  module Models
    module Events
      type backfill_revert_params =
        { backfill_id: String } & Orb::Internal::Type::request_parameters

      class BackfillRevertParams < Orb::Internal::Type::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor backfill_id: String

        def initialize: (
          backfill_id: String,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> {
          backfill_id: String,
          request_options: Orb::RequestOptions
        }
      end
    end
  end
end
