module Orb
  module Models
    module Events
      type volume_list_params =
        {
          timeframe_start: Time,
          cursor: String?,
          limit: Integer,
          timeframe_end: Time
        }
        & Orb::Internal::Type::request_parameters

      class VolumeListParams < Orb::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        attr_accessor timeframe_start: Time

        attr_accessor cursor: String?

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader timeframe_end: Time?

        def timeframe_end=: (Time) -> Time

        def initialize: (
          timeframe_start: Time,
          ?cursor: String?,
          ?limit: Integer,
          ?timeframe_end: Time,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> Orb::Models::Events::volume_list_params
      end
    end
  end
end
