# frozen_string_literal: true

require_relative "../../test_helper"

class Orb::Test::Resources::Prices::ExternalPriceIDTest < Orb::Test::ResourceTest
  def test_update
    response = @orb.prices.external_price_id.update("external_price_id")

    assert_pattern do
      response => Orb::Models::Price
    end

    assert_pattern do
      case response
      in Orb::Models::Price::Unit
      in Orb::Models::Price::Package
      in Orb::Models::Price::Matrix
      in Orb::Models::Price::Tiered
      in Orb::Models::Price::TieredBps
      in Orb::Models::Price::Bps
      in Orb::Models::Price::BulkBps
      in Orb::Models::Price::Bulk
      in Orb::Models::Price::ThresholdTotalAmount
      in Orb::Models::Price::TieredPackage
      in Orb::Models::Price::GroupedTiered
      in Orb::Models::Price::TieredWithMinimum
      in Orb::Models::Price::TieredPackageWithMinimum
      in Orb::Models::Price::PackageWithAllocation
      in Orb::Models::Price::UnitWithPercent
      in Orb::Models::Price::MatrixWithAllocation
      in Orb::Models::Price::TieredWithProration
      in Orb::Models::Price::UnitWithProration
      in Orb::Models::Price::GroupedAllocation
      in Orb::Models::Price::GroupedWithProratedMinimum
      in Orb::Models::Price::GroupedWithMeteredMinimum
      in Orb::Models::Price::MatrixWithDisplayName
      in Orb::Models::Price::BulkWithProration
      in Orb::Models::Price::GroupedTieredPackage
      in Orb::Models::Price::MaxGroupTieredPackage
      in Orb::Models::Price::ScalableMatrixWithUnitPricing
      in Orb::Models::Price::ScalableMatrixWithTieredPricing
      in Orb::Models::Price::CumulativeGroupedBulk
      end
    end

    assert_pattern do
      case response
      in {
        model_type: :unit,
        id: String,
        billable_metric: Orb::Models::Price::Unit::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Unit::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Unit::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Unit::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Unit::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Unit::Item,
        maximum: Orb::Models::Price::Unit::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Unit::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Unit::PriceType,
        unit_config: Orb::Models::Price::Unit::UnitConfig,
        dimensional_price_configuration: Orb::Models::Price::Unit::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package,
        id: String,
        billable_metric: Orb::Models::Price::Package::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Package::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Package::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Package::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Package::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Package::Item,
        maximum: Orb::Models::Price::Package::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Package::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_config: Orb::Models::Price::Package::PackageConfig,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Package::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Package::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix,
        id: String,
        billable_metric: Orb::Models::Price::Matrix::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Matrix::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Matrix::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Matrix::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Matrix::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Matrix::Item,
        matrix_config: Orb::Models::Price::Matrix::MatrixConfig,
        maximum: Orb::Models::Price::Matrix::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Matrix::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Matrix::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Matrix::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered,
        id: String,
        billable_metric: Orb::Models::Price::Tiered::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Tiered::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Tiered::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Tiered::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Tiered::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Tiered::Item,
        maximum: Orb::Models::Price::Tiered::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Tiered::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Tiered::PriceType,
        tiered_config: Orb::Models::Price::Tiered::TieredConfig,
        dimensional_price_configuration: Orb::Models::Price::Tiered::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_bps,
        id: String,
        billable_metric: Orb::Models::Price::TieredBps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredBps::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredBps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredBps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredBps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredBps::Item,
        maximum: Orb::Models::Price::TieredBps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredBps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredBps::PriceType,
        tiered_bps_config: Orb::Models::Price::TieredBps::TieredBpsConfig,
        dimensional_price_configuration: Orb::Models::Price::TieredBps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bps,
        id: String,
        billable_metric: Orb::Models::Price::Bps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Bps::BillingCycleConfiguration,
        bps_config: Orb::Models::Price::Bps::BpsConfig,
        cadence: Orb::Models::Price::Bps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Bps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Bps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Bps::Item,
        maximum: Orb::Models::Price::Bps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Bps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Bps::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Bps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_bps,
        id: String,
        billable_metric: Orb::Models::Price::BulkBps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::BulkBps::BillingCycleConfiguration,
        bulk_bps_config: Orb::Models::Price::BulkBps::BulkBpsConfig,
        cadence: Orb::Models::Price::BulkBps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::BulkBps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::BulkBps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::BulkBps::Item,
        maximum: Orb::Models::Price::BulkBps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::BulkBps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::BulkBps::PriceType,
        dimensional_price_configuration: Orb::Models::Price::BulkBps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk,
        id: String,
        billable_metric: Orb::Models::Price::Bulk::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Bulk::BillingCycleConfiguration,
        bulk_config: Orb::Models::Price::Bulk::BulkConfig,
        cadence: Orb::Models::Price::Bulk::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Bulk::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Bulk::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Bulk::Item,
        maximum: Orb::Models::Price::Bulk::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Bulk::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Bulk::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Bulk::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :threshold_total_amount,
        id: String,
        billable_metric: Orb::Models::Price::ThresholdTotalAmount::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ThresholdTotalAmount::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ThresholdTotalAmount::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ThresholdTotalAmount::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ThresholdTotalAmount::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ThresholdTotalAmount::Item,
        maximum: Orb::Models::Price::ThresholdTotalAmount::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ThresholdTotalAmount::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ThresholdTotalAmount::PriceType,
        threshold_total_amount_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ThresholdTotalAmount::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::TieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredPackage::Item,
        maximum: Orb::Models::Price::TieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredPackage::PriceType,
        tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered,
        id: String,
        billable_metric: Orb::Models::Price::GroupedTiered::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedTiered::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedTiered::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedTiered::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedTiered::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedTiered::Item,
        maximum: Orb::Models::Price::GroupedTiered::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedTiered::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedTiered::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedTiered::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_minimum,
        id: String,
        billable_metric: Orb::Models::Price::TieredWithMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredWithMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredWithMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredWithMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredWithMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredWithMinimum::Item,
        maximum: Orb::Models::Price::TieredWithMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredWithMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredWithMinimum::PriceType,
        tiered_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredWithMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package_with_minimum,
        id: String,
        billable_metric: Orb::Models::Price::TieredPackageWithMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredPackageWithMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredPackageWithMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredPackageWithMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredPackageWithMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredPackageWithMinimum::Item,
        maximum: Orb::Models::Price::TieredPackageWithMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredPackageWithMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredPackageWithMinimum::PriceType,
        tiered_package_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredPackageWithMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package_with_allocation,
        id: String,
        billable_metric: Orb::Models::Price::PackageWithAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::PackageWithAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::PackageWithAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::PackageWithAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::PackageWithAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::PackageWithAllocation::Item,
        maximum: Orb::Models::Price::PackageWithAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::PackageWithAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_with_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::PackageWithAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::PackageWithAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_percent,
        id: String,
        billable_metric: Orb::Models::Price::UnitWithPercent::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::UnitWithPercent::BillingCycleConfiguration,
        cadence: Orb::Models::Price::UnitWithPercent::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::UnitWithPercent::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::UnitWithPercent::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::UnitWithPercent::Item,
        maximum: Orb::Models::Price::UnitWithPercent::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::UnitWithPercent::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::UnitWithPercent::PriceType,
        unit_with_percent_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::UnitWithPercent::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_allocation,
        id: String,
        billable_metric: Orb::Models::Price::MatrixWithAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MatrixWithAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MatrixWithAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MatrixWithAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MatrixWithAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MatrixWithAllocation::Item,
        matrix_with_allocation_config: Orb::Models::Price::MatrixWithAllocation::MatrixWithAllocationConfig,
        maximum: Orb::Models::Price::MatrixWithAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MatrixWithAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MatrixWithAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MatrixWithAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::TieredWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredWithProration::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredWithProration::Item,
        maximum: Orb::Models::Price::TieredWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredWithProration::PriceType,
        tiered_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::UnitWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::UnitWithProration::BillingCycleConfiguration,
        cadence: Orb::Models::Price::UnitWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::UnitWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::UnitWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::UnitWithProration::Item,
        maximum: Orb::Models::Price::UnitWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::UnitWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::UnitWithProration::PriceType,
        unit_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::UnitWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_allocation,
        id: String,
        billable_metric: Orb::Models::Price::GroupedAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedAllocation::Item,
        maximum: Orb::Models::Price::GroupedAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_prorated_minimum,
        id: String,
        billable_metric: Orb::Models::Price::GroupedWithProratedMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedWithProratedMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedWithProratedMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedWithProratedMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_prorated_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedWithProratedMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedWithProratedMinimum::Item,
        maximum: Orb::Models::Price::GroupedWithProratedMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedWithProratedMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedWithProratedMinimum::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedWithProratedMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_metered_minimum,
        id: String,
        billable_metric: Orb::Models::Price::GroupedWithMeteredMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedWithMeteredMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedWithMeteredMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_metered_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedWithMeteredMinimum::Item,
        maximum: Orb::Models::Price::GroupedWithMeteredMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedWithMeteredMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedWithMeteredMinimum::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_display_name,
        id: String,
        billable_metric: Orb::Models::Price::MatrixWithDisplayName::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MatrixWithDisplayName::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MatrixWithDisplayName::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MatrixWithDisplayName::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MatrixWithDisplayName::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MatrixWithDisplayName::Item,
        matrix_with_display_name_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Models::Price::MatrixWithDisplayName::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MatrixWithDisplayName::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MatrixWithDisplayName::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MatrixWithDisplayName::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::BulkWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::BulkWithProration::BillingCycleConfiguration,
        bulk_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        cadence: Orb::Models::Price::BulkWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::BulkWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::BulkWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::BulkWithProration::Item,
        maximum: Orb::Models::Price::BulkWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::BulkWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::BulkWithProration::PriceType,
        dimensional_price_configuration: Orb::Models::Price::BulkWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::GroupedTieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedTieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedTieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedTieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedTieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedTieredPackage::Item,
        maximum: Orb::Models::Price::GroupedTieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedTieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedTieredPackage::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedTieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :max_group_tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::MaxGroupTieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MaxGroupTieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MaxGroupTieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MaxGroupTieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MaxGroupTieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MaxGroupTieredPackage::Item,
        max_group_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Models::Price::MaxGroupTieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MaxGroupTieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MaxGroupTieredPackage::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MaxGroupTieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_unit_pricing,
        id: String,
        billable_metric: Orb::Models::Price::ScalableMatrixWithUnitPricing::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ScalableMatrixWithUnitPricing::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ScalableMatrixWithUnitPricing::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ScalableMatrixWithUnitPricing::Item,
        maximum: Orb::Models::Price::ScalableMatrixWithUnitPricing::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ScalableMatrixWithUnitPricing::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ScalableMatrixWithUnitPricing::PriceType,
        scalable_matrix_with_unit_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_tiered_pricing,
        id: String,
        billable_metric: Orb::Models::Price::ScalableMatrixWithTieredPricing::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ScalableMatrixWithTieredPricing::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ScalableMatrixWithTieredPricing::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ScalableMatrixWithTieredPricing::Item,
        maximum: Orb::Models::Price::ScalableMatrixWithTieredPricing::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ScalableMatrixWithTieredPricing::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ScalableMatrixWithTieredPricing::PriceType,
        scalable_matrix_with_tiered_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :cumulative_grouped_bulk,
        id: String,
        billable_metric: Orb::Models::Price::CumulativeGroupedBulk::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::CumulativeGroupedBulk::BillingCycleConfiguration,
        cadence: Orb::Models::Price::CumulativeGroupedBulk::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::CumulativeGroupedBulk::CreditAllocation | nil,
        cumulative_grouped_bulk_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::CumulativeGroupedBulk::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::CumulativeGroupedBulk::Item,
        maximum: Orb::Models::Price::CumulativeGroupedBulk::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::CumulativeGroupedBulk::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::CumulativeGroupedBulk::PriceType,
        dimensional_price_configuration: Orb::Models::Price::CumulativeGroupedBulk::DimensionalPriceConfiguration | nil
      }
      end
    end
  end

  def test_fetch
    response = @orb.prices.external_price_id.fetch("external_price_id")

    assert_pattern do
      response => Orb::Models::Price
    end

    assert_pattern do
      case response
      in Orb::Models::Price::Unit
      in Orb::Models::Price::Package
      in Orb::Models::Price::Matrix
      in Orb::Models::Price::Tiered
      in Orb::Models::Price::TieredBps
      in Orb::Models::Price::Bps
      in Orb::Models::Price::BulkBps
      in Orb::Models::Price::Bulk
      in Orb::Models::Price::ThresholdTotalAmount
      in Orb::Models::Price::TieredPackage
      in Orb::Models::Price::GroupedTiered
      in Orb::Models::Price::TieredWithMinimum
      in Orb::Models::Price::TieredPackageWithMinimum
      in Orb::Models::Price::PackageWithAllocation
      in Orb::Models::Price::UnitWithPercent
      in Orb::Models::Price::MatrixWithAllocation
      in Orb::Models::Price::TieredWithProration
      in Orb::Models::Price::UnitWithProration
      in Orb::Models::Price::GroupedAllocation
      in Orb::Models::Price::GroupedWithProratedMinimum
      in Orb::Models::Price::GroupedWithMeteredMinimum
      in Orb::Models::Price::MatrixWithDisplayName
      in Orb::Models::Price::BulkWithProration
      in Orb::Models::Price::GroupedTieredPackage
      in Orb::Models::Price::MaxGroupTieredPackage
      in Orb::Models::Price::ScalableMatrixWithUnitPricing
      in Orb::Models::Price::ScalableMatrixWithTieredPricing
      in Orb::Models::Price::CumulativeGroupedBulk
      end
    end

    assert_pattern do
      case response
      in {
        model_type: :unit,
        id: String,
        billable_metric: Orb::Models::Price::Unit::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Unit::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Unit::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Unit::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Unit::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Unit::Item,
        maximum: Orb::Models::Price::Unit::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Unit::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Unit::PriceType,
        unit_config: Orb::Models::Price::Unit::UnitConfig,
        dimensional_price_configuration: Orb::Models::Price::Unit::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package,
        id: String,
        billable_metric: Orb::Models::Price::Package::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Package::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Package::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Package::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Package::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Package::Item,
        maximum: Orb::Models::Price::Package::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Package::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_config: Orb::Models::Price::Package::PackageConfig,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Package::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Package::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix,
        id: String,
        billable_metric: Orb::Models::Price::Matrix::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Matrix::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Matrix::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Matrix::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Matrix::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Matrix::Item,
        matrix_config: Orb::Models::Price::Matrix::MatrixConfig,
        maximum: Orb::Models::Price::Matrix::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Matrix::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Matrix::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Matrix::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered,
        id: String,
        billable_metric: Orb::Models::Price::Tiered::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Tiered::BillingCycleConfiguration,
        cadence: Orb::Models::Price::Tiered::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Tiered::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Tiered::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Tiered::Item,
        maximum: Orb::Models::Price::Tiered::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Tiered::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Tiered::PriceType,
        tiered_config: Orb::Models::Price::Tiered::TieredConfig,
        dimensional_price_configuration: Orb::Models::Price::Tiered::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_bps,
        id: String,
        billable_metric: Orb::Models::Price::TieredBps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredBps::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredBps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredBps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredBps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredBps::Item,
        maximum: Orb::Models::Price::TieredBps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredBps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredBps::PriceType,
        tiered_bps_config: Orb::Models::Price::TieredBps::TieredBpsConfig,
        dimensional_price_configuration: Orb::Models::Price::TieredBps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bps,
        id: String,
        billable_metric: Orb::Models::Price::Bps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Bps::BillingCycleConfiguration,
        bps_config: Orb::Models::Price::Bps::BpsConfig,
        cadence: Orb::Models::Price::Bps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Bps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Bps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Bps::Item,
        maximum: Orb::Models::Price::Bps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Bps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Bps::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Bps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_bps,
        id: String,
        billable_metric: Orb::Models::Price::BulkBps::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::BulkBps::BillingCycleConfiguration,
        bulk_bps_config: Orb::Models::Price::BulkBps::BulkBpsConfig,
        cadence: Orb::Models::Price::BulkBps::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::BulkBps::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::BulkBps::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::BulkBps::Item,
        maximum: Orb::Models::Price::BulkBps::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::BulkBps::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::BulkBps::PriceType,
        dimensional_price_configuration: Orb::Models::Price::BulkBps::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk,
        id: String,
        billable_metric: Orb::Models::Price::Bulk::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::Bulk::BillingCycleConfiguration,
        bulk_config: Orb::Models::Price::Bulk::BulkConfig,
        cadence: Orb::Models::Price::Bulk::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::Bulk::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::Bulk::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::Bulk::Item,
        maximum: Orb::Models::Price::Bulk::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::Bulk::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::Bulk::PriceType,
        dimensional_price_configuration: Orb::Models::Price::Bulk::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :threshold_total_amount,
        id: String,
        billable_metric: Orb::Models::Price::ThresholdTotalAmount::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ThresholdTotalAmount::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ThresholdTotalAmount::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ThresholdTotalAmount::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ThresholdTotalAmount::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ThresholdTotalAmount::Item,
        maximum: Orb::Models::Price::ThresholdTotalAmount::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ThresholdTotalAmount::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ThresholdTotalAmount::PriceType,
        threshold_total_amount_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ThresholdTotalAmount::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::TieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredPackage::Item,
        maximum: Orb::Models::Price::TieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredPackage::PriceType,
        tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered,
        id: String,
        billable_metric: Orb::Models::Price::GroupedTiered::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedTiered::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedTiered::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedTiered::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedTiered::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedTiered::Item,
        maximum: Orb::Models::Price::GroupedTiered::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedTiered::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedTiered::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedTiered::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_minimum,
        id: String,
        billable_metric: Orb::Models::Price::TieredWithMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredWithMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredWithMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredWithMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredWithMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredWithMinimum::Item,
        maximum: Orb::Models::Price::TieredWithMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredWithMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredWithMinimum::PriceType,
        tiered_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredWithMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package_with_minimum,
        id: String,
        billable_metric: Orb::Models::Price::TieredPackageWithMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredPackageWithMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredPackageWithMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredPackageWithMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredPackageWithMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredPackageWithMinimum::Item,
        maximum: Orb::Models::Price::TieredPackageWithMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredPackageWithMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredPackageWithMinimum::PriceType,
        tiered_package_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredPackageWithMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package_with_allocation,
        id: String,
        billable_metric: Orb::Models::Price::PackageWithAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::PackageWithAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::PackageWithAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::PackageWithAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::PackageWithAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::PackageWithAllocation::Item,
        maximum: Orb::Models::Price::PackageWithAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::PackageWithAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_with_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::PackageWithAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::PackageWithAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_percent,
        id: String,
        billable_metric: Orb::Models::Price::UnitWithPercent::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::UnitWithPercent::BillingCycleConfiguration,
        cadence: Orb::Models::Price::UnitWithPercent::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::UnitWithPercent::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::UnitWithPercent::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::UnitWithPercent::Item,
        maximum: Orb::Models::Price::UnitWithPercent::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::UnitWithPercent::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::UnitWithPercent::PriceType,
        unit_with_percent_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::UnitWithPercent::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_allocation,
        id: String,
        billable_metric: Orb::Models::Price::MatrixWithAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MatrixWithAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MatrixWithAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MatrixWithAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MatrixWithAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MatrixWithAllocation::Item,
        matrix_with_allocation_config: Orb::Models::Price::MatrixWithAllocation::MatrixWithAllocationConfig,
        maximum: Orb::Models::Price::MatrixWithAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MatrixWithAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MatrixWithAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MatrixWithAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::TieredWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::TieredWithProration::BillingCycleConfiguration,
        cadence: Orb::Models::Price::TieredWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::TieredWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::TieredWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::TieredWithProration::Item,
        maximum: Orb::Models::Price::TieredWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::TieredWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::TieredWithProration::PriceType,
        tiered_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::TieredWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::UnitWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::UnitWithProration::BillingCycleConfiguration,
        cadence: Orb::Models::Price::UnitWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::UnitWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::UnitWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::UnitWithProration::Item,
        maximum: Orb::Models::Price::UnitWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::UnitWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::UnitWithProration::PriceType,
        unit_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::UnitWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_allocation,
        id: String,
        billable_metric: Orb::Models::Price::GroupedAllocation::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedAllocation::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedAllocation::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedAllocation::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedAllocation::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedAllocation::Item,
        maximum: Orb::Models::Price::GroupedAllocation::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedAllocation::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedAllocation::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedAllocation::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_prorated_minimum,
        id: String,
        billable_metric: Orb::Models::Price::GroupedWithProratedMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedWithProratedMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedWithProratedMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedWithProratedMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_prorated_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedWithProratedMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedWithProratedMinimum::Item,
        maximum: Orb::Models::Price::GroupedWithProratedMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedWithProratedMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedWithProratedMinimum::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedWithProratedMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_metered_minimum,
        id: String,
        billable_metric: Orb::Models::Price::GroupedWithMeteredMinimum::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedWithMeteredMinimum::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedWithMeteredMinimum::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_metered_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedWithMeteredMinimum::Item,
        maximum: Orb::Models::Price::GroupedWithMeteredMinimum::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedWithMeteredMinimum::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedWithMeteredMinimum::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedWithMeteredMinimum::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_display_name,
        id: String,
        billable_metric: Orb::Models::Price::MatrixWithDisplayName::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MatrixWithDisplayName::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MatrixWithDisplayName::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MatrixWithDisplayName::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MatrixWithDisplayName::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MatrixWithDisplayName::Item,
        matrix_with_display_name_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Models::Price::MatrixWithDisplayName::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MatrixWithDisplayName::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MatrixWithDisplayName::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MatrixWithDisplayName::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_with_proration,
        id: String,
        billable_metric: Orb::Models::Price::BulkWithProration::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::BulkWithProration::BillingCycleConfiguration,
        bulk_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        cadence: Orb::Models::Price::BulkWithProration::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::BulkWithProration::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::BulkWithProration::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::BulkWithProration::Item,
        maximum: Orb::Models::Price::BulkWithProration::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::BulkWithProration::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::BulkWithProration::PriceType,
        dimensional_price_configuration: Orb::Models::Price::BulkWithProration::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::GroupedTieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::GroupedTieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::GroupedTieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::GroupedTieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::Models::Price::GroupedTieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::GroupedTieredPackage::Item,
        maximum: Orb::Models::Price::GroupedTieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::GroupedTieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::GroupedTieredPackage::PriceType,
        dimensional_price_configuration: Orb::Models::Price::GroupedTieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :max_group_tiered_package,
        id: String,
        billable_metric: Orb::Models::Price::MaxGroupTieredPackage::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::MaxGroupTieredPackage::BillingCycleConfiguration,
        cadence: Orb::Models::Price::MaxGroupTieredPackage::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::MaxGroupTieredPackage::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::MaxGroupTieredPackage::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::MaxGroupTieredPackage::Item,
        max_group_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Models::Price::MaxGroupTieredPackage::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::MaxGroupTieredPackage::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::MaxGroupTieredPackage::PriceType,
        dimensional_price_configuration: Orb::Models::Price::MaxGroupTieredPackage::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_unit_pricing,
        id: String,
        billable_metric: Orb::Models::Price::ScalableMatrixWithUnitPricing::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ScalableMatrixWithUnitPricing::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ScalableMatrixWithUnitPricing::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ScalableMatrixWithUnitPricing::Item,
        maximum: Orb::Models::Price::ScalableMatrixWithUnitPricing::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ScalableMatrixWithUnitPricing::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ScalableMatrixWithUnitPricing::PriceType,
        scalable_matrix_with_unit_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ScalableMatrixWithUnitPricing::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_tiered_pricing,
        id: String,
        billable_metric: Orb::Models::Price::ScalableMatrixWithTieredPricing::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::BillingCycleConfiguration,
        cadence: Orb::Models::Price::ScalableMatrixWithTieredPricing::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::ScalableMatrixWithTieredPricing::CreditAllocation | nil,
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::ScalableMatrixWithTieredPricing::Item,
        maximum: Orb::Models::Price::ScalableMatrixWithTieredPricing::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::ScalableMatrixWithTieredPricing::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::ScalableMatrixWithTieredPricing::PriceType,
        scalable_matrix_with_tiered_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::Models::Price::ScalableMatrixWithTieredPricing::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :cumulative_grouped_bulk,
        id: String,
        billable_metric: Orb::Models::Price::CumulativeGroupedBulk::BillableMetric | nil,
        billing_cycle_configuration: Orb::Models::Price::CumulativeGroupedBulk::BillingCycleConfiguration,
        cadence: Orb::Models::Price::CumulativeGroupedBulk::Cadence,
        conversion_rate: Float | nil,
        created_at: Time,
        credit_allocation: Orb::Models::Price::CumulativeGroupedBulk::CreditAllocation | nil,
        cumulative_grouped_bulk_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        currency: String,
        discount: Orb::Models::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::Models::Price::CumulativeGroupedBulk::InvoicingCycleConfiguration | nil,
        item: Orb::Models::Price::CumulativeGroupedBulk::Item,
        maximum: Orb::Models::Price::CumulativeGroupedBulk::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Models::Price::CumulativeGroupedBulk::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Models::Price::CumulativeGroupedBulk::PriceType,
        dimensional_price_configuration: Orb::Models::Price::CumulativeGroupedBulk::DimensionalPriceConfiguration | nil
      }
      end
    end
  end
end
