# frozen_string_literal: true

require_relative "../../test_helper"

class Orb::Test::Resources::Prices::ExternalPriceIDTest < Orb::Test::ResourceTest
  def test_update
    response = @orb.prices.external_price_id.update("external_price_id")

    assert_pattern do
      response => Orb::Price
    end

    assert_pattern do
      case response
      in Orb::Price::Unit
      in Orb::Price::Package
      in Orb::Price::Matrix
      in Orb::Price::Tiered
      in Orb::Price::Bulk
      in Orb::Price::ThresholdTotalAmount
      in Orb::Price::TieredPackage
      in Orb::Price::GroupedTiered
      in Orb::Price::TieredWithMinimum
      in Orb::Price::TieredPackageWithMinimum
      in Orb::Price::PackageWithAllocation
      in Orb::Price::UnitWithPercent
      in Orb::Price::MatrixWithAllocation
      in Orb::Price::TieredWithProration
      in Orb::Price::UnitWithProration
      in Orb::Price::GroupedAllocation
      in Orb::Price::GroupedWithProratedMinimum
      in Orb::Price::GroupedWithMeteredMinimum
      in Orb::Price::MatrixWithDisplayName
      in Orb::Price::BulkWithProration
      in Orb::Price::GroupedTieredPackage
      in Orb::Price::MaxGroupTieredPackage
      in Orb::Price::ScalableMatrixWithUnitPricing
      in Orb::Price::ScalableMatrixWithTieredPricing
      in Orb::Price::CumulativeGroupedBulk
      in Orb::Price::GroupedWithMinMaxThresholds
      in Orb::Price::Minimum
      end
    end

    assert_pattern do
      case response
      in {
        model_type: :unit,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Unit::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Unit::UnnamedTypeWithobjectParent85 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Unit::PriceType,
        replaces_price_id: String | nil,
        unit_config: Orb::UnitConfig,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Package::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Package::UnnamedTypeWithobjectParent86 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_config: Orb::PackageConfig,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Package::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Matrix::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Matrix::UnnamedTypeWithobjectParent87 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_config: Orb::MatrixConfig,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Matrix::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Tiered::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Tiered::UnnamedTypeWithobjectParent88 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Tiered::PriceType,
        replaces_price_id: String | nil,
        tiered_config: Orb::TieredConfig,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        bulk_config: Orb::BulkConfig,
        cadence: Orb::Price::Bulk::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Bulk::UnnamedTypeWithobjectParent89 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Bulk::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :threshold_total_amount,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ThresholdTotalAmount::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ThresholdTotalAmount::UnnamedTypeWithobjectParent90 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ThresholdTotalAmount::PriceType,
        replaces_price_id: String | nil,
        threshold_total_amount_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredPackage::UnnamedTypeWithobjectParent91 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredPackage::PriceType,
        replaces_price_id: String | nil,
        tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedTiered::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedTiered::UnnamedTypeWithobjectParent92 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedTiered::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredWithMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredWithMinimum::UnnamedTypeWithobjectParent93 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredWithMinimum::PriceType,
        replaces_price_id: String | nil,
        tiered_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package_with_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredPackageWithMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredPackageWithMinimum::UnnamedTypeWithobjectParent94 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredPackageWithMinimum::PriceType,
        replaces_price_id: String | nil,
        tiered_package_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package_with_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::PackageWithAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::PackageWithAllocation::UnnamedTypeWithobjectParent95 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_with_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::PackageWithAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_percent,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::UnitWithPercent::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::UnitWithPercent::UnnamedTypeWithobjectParent96 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::UnitWithPercent::PriceType,
        replaces_price_id: String | nil,
        unit_with_percent_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MatrixWithAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MatrixWithAllocation::UnnamedTypeWithobjectParent97 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_with_allocation_config: Orb::MatrixWithAllocationConfig,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MatrixWithAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredWithProration::UnnamedTypeWithobjectParent98 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredWithProration::PriceType,
        replaces_price_id: String | nil,
        tiered_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::UnitWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::UnitWithProration::UnnamedTypeWithobjectParent99 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::UnitWithProration::PriceType,
        replaces_price_id: String | nil,
        unit_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedAllocation::UnnamedTypeWithobjectParent100 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_prorated_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithProratedMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithProratedMinimum::UnnamedTypeWithobjectParent101 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_prorated_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithProratedMinimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_metered_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithMeteredMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithMeteredMinimum::UnnamedTypeWithobjectParent102 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_metered_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithMeteredMinimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_display_name,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MatrixWithDisplayName::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MatrixWithDisplayName::UnnamedTypeWithobjectParent103 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_with_display_name_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MatrixWithDisplayName::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        bulk_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        cadence: Orb::Price::BulkWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::BulkWithProration::UnnamedTypeWithobjectParent104 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::BulkWithProration::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedTieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedTieredPackage::UnnamedTypeWithobjectParent105 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedTieredPackage::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :max_group_tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MaxGroupTieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MaxGroupTieredPackage::UnnamedTypeWithobjectParent106 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        max_group_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MaxGroupTieredPackage::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_unit_pricing,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ScalableMatrixWithUnitPricing::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ScalableMatrixWithUnitPricing::UnnamedTypeWithobjectParent107 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ScalableMatrixWithUnitPricing::PriceType,
        replaces_price_id: String | nil,
        scalable_matrix_with_unit_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_tiered_pricing,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ScalableMatrixWithTieredPricing::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ScalableMatrixWithTieredPricing::UnnamedTypeWithobjectParent108 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ScalableMatrixWithTieredPricing::PriceType,
        replaces_price_id: String | nil,
        scalable_matrix_with_tiered_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :cumulative_grouped_bulk,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::CumulativeGroupedBulk::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::CumulativeGroupedBulk::UnnamedTypeWithobjectParent109 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        cumulative_grouped_bulk_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::CumulativeGroupedBulk::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_min_max_thresholds,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithMinMaxThresholds::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithMinMaxThresholds::UnnamedTypeWithobjectParent110 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_min_max_thresholds_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithMinMaxThresholds::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Minimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Minimum::UnnamedTypeWithobjectParent111 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        minimum_config: Orb::Price::Minimum::MinimumConfig,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Minimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      end
    end
  end

  def test_fetch
    response = @orb.prices.external_price_id.fetch("external_price_id")

    assert_pattern do
      response => Orb::Price
    end

    assert_pattern do
      case response
      in Orb::Price::Unit
      in Orb::Price::Package
      in Orb::Price::Matrix
      in Orb::Price::Tiered
      in Orb::Price::Bulk
      in Orb::Price::ThresholdTotalAmount
      in Orb::Price::TieredPackage
      in Orb::Price::GroupedTiered
      in Orb::Price::TieredWithMinimum
      in Orb::Price::TieredPackageWithMinimum
      in Orb::Price::PackageWithAllocation
      in Orb::Price::UnitWithPercent
      in Orb::Price::MatrixWithAllocation
      in Orb::Price::TieredWithProration
      in Orb::Price::UnitWithProration
      in Orb::Price::GroupedAllocation
      in Orb::Price::GroupedWithProratedMinimum
      in Orb::Price::GroupedWithMeteredMinimum
      in Orb::Price::MatrixWithDisplayName
      in Orb::Price::BulkWithProration
      in Orb::Price::GroupedTieredPackage
      in Orb::Price::MaxGroupTieredPackage
      in Orb::Price::ScalableMatrixWithUnitPricing
      in Orb::Price::ScalableMatrixWithTieredPricing
      in Orb::Price::CumulativeGroupedBulk
      in Orb::Price::GroupedWithMinMaxThresholds
      in Orb::Price::Minimum
      end
    end

    assert_pattern do
      case response
      in {
        model_type: :unit,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Unit::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Unit::UnnamedTypeWithobjectParent85 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Unit::PriceType,
        replaces_price_id: String | nil,
        unit_config: Orb::UnitConfig,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Package::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Package::UnnamedTypeWithobjectParent86 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_config: Orb::PackageConfig,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Package::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Matrix::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Matrix::UnnamedTypeWithobjectParent87 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_config: Orb::MatrixConfig,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Matrix::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Tiered::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Tiered::UnnamedTypeWithobjectParent88 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Tiered::PriceType,
        replaces_price_id: String | nil,
        tiered_config: Orb::TieredConfig,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        bulk_config: Orb::BulkConfig,
        cadence: Orb::Price::Bulk::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Bulk::UnnamedTypeWithobjectParent89 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Bulk::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :threshold_total_amount,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ThresholdTotalAmount::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ThresholdTotalAmount::UnnamedTypeWithobjectParent90 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ThresholdTotalAmount::PriceType,
        replaces_price_id: String | nil,
        threshold_total_amount_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredPackage::UnnamedTypeWithobjectParent91 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredPackage::PriceType,
        replaces_price_id: String | nil,
        tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedTiered::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedTiered::UnnamedTypeWithobjectParent92 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedTiered::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredWithMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredWithMinimum::UnnamedTypeWithobjectParent93 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredWithMinimum::PriceType,
        replaces_price_id: String | nil,
        tiered_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_package_with_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredPackageWithMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredPackageWithMinimum::UnnamedTypeWithobjectParent94 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredPackageWithMinimum::PriceType,
        replaces_price_id: String | nil,
        tiered_package_with_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :package_with_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::PackageWithAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::PackageWithAllocation::UnnamedTypeWithobjectParent95 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        package_with_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::PackageWithAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_percent,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::UnitWithPercent::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::UnitWithPercent::UnnamedTypeWithobjectParent96 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::UnitWithPercent::PriceType,
        replaces_price_id: String | nil,
        unit_with_percent_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MatrixWithAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MatrixWithAllocation::UnnamedTypeWithobjectParent97 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_with_allocation_config: Orb::MatrixWithAllocationConfig,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MatrixWithAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :tiered_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::TieredWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::TieredWithProration::UnnamedTypeWithobjectParent98 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::TieredWithProration::PriceType,
        replaces_price_id: String | nil,
        tiered_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :unit_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::UnitWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::UnitWithProration::UnnamedTypeWithobjectParent99 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::UnitWithProration::PriceType,
        replaces_price_id: String | nil,
        unit_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_allocation,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedAllocation::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedAllocation::UnnamedTypeWithobjectParent100 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_allocation_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedAllocation::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_prorated_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithProratedMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithProratedMinimum::UnnamedTypeWithobjectParent101 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_prorated_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithProratedMinimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_metered_minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithMeteredMinimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithMeteredMinimum::UnnamedTypeWithobjectParent102 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_metered_minimum_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithMeteredMinimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :matrix_with_display_name,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MatrixWithDisplayName::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MatrixWithDisplayName::UnnamedTypeWithobjectParent103 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        matrix_with_display_name_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MatrixWithDisplayName::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :bulk_with_proration,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        bulk_with_proration_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        cadence: Orb::Price::BulkWithProration::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::BulkWithProration::UnnamedTypeWithobjectParent104 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::BulkWithProration::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedTieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedTieredPackage::UnnamedTypeWithobjectParent105 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedTieredPackage::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :max_group_tiered_package,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::MaxGroupTieredPackage::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::MaxGroupTieredPackage::UnnamedTypeWithobjectParent106 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        max_group_tiered_package_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::MaxGroupTieredPackage::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_unit_pricing,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ScalableMatrixWithUnitPricing::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ScalableMatrixWithUnitPricing::UnnamedTypeWithobjectParent107 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ScalableMatrixWithUnitPricing::PriceType,
        replaces_price_id: String | nil,
        scalable_matrix_with_unit_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :scalable_matrix_with_tiered_pricing,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::ScalableMatrixWithTieredPricing::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::ScalableMatrixWithTieredPricing::UnnamedTypeWithobjectParent108 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::ScalableMatrixWithTieredPricing::PriceType,
        replaces_price_id: String | nil,
        scalable_matrix_with_tiered_pricing_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :cumulative_grouped_bulk,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::CumulativeGroupedBulk::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::CumulativeGroupedBulk::UnnamedTypeWithobjectParent109 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        cumulative_grouped_bulk_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::CumulativeGroupedBulk::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :grouped_with_min_max_thresholds,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::GroupedWithMinMaxThresholds::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::GroupedWithMinMaxThresholds::UnnamedTypeWithobjectParent110 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        grouped_with_min_max_thresholds_config: ^(Orb::Internal::Type::HashOf[Orb::Internal::Type::Unknown]),
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::GroupedWithMinMaxThresholds::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      in {
        model_type: :minimum,
        id: String,
        billable_metric: Orb::BillableMetricTiny | nil,
        billing_cycle_configuration: Orb::BillingCycleConfiguration,
        cadence: Orb::Price::Minimum::Cadence,
        composite_price_filters: ^(Orb::Internal::Type::ArrayOf[Orb::TransformPriceFilter]) | nil,
        conversion_rate: Float | nil,
        conversion_rate_config: Orb::Price::Minimum::UnnamedTypeWithobjectParent111 | nil,
        created_at: Time,
        credit_allocation: Orb::Allocation | nil,
        currency: String,
        discount: Orb::Discount | nil,
        external_price_id: String | nil,
        fixed_price_quantity: Float | nil,
        invoicing_cycle_configuration: Orb::BillingCycleConfiguration | nil,
        item: Orb::ItemSlim,
        maximum: Orb::Maximum | nil,
        maximum_amount: String | nil,
        metadata: ^(Orb::Internal::Type::HashOf[String]),
        minimum: Orb::Minimum | nil,
        minimum_amount: String | nil,
        minimum_config: Orb::Price::Minimum::MinimumConfig,
        name: String,
        plan_phase_order: Integer | nil,
        price_type: Orb::Price::Minimum::PriceType,
        replaces_price_id: String | nil,
        dimensional_price_configuration: Orb::DimensionalPriceConfiguration | nil
      }
      end
    end
  end
end
