module Orb
  module Resources
    class Coupons
      attr_reader subscriptions: Orb::Resources::Coupons::Subscriptions

      def create: (
        discount: Orb::Models::CouponCreateParams::discount,
        redemption_code: String,
        ?duration_in_months: Integer?,
        ?max_redemptions: Integer?,
        ?request_options: Orb::request_opts
      ) -> Orb::Coupon

      def list: (
        ?cursor: String?,
        ?limit: Integer,
        ?redemption_code: String?,
        ?show_archived: bool?,
        ?request_options: Orb::request_opts
      ) -> Orb::Internal::Page[Orb::Coupon]

      def archive: (
        String coupon_id,
        ?request_options: Orb::request_opts
      ) -> Orb::Coupon

      def fetch: (
        String coupon_id,
        ?request_options: Orb::request_opts
      ) -> Orb::Coupon

      def initialize: (client: Orb::Client) -> void
    end
  end
end
