module Orb
  module Resources
    class CreditNotes
      def create: (
        line_items: ::Array[Orb::CreditNoteCreateParams::LineItem],
        ?memo: String?,
        ?reason: Orb::Models::CreditNoteCreateParams::reason?,
        ?request_options: Orb::request_opts
      ) -> Orb::CreditNote

      def list: (
        ?created_at_gt: Time?,
        ?created_at_gte: Time?,
        ?created_at_lt: Time?,
        ?created_at_lte: Time?,
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> Orb::Internal::Page[Orb::CreditNote]

      def fetch: (
        String credit_note_id,
        ?request_options: Orb::request_opts
      ) -> Orb::CreditNote

      def initialize: (client: Orb::Client) -> void
    end
  end
end
