module Orb
  module Resources
    class DimensionalPriceGroups
      attr_reader external_dimensional_price_group_id: Orb::Resources::DimensionalPriceGroups::ExternalDimensionalPriceGroupID

      def create:
        (
          Orb::Models::DimensionalPriceGroupCreateParams
          | ::Hash[Symbol, top] params
        ) -> Orb::Models::DimensionalPriceGroupModel
        | (
          billable_metric_id: String,
          dimensions: ::Array[String],
          name: String,
          external_dimensional_price_group_id: String?,
          metadata: ::Hash[Symbol, String?]?,
          request_options: Orb::request_opts
        ) -> Orb::Models::DimensionalPriceGroupModel

      def retrieve:
        (
          String dimensional_price_group_id,
          ?Orb::Models::DimensionalPriceGroupRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Orb::Models::DimensionalPriceGroupModel
        | (
          String dimensional_price_group_id,
          request_options: Orb::request_opts
        ) -> Orb::Models::DimensionalPriceGroupModel

      def list:
        (
          ?Orb::Models::DimensionalPriceGroupListParams
          | ::Hash[Symbol, top] params
        ) -> Orb::Page[Orb::Models::DimensionalPriceGroupModel]
        | (
          cursor: String?,
          limit: Integer,
          request_options: Orb::request_opts
        ) -> Orb::Page[Orb::Models::DimensionalPriceGroupModel]

      def initialize: (client: Orb::Client) -> void
    end
  end
end
