module Orb
  module Resources
    class DimensionalPriceGroups
      attr_reader external_dimensional_price_group_id: Orb::Resources::DimensionalPriceGroups::ExternalDimensionalPriceGroupID

      def create: (
        billable_metric_id: String,
        dimensions: ::Array[String],
        name: String,
        ?external_dimensional_price_group_id: String?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> Orb::DimensionalPriceGroup

      def retrieve: (
        String dimensional_price_group_id,
        ?request_options: Orb::request_opts
      ) -> Orb::DimensionalPriceGroup

      def list: (
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> Orb::Internal::Page[Orb::DimensionalPriceGroup]

      def initialize: (client: Orb::Client) -> void
    end
  end
end
