module Orb
  module Resources
    class Items
      def create: (
        name: String,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> Orb::Item

      def update: (
        String item_id,
        ?external_connections: ::Array[Orb::ItemUpdateParams::ExternalConnection]?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?name: String?,
        ?request_options: Orb::request_opts
      ) -> Orb::Item

      def list: (
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> Orb::Internal::Page[Orb::Item]

      def archive: (
        String item_id,
        ?request_options: Orb::request_opts
      ) -> Orb::Item

      def fetch: (
        String item_id,
        ?request_options: Orb::request_opts
      ) -> Orb::Item

      def initialize: (client: Orb::Client) -> void
    end
  end
end
