module Orb
  module Resources
    class Metrics
      def create:
        (
          Orb::Models::MetricCreateParams | ::Hash[Symbol, top] params
        ) -> Orb::Models::BillableMetric
        | (
          description: String?,
          item_id: String,
          name: String,
          sql: String,
          metadata: ::Hash[Symbol, String?]?,
          request_options: Orb::request_opts
        ) -> Orb::Models::BillableMetric

      def update:
        (
          String metric_id,
          ?Orb::Models::MetricUpdateParams | ::Hash[Symbol, top] params
        ) -> Orb::Models::BillableMetric
        | (
          String metric_id,
          metadata: ::Hash[Symbol, String?]?,
          request_options: Orb::request_opts
        ) -> Orb::Models::BillableMetric

      def list:
        (
          ?Orb::Models::MetricListParams | ::Hash[Symbol, top] params
        ) -> Orb::Page[Orb::Models::BillableMetric]
        | (
          created_at_gt: Time?,
          created_at_gte: Time?,
          created_at_lt: Time?,
          created_at_lte: Time?,
          cursor: String?,
          limit: Integer,
          request_options: Orb::request_opts
        ) -> Orb::Page[Orb::Models::BillableMetric]

      def fetch:
        (
          String metric_id,
          ?Orb::Models::MetricFetchParams | ::Hash[Symbol, top] params
        ) -> Orb::Models::BillableMetric
        | (
          String metric_id,
          request_options: Orb::request_opts
        ) -> Orb::Models::BillableMetric

      def initialize: (client: Orb::Client) -> void
    end
  end
end
