module Orb
  module Resources
    class Metrics
      def create: (
        description: String?,
        item_id: String,
        name: String,
        sql: String,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> Orb::Models::BillableMetric

      def update: (
        String metric_id,
        ?metadata: ::Hash[Symbol, String?]?,
        ?request_options: Orb::request_opts
      ) -> Orb::Models::BillableMetric

      def list: (
        ?created_at_gt: Time?,
        ?created_at_gte: Time?,
        ?created_at_lt: Time?,
        ?created_at_lte: Time?,
        ?cursor: String?,
        ?limit: Integer,
        ?request_options: Orb::request_opts
      ) -> Orb::Internal::Page[Orb::Models::BillableMetric]

      def fetch: (
        String metric_id,
        ?request_options: Orb::request_opts
      ) -> Orb::Models::BillableMetric

      def initialize: (client: Orb::Client) -> void
    end
  end
end
