module Orb
  module Resources
    class TopLevel
      def ping: (
        ?request_options: Orb::request_opts
      ) -> Orb::Models::TopLevelPingResponse

      def initialize: (client: Orb::Client) -> void
    end
  end
end
