module Orb
  module Models
    module Coupons
      type subscription_list_params =
        { cursor: String?, limit: Integer } & Orb::request_parameters

      class SubscriptionListParams < Orb::BaseModel
        extend Orb::RequestParameters::Converter
        include Orb::RequestParameters

        attr_accessor cursor: String?

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          ?cursor: String?,
          ?limit: Integer,
          ?request_options: Orb::request_opts
        ) -> void

        def to_hash: -> Orb::Models::Coupons::subscription_list_params
      end
    end
  end
end
