module Orb
  module Models
    module Plans
      module ExternalPlanID
        type version_retrieve_params =
          { external_plan_id: String } & Orb::Internal::Type::request_parameters

        class VersionRetrieveParams < Orb::Internal::Type::BaseModel
          extend Orb::Internal::Type::RequestParameters::Converter
          include Orb::Internal::Type::RequestParameters

          attr_accessor external_plan_id: String

          def initialize: (
            external_plan_id: String,
            ?request_options: Orb::request_opts
          ) -> void

          def to_hash: -> {
            external_plan_id: String,
            request_options: Orb::RequestOptions
          }
        end
      end
    end
  end
end
