module Orb
  module Internal
    class Page[Elem]
      include Orb::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor pagination_metadata: PaginationMetadata

      def inspect: -> String

      type pagination_metadata = { has_more: bool, next_cursor: String? }
      class PaginationMetadata < Orb::Internal::Type::BaseModel
        attr_accessor has_more: bool

        attr_accessor next_cursor: String?

        def initialize: (has_more: bool, next_cursor: String?) -> void
      end
    end
  end
end
