# frozen_string_literal: true

module Orb
  module Models
    module Customers
      module Credits
        # @see Orb::Resources::Customers::Credits::TopUps#list_by_external_id
        class TopUpListByExternalIDResponse < Orb::Internal::Type::BaseModel
          # @!attribute id
          #
          #   @return [String]
          required :id, String

          # @!attribute amount
          #   The amount to increment when the threshold is reached.
          #
          #   @return [String]
          required :amount, String

          # @!attribute currency
          #   The currency or custom pricing unit to use for this top-up. If this is a
          #   real-world currency, it must match the customer's invoicing currency.
          #
          #   @return [String]
          required :currency, String

          # @!attribute invoice_settings
          #   Settings for invoices generated by triggered top-ups.
          #
          #   @return [Orb::Models::Customers::Credits::TopUpInvoiceSettings]
          required :invoice_settings, -> { Orb::Customers::Credits::TopUpInvoiceSettings }

          # @!attribute per_unit_cost_basis
          #   How much, in the customer's currency, to charge for each unit.
          #
          #   @return [String]
          required :per_unit_cost_basis, String

          # @!attribute threshold
          #   The threshold at which to trigger the top-up. If the balance is at or below this
          #   threshold, the top-up will be triggered.
          #
          #   @return [String]
          required :threshold, String

          # @!attribute expires_after
          #   The number of days or months after which the top-up expires. If unspecified, it
          #   does not expire.
          #
          #   @return [Integer, nil]
          optional :expires_after, Integer, nil?: true

          # @!attribute expires_after_unit
          #   The unit of expires_after.
          #
          #   @return [Symbol, Orb::Models::Customers::Credits::TopUpListByExternalIDResponse::ExpiresAfterUnit, nil]
          optional :expires_after_unit,
                   enum: -> { Orb::Models::Customers::Credits::TopUpListByExternalIDResponse::ExpiresAfterUnit },
                   nil?: true

          # @!method initialize(id:, amount:, currency:, invoice_settings:, per_unit_cost_basis:, threshold:, expires_after: nil, expires_after_unit: nil)
          #   Some parameter documentations has been truncated, see
          #   {Orb::Models::Customers::Credits::TopUpListByExternalIDResponse} for more
          #   details.
          #
          #   @param id [String]
          #
          #   @param amount [String] The amount to increment when the threshold is reached.
          #
          #   @param currency [String] The currency or custom pricing unit to use for this top-up. If this is a real-wo
          #
          #   @param invoice_settings [Orb::Models::Customers::Credits::TopUpInvoiceSettings] Settings for invoices generated by triggered top-ups.
          #
          #   @param per_unit_cost_basis [String] How much, in the customer's currency, to charge for each unit.
          #
          #   @param threshold [String] The threshold at which to trigger the top-up. If the balance is at or below this
          #
          #   @param expires_after [Integer, nil] The number of days or months after which the top-up expires. If unspecified, it
          #
          #   @param expires_after_unit [Symbol, Orb::Models::Customers::Credits::TopUpListByExternalIDResponse::ExpiresAfterUnit, nil] The unit of expires_after.

          # The unit of expires_after.
          #
          # @see Orb::Models::Customers::Credits::TopUpListByExternalIDResponse#expires_after_unit
          module ExpiresAfterUnit
            extend Orb::Internal::Type::Enum

            DAY = :day
            MONTH = :month

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
