# frozen_string_literal: true

module Orb
  module Models
    module Customers
      module Credits
        # @see Orb::Resources::Customers::Credits::TopUps#list
        class TopUpListResponse < Orb::Internal::Type::BaseModel
          # @!attribute id
          #
          #   @return [String]
          required :id, String

          # @!attribute amount
          #   The amount to increment when the threshold is reached.
          #
          #   @return [String]
          required :amount, String

          # @!attribute currency
          #   The currency or custom pricing unit to use for this top-up. If this is a
          #   real-world currency, it must match the customer's invoicing currency.
          #
          #   @return [String]
          required :currency, String

          # @!attribute invoice_settings
          #   Settings for invoices generated by triggered top-ups.
          #
          #   @return [Orb::Models::Customers::Credits::TopUpListResponse::InvoiceSettings]
          required :invoice_settings, -> { Orb::Models::Customers::Credits::TopUpListResponse::InvoiceSettings }

          # @!attribute per_unit_cost_basis
          #   How much, in the customer's currency, to charge for each unit.
          #
          #   @return [String]
          required :per_unit_cost_basis, String

          # @!attribute threshold
          #   The threshold at which to trigger the top-up. If the balance is at or below this
          #   threshold, the top-up will be triggered.
          #
          #   @return [String]
          required :threshold, String

          # @!attribute expires_after
          #   The number of days or months after which the top-up expires. If unspecified, it
          #   does not expire.
          #
          #   @return [Integer, nil]
          optional :expires_after, Integer, nil?: true

          # @!attribute expires_after_unit
          #   The unit of expires_after.
          #
          #   @return [Symbol, Orb::Models::Customers::Credits::TopUpListResponse::ExpiresAfterUnit, nil]
          optional :expires_after_unit,
                   enum: -> { Orb::Models::Customers::Credits::TopUpListResponse::ExpiresAfterUnit },
                   nil?: true

          # @!method initialize(id:, amount:, currency:, invoice_settings:, per_unit_cost_basis:, threshold:, expires_after: nil, expires_after_unit: nil)
          #   Some parameter documentations has been truncated, see
          #   {Orb::Models::Customers::Credits::TopUpListResponse} for more details.
          #
          #   @param id [String]
          #
          #   @param amount [String] The amount to increment when the threshold is reached.
          #
          #   @param currency [String] The currency or custom pricing unit to use for this top-up. If this is a real-wo
          #
          #   @param invoice_settings [Orb::Models::Customers::Credits::TopUpListResponse::InvoiceSettings] Settings for invoices generated by triggered top-ups.
          #
          #   @param per_unit_cost_basis [String] How much, in the customer's currency, to charge for each unit.
          #
          #   @param threshold [String] The threshold at which to trigger the top-up. If the balance is at or below this
          #
          #   @param expires_after [Integer, nil] The number of days or months after which the top-up expires. If unspecified, it
          #
          #   @param expires_after_unit [Symbol, Orb::Models::Customers::Credits::TopUpListResponse::ExpiresAfterUnit, nil] The unit of expires_after.

          # @see Orb::Models::Customers::Credits::TopUpListResponse#invoice_settings
          class InvoiceSettings < Orb::Internal::Type::BaseModel
            # @!attribute auto_collection
            #   Whether the credits purchase invoice should auto collect with the customer's
            #   saved payment method.
            #
            #   @return [Boolean]
            required :auto_collection, Orb::Internal::Type::Boolean

            # @!attribute net_terms
            #   The net terms determines the difference between the invoice date and the issue
            #   date for the invoice. If you intend the invoice to be due on issue, set this
            #   to 0.
            #
            #   @return [Integer]
            required :net_terms, Integer

            # @!attribute memo
            #   An optional memo to display on the invoice.
            #
            #   @return [String, nil]
            optional :memo, String, nil?: true

            # @!attribute require_successful_payment
            #   When true, credit blocks created by this top-up will require that the
            #   corresponding invoice is paid before they are drawn down from. If any topup
            #   block is pending payment, further automatic top-ups will be paused until the
            #   invoice is paid or voided.
            #
            #   @return [Boolean, nil]
            optional :require_successful_payment, Orb::Internal::Type::Boolean

            # @!method initialize(auto_collection:, net_terms:, memo: nil, require_successful_payment: nil)
            #   Some parameter documentations has been truncated, see
            #   {Orb::Models::Customers::Credits::TopUpListResponse::InvoiceSettings} for more
            #   details.
            #
            #   Settings for invoices generated by triggered top-ups.
            #
            #   @param auto_collection [Boolean] Whether the credits purchase invoice should auto collect with the customer's sav
            #
            #   @param net_terms [Integer] The net terms determines the difference between the invoice date and the issue d
            #
            #   @param memo [String, nil] An optional memo to display on the invoice.
            #
            #   @param require_successful_payment [Boolean] When true, credit blocks created by this top-up will require that the correspond
          end

          # The unit of expires_after.
          #
          # @see Orb::Models::Customers::Credits::TopUpListResponse#expires_after_unit
          module ExpiresAfterUnit
            extend Orb::Internal::Type::Enum

            DAY = :day
            MONTH = :month

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
