# frozen_string_literal: true

module Orb
  module Resources
    class Customers
      class Credits
        class TopUps
          # Some parameter documentations has been truncated, see
          # {Orb::Models::Customers::Credits::TopUpCreateParams} for more details.
          #
          # This endpoint allows you to create a new top-up for a specified customer's
          # balance. While this top-up is active, the customer's balance will added in
          # increments of the specified amount whenever the balance reaches the specified
          # threshold.
          #
          # If a top-up already exists for this customer in the same currency, the existing
          # top-up will be replaced.
          #
          # @overload create(customer_id, amount:, currency:, invoice_settings:, per_unit_cost_basis:, threshold:, active_from: nil, expires_after: nil, expires_after_unit: nil, request_options: {})
          #
          # @param customer_id [String]
          #
          # @param amount [String] The amount to increment when the threshold is reached.
          #
          # @param currency [String] The currency or custom pricing unit to use for this top-up. If this is a real-wo
          # ...
          #
          # @param invoice_settings [Orb::Models::Customers::Credits::TopUpCreateParams::InvoiceSettings] Settings for invoices generated by triggered top-ups.
          #
          # @param per_unit_cost_basis [String] How much, in the customer's currency, to charge for each unit.
          #
          # @param threshold [String] The threshold at which to trigger the top-up. If the balance is at or below this
          # ...
          #
          # @param active_from [Time, nil] The date from which the top-up is active. If unspecified, the top-up is active i
          # ...
          #
          # @param expires_after [Integer, nil] The number of days or months after which the top-up expires. If unspecified, it
          # ...
          #
          # @param expires_after_unit [Symbol, Orb::Models::Customers::Credits::TopUpCreateParams::ExpiresAfterUnit, nil] The unit of expires_after.
          #
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [Orb::Models::Customers::Credits::TopUpCreateResponse]
          #
          # @see Orb::Models::Customers::Credits::TopUpCreateParams
          def create(customer_id, params)
            parsed, options = Orb::Models::Customers::Credits::TopUpCreateParams.dump_request(params)
            @client.request(
              method: :post,
              path: ["customers/%1$s/credits/top_ups", customer_id],
              body: parsed,
              model: Orb::Models::Customers::Credits::TopUpCreateResponse,
              options: options
            )
          end

          # Some parameter documentations has been truncated, see
          # {Orb::Models::Customers::Credits::TopUpListParams} for more details.
          #
          # List top-ups
          #
          # @overload list(customer_id, cursor: nil, limit: nil, request_options: {})
          #
          # @param customer_id [String]
          #
          # @param cursor [String, nil] Cursor for pagination. This can be populated by the `next_cursor` value returned
          # ...
          #
          # @param limit [Integer] The number of items to fetch. Defaults to 20.
          #
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [Orb::Internal::Page<Orb::Models::Customers::Credits::TopUpListResponse>]
          #
          # @see Orb::Models::Customers::Credits::TopUpListParams
          def list(customer_id, params = {})
            parsed, options = Orb::Models::Customers::Credits::TopUpListParams.dump_request(params)
            @client.request(
              method: :get,
              path: ["customers/%1$s/credits/top_ups", customer_id],
              query: parsed,
              page: Orb::Internal::Page,
              model: Orb::Models::Customers::Credits::TopUpListResponse,
              options: options
            )
          end

          # This deactivates the top-up and voids any invoices associated with pending
          # credit blocks purchased through the top-up.
          #
          # @overload delete(top_up_id, customer_id:, request_options: {})
          #
          # @param top_up_id [String]
          # @param customer_id [String]
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [nil]
          #
          # @see Orb::Models::Customers::Credits::TopUpDeleteParams
          def delete(top_up_id, params)
            parsed, options = Orb::Models::Customers::Credits::TopUpDeleteParams.dump_request(params)
            customer_id =
              parsed.delete(:customer_id) do
                raise ArgumentError.new("missing required path argument #{_1}")
              end
            @client.request(
              method: :delete,
              path: ["customers/%1$s/credits/top_ups/%2$s", customer_id, top_up_id],
              model: NilClass,
              options: options
            )
          end

          # Some parameter documentations has been truncated, see
          # {Orb::Models::Customers::Credits::TopUpCreateByExternalIDParams} for more
          # details.
          #
          # This endpoint allows you to create a new top-up for a specified customer's
          # balance. While this top-up is active, the customer's balance will added in
          # increments of the specified amount whenever the balance reaches the specified
          # threshold.
          #
          # If a top-up already exists for this customer in the same currency, the existing
          # top-up will be replaced.
          #
          # @overload create_by_external_id(external_customer_id, amount:, currency:, invoice_settings:, per_unit_cost_basis:, threshold:, active_from: nil, expires_after: nil, expires_after_unit: nil, request_options: {})
          #
          # @param external_customer_id [String]
          #
          # @param amount [String] The amount to increment when the threshold is reached.
          #
          # @param currency [String] The currency or custom pricing unit to use for this top-up. If this is a real-wo
          # ...
          #
          # @param invoice_settings [Orb::Models::Customers::Credits::TopUpCreateByExternalIDParams::InvoiceSettings] Settings for invoices generated by triggered top-ups.
          #
          # @param per_unit_cost_basis [String] How much, in the customer's currency, to charge for each unit.
          #
          # @param threshold [String] The threshold at which to trigger the top-up. If the balance is at or below this
          # ...
          #
          # @param active_from [Time, nil] The date from which the top-up is active. If unspecified, the top-up is active i
          # ...
          #
          # @param expires_after [Integer, nil] The number of days or months after which the top-up expires. If unspecified, it
          # ...
          #
          # @param expires_after_unit [Symbol, Orb::Models::Customers::Credits::TopUpCreateByExternalIDParams::ExpiresAfterUnit, nil] The unit of expires_after.
          #
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [Orb::Models::Customers::Credits::TopUpCreateByExternalIDResponse]
          #
          # @see Orb::Models::Customers::Credits::TopUpCreateByExternalIDParams
          def create_by_external_id(external_customer_id, params)
            parsed, options = Orb::Models::Customers::Credits::TopUpCreateByExternalIDParams.dump_request(params)
            @client.request(
              method: :post,
              path: ["customers/external_customer_id/%1$s/credits/top_ups", external_customer_id],
              body: parsed,
              model: Orb::Models::Customers::Credits::TopUpCreateByExternalIDResponse,
              options: options
            )
          end

          # This deactivates the top-up and voids any invoices associated with pending
          # credit blocks purchased through the top-up.
          #
          # @overload delete_by_external_id(top_up_id, external_customer_id:, request_options: {})
          #
          # @param top_up_id [String]
          # @param external_customer_id [String]
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [nil]
          #
          # @see Orb::Models::Customers::Credits::TopUpDeleteByExternalIDParams
          def delete_by_external_id(top_up_id, params)
            parsed, options = Orb::Models::Customers::Credits::TopUpDeleteByExternalIDParams.dump_request(params)
            external_customer_id =
              parsed.delete(:external_customer_id) do
                raise ArgumentError.new("missing required path argument #{_1}")
              end
            @client.request(
              method: :delete,
              path: [
                "customers/external_customer_id/%1$s/credits/top_ups/%2$s",
                external_customer_id,
                top_up_id
              ],
              model: NilClass,
              options: options
            )
          end

          # Some parameter documentations has been truncated, see
          # {Orb::Models::Customers::Credits::TopUpListByExternalIDParams} for more details.
          #
          # List top-ups by external ID
          #
          # @overload list_by_external_id(external_customer_id, cursor: nil, limit: nil, request_options: {})
          #
          # @param external_customer_id [String]
          #
          # @param cursor [String, nil] Cursor for pagination. This can be populated by the `next_cursor` value returned
          # ...
          #
          # @param limit [Integer] The number of items to fetch. Defaults to 20.
          #
          # @param request_options [Orb::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [Orb::Internal::Page<Orb::Models::Customers::Credits::TopUpListByExternalIDResponse>]
          #
          # @see Orb::Models::Customers::Credits::TopUpListByExternalIDParams
          def list_by_external_id(external_customer_id, params = {})
            parsed, options = Orb::Models::Customers::Credits::TopUpListByExternalIDParams.dump_request(params)
            @client.request(
              method: :get,
              path: ["customers/external_customer_id/%1$s/credits/top_ups", external_customer_id],
              query: parsed,
              page: Orb::Internal::Page,
              model: Orb::Models::Customers::Credits::TopUpListByExternalIDResponse,
              options: options
            )
          end

          # @api private
          #
          # @param client [Orb::Client]
          def initialize(client:)
            @client = client
          end
        end
      end
    end
  end
end
