module Orb
  module Models
    module DimensionalPriceGroups
      type external_dimensional_price_group_id_retrieve_params =
        {  } & Orb::Internal::Type::request_parameters

      class ExternalDimensionalPriceGroupIDRetrieveParams < Orb::BaseModel
        extend Orb::Internal::Type::RequestParameters::Converter
        include Orb::Internal::Type::RequestParameters

        def initialize: (?request_options: Orb::request_opts) -> void

        def to_hash: -> Orb::Models::DimensionalPriceGroups::external_dimensional_price_group_id_retrieve_params
      end
    end
  end
end
