module Orb
  module Models
    module Customers
      module Credits
        type affected_block =
          { id: String, expiry_date: Time?, per_unit_cost_basis: String? }

        class AffectedBlock < Orb::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor expiry_date: Time?

          attr_accessor per_unit_cost_basis: String?

          def initialize: (
            id: String,
            expiry_date: Time?,
            per_unit_cost_basis: String?
          ) -> void

          def to_hash: -> {
            id: String,
            expiry_date: Time?,
            per_unit_cost_basis: String?
          }
        end
      end
    end
  end
end
