module Orb
  module Models
    module Customers
      module Credits
        type ledger_create_entry_by_external_id_params =
          {
            add_credit_ledger_entry_request: Orb::Models::add_credit_ledger_entry_request
          }
          & Orb::request_parameters

        class LedgerCreateEntryByExternalIDParams < Orb::BaseModel
          extend Orb::RequestParameters::Converter
          include Orb::RequestParameters

          attr_accessor add_credit_ledger_entry_request: Orb::Models::add_credit_ledger_entry_request

          def initialize:
            (
              add_credit_ledger_entry_request: Orb::Models::add_credit_ledger_entry_request,
              request_options: Orb::request_opts
            ) -> void
            | (
              ?Orb::Models::Customers::Credits::ledger_create_entry_by_external_id_params
              | Orb::BaseModel data
            ) -> void

          def to_hash: -> Orb::Models::Customers::Credits::ledger_create_entry_by_external_id_params
        end
      end
    end
  end
end
