module Orb
  module Models
    module Customers
      module Credits
        type ledger_create_entry_response =
          Orb::Customers::Credits::IncrementLedgerEntry
          | Orb::Customers::Credits::DecrementLedgerEntry
          | Orb::Customers::Credits::ExpirationChangeLedgerEntry
          | Orb::Customers::Credits::CreditBlockExpiryLedgerEntry
          | Orb::Customers::Credits::VoidLedgerEntry
          | Orb::Customers::Credits::VoidInitiatedLedgerEntry
          | Orb::Customers::Credits::AmendmentLedgerEntry

        module LedgerCreateEntryResponse
          extend Orb::Internal::Type::Union

          def self?.variants: -> ::Array[Orb::Models::Customers::Credits::ledger_create_entry_response]
        end
      end
    end
  end
end
