module Orb
  module Models
    module Customers
      module Credits
        type top_up_list_params =
          { cursor: String?, limit: Integer } & Orb::request_parameters

        class TopUpListParams < Orb::BaseModel
          extend Orb::RequestParameters::Converter
          include Orb::RequestParameters

          attr_accessor cursor: String?

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          def initialize:
            (
              cursor: String?,
              limit: Integer,
              request_options: Orb::request_opts
            ) -> void
            | (
              ?Orb::Models::Customers::Credits::top_up_list_params
              | Orb::BaseModel data
            ) -> void

          def to_hash: -> Orb::Models::Customers::Credits::top_up_list_params
        end
      end
    end
  end
end
