module Orb
  module Models
    module Customers
      module Credits
        type top_up_create_by_external_id_params =
          {  } & Orb::request_parameters

        class TopUpCreateByExternalIDParams < Orb::Models::AddCreditTopUpRequest
          extend Orb::RequestParameters::Converter
          include Orb::RequestParameters

          def initialize:
            (request_options: Orb::request_opts) -> void
            | (
              ?Orb::Models::Customers::Credits::top_up_create_by_external_id_params
              | Orb::BaseModel data
            ) -> void

          def to_hash: -> Orb::Models::Customers::Credits::top_up_create_by_external_id_params
        end
      end
    end
  end
end
