module Orb
  module Models
    module Customers
      module Credits
        type top_up_delete_by_external_id_params =
          { external_customer_id: String }
          & Orb::Internal::Type::request_parameters

        class TopUpDeleteByExternalIDParams < Orb::Internal::Type::BaseModel
          extend Orb::Internal::Type::RequestParameters::Converter
          include Orb::Internal::Type::RequestParameters

          attr_accessor external_customer_id: String

          def initialize: (
            external_customer_id: String,
            ?request_options: Orb::request_opts
          ) -> void

          def to_hash: -> {
            external_customer_id: String,
            request_options: Orb::RequestOptions
          }
        end
      end
    end
  end
end
